# On the host this runs within the same docker-compose.yaml as prometheus
# Remember to verify the path to the snmp.yml file
version: "3"

services:

  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp_exporter
    restart: unless-stopped
    volumes:
      - ./snmp_exporter/snmp.yml:/etc/snmp_exporter/snmp.yml
    ports:
      - 9116:9116
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"
