---
services:
  prometheus-pve-exporter:
    image: prompve/prometheus-pve-exporter
    container_name: prometheus-pve-exporter
    volumes:
      - "./pve.yml:/etc/prometheus/pve.yml"
    ports:
      - "9221:9221"
    init: true
