services:
  vscode-server:
    container_name: visual-code
    image: visual-code:latest
    ports:
      - "8585:8585"
    user: "${UID}:${GID}"
    volumes:
     - ./data:/home/tbryant:Z
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_network
      traefik.http.routers.code-server.rule: Host(`visual-code.timmybtech.com`)
      traefik.http.services.code-server.loadbalancer.server.port: 8585

networks:
  default:
    name: traefik_network
    external: true
