global:
  scrape_interval: 60s

  external_labels:
    origin_prometheus: homelab-oci02

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 60s
    static_configs:
      - targets: ["10.0.0.166:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
    relabel_configs:
      - source_labels: [__address__]
        regex: ".*"
        target_label: instance
        replacement: "homelab-oci02"

  - job_name: crowdsec
    static_configs:
      - targets:
          - homelab-oci02.tailebee.ts.net:6060
          - homelab-oci02.tailebee.ts.net:60601
    metrics_path: /metrics
    relabel_configs:
      - source_labels:
          - __address__
        regex: .*
        target_label: instance
        replacement: homelab-oci02
