services:
  zabbix-server:
    image: docker.io/zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - "10051:10051"
    network_mode: host
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export

  zabbix-web-nginx-pgsql:
    image: docker.io/zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: "10.0.0.26"
      PHP_TZ: ${PHP_TZ}
    # ports:
    #   - "${ZABBIX_FRONTEND_PORT}:8080"
    network_mode: host
    cap_add:
      - SYS_ADMIN
    volumes:
      - zabbix-web-data:/usr/share/zabbix
      - ./custom-nginx.conf:/etc/nginx/nginx.conf:z
      - ./custom-zabbix.conf:/etc/php84/php-fpm.d/zabbix.conf:z

  zabbix-agent:
    image: docker.io/zabbix/zabbix-agent2:latest
    container_name: zabbix-agent
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "zabbix-server"
      ZBX_SERVER_HOST: "10.0.0.26"
      ZBX_SERVER_PORT: "10051"
      ZBX_SERVER_ACTIVE: "10.0.0.26"
    network_mode: host
volumes:
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:
  zabbix-web-data:
