global:
    # By default, scrape targets every 15 seconds.
    scrape_interval: 60s
    # For Prometheus federation
    external_labels:
        origin_prometheus: podman-01
scrape_configs:
    - job_name: prometheus
      scrape_interval: 60s
      static_configs:
        - targets:
            - localhost:9090
    - job_name: node_exporter
      static_configs:
        - targets:
            - node-exporter:9100
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: podman-01
    - job_name: podman_exporter
      static_configs:
        - targets:
            - 192.168.86.143:9882
      metrics_path: /metrics
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: podman-01
    - job_name: postgres
      static_configs:
        - targets:
            - 192.168.86.143:9187
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: postgresql.homelab.lan
    - job_name: uptime
      scheme: http
      metrics_path: /metrics
      static_configs:
        - targets:
            - 192.168.86.143:3001
      # Only needed if authentication is enabled (default)
      basic_auth:
        password: uk1_4I2zzKKrOnjQ1ZpLF9eq-5i8kb3k3hoR5CfSHZw3
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: podman-01
    - job_name: cloudflared
      scrape_interval: 60s
      metrics_path: /metrics
      static_configs:
        - targets:
            - 192.168.86.143:60123
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: "hoarder|healthchecks.timmybtech.com"
