---
services:
  cf-tunnel:
    image: docker.io/cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate --metrics 0.0.0.0:60123 run podman-01
    volumes:
      - ./cloudflared:/etc/cloudflared:Z
    ports:
      - 60123:60123
    labels:
      io.containers.autoupdate: "registry"
