---
services:
  cf-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: app-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate --metrics 0.0.0.0:60123 run
    volumes:
      - ./cloudflared:/etc/cloudflared:Z
    ports:
      - 60123:60123
    depends_on:
      - app
