version: "3"

services:
  pgweb:
    container_name: pgweb  # optional
    restart: always  # optional
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    # links:
    #   - postgres:postgres  # my database container is called postgres, not db
    environment:
      - DATABASE_URL=postgres://${PG_DB_USER}:${PG_DB_PASSWORD}@${PG_DB_HOST}/postgres
    # depends_on:
    #   - postgres  # my database container is called postgres, not db
