services:
  pulse-server:
    # Build context commented out - using pre-built image from Docker Hub
    build:
      context: .
      dockerfile: Dockerfile
    # image: rcourtman/pulse:latest # Use the pre-built image from Docker Hub
    container_name: pulse
    restart: unless-stopped
    ports:
      # Map container port 7655 to host port 7655
      # You can change the host port (left side) if 7655 is already in use on your host
      - "7655:7655"
    env_file:
      # Load environment variables from a .env file in the same directory as this compose file
      - .env # Standard location
    # Optional: Define networks if needed, otherwise uses default bridge network
    # networks:
    #   - pulse_network

# Optional: Define a network
# networks:
#   pulse_network:
#     driver: bridge
