version: '3.3'
services:
    prometheuscommunity:
        network_mode: host
        container_name: 'postres_exporter'
        environment:
            - 'DATA_SOURCE_NAME=postgresql://${PG_DB_USER}:${PG_DB_PASSWORD}@${PG_DB_HOST}:5432/postgres?sslmode=disable'
        image: quay.io/prometheuscommunity/postgres-EXPORTER
        restart: unless-stopped
