#ENC[AES256_GCM,data:BubI1Hig242Nfv6YrV4bKWgsOSP7viD85e7RFHz6stayZcQFMaNJ5tflMnw+7x9fRsH/v8bnAFaoQDgeBvnVyLcQEVq73Q==,iv:bNhe9+ZeLasvsdsrD58xaHS9cVcvTATAB+HmJomNW9c=,tag:pCj+F5NGJYfQOow7Vj7b6A==,type:comment]
cron: ENC[AES256_GCM,data:x6Y+PQqzx7KQ02YT,iv:MP8pz5AviU5R5ukSO3sNteMGTCE2Sxv1LY9eJjE6d3A=,tag:rZBBMeSJIr3pi4LVR+DLAw==,type:str]
#ENC[AES256_GCM,data:OMPEVF+5IQLK0SF0S6Mmc7a4kVydK2wMMi/tDPGZfldRB8mE,iv:Q8u1mN/s/y0mytVy5CHAGjxBlM/1DGSo+ScWCbVYGFs=,tag:gswMfRofDFn8JvRAmrCnjw==,type:comment]
runOnStart: ENC[AES256_GCM,data:qHXhBA==,iv:3AKDAwFG7FAkYXji7NX9pQNh3UVYc1Jdt3+j3Ss1Y5A=,tag:RxiQncl1FcMaG7NqsgTqmw==,type:bool]
origin:
    #ENC[AES256_GCM,data:ZAlzn3KB+m9X3xndwRfzAlS7eXMKo+TVNXCS,iv:AVl7viihju4dqgbnMn4sNWvUx8cCLCJEoUhE7rANMOk=,tag:ku/FsVw9AKJRSqs9l4aCVg==,type:comment]
    url: ENC[AES256_GCM,data:pXXZfL21F9j1oTwRh1wJXGe6XgDL,iv:3tjco9MZewN0sY1VlBVzOE4RroC8xaHMpgh5jadr1Qc=,tag:ez6kgKnPxGZlIZNCYhzc8w==,type:str]
    #ENC[AES256_GCM,data:32KQuflcPH/QDTrtWjxduDbwoqREwLYc4GHSXWh94ujIQd5LV0Ns9GHj1H7yu54lw72evTs=,iv:/29OteVhPomuyBu4aezuEpA+R02g9mQ/xu2CDflTt3w=,tag:PDDZYYF+EsJBTrSHlI4ppQ==,type:comment]
    #ENC[AES256_GCM,data:6ZMwUZh3IT9HB41pyI9FmGqMMbtdMz6rpuDtxqvQN4MLBCnoWe6gKhEEaA/6,iv:39kjJHCRaorUhZ2Tkupd/nS1Sx6rXkPscaV/+k1iC3g=,tag:5Cx07eTW8iexEPULfJOxoA==,type:comment]
    username: ENC[AES256_GCM,data:WPRABRgvAQ==,iv:t+kNTa0OxDS5hs7W6QX0fh3Mfq0FdRRlbQplzOe17Ks=,tag:A3+6FRk3gAyn4wXrZ1YBOw==,type:str]
    password: ENC[AES256_GCM,data:N2ttI/9ngT6lXeSZW0k9Jm4=,iv:+F6THKD2KeC2dw8VuhDVdXDSt+mu9CIElpv8HbvihAw=,tag:1Ja3jbvAhqFsxNEQV+jdkA==,type:str]
#ENC[AES256_GCM,data:7ynf01GOzERanSHw+5/LeFwp02QAhLRvPjA1fBSrlttl4FpUV2vY+g==,iv:zKnJ8tY/YWJrv9dm7tjba5Uhe9ma8lto9l7pi8SSf84=,tag:bbWQ6SgeizPpn8sFD5wclg==,type:comment]
#ENC[AES256_GCM,data:qQpDZF7mVrtH,iv:W/9r9BJX9eScGS3PFfrt1AjRx9CUYXNfXbO05X6RGdQ=,tag:cJif+MNn+yDxQXIsjdtRjw==,type:comment]
#ENC[AES256_GCM,data:cW0waUyIPGXwJoH6/vH3lsR3xwB/PJHPp/cmfA==,iv:UwSI57336Bx6ILHGjKlGlgQFYSLdG9fAzlS/A6ybk70=,tag:lDHhI0NPeLCLw3blZWPFKA==,type:comment]
#ENC[AES256_GCM,data:MSjdOSmlWO1NGtI4gTOjwFIQNNXELD4sqCEjErTwMxs2ERHMewI=,iv:Dhd0f/W3fUyMMlVFr7V8K3rvbVqBEk7/cLk4I5JD0Ao=,tag:g+XOFhhP8giK+XEdCi8/Gg==,type:comment]
#ENC[AES256_GCM,data:TbuhOvqiqjp/04dBIT5Xols=,iv:0nLZ4+YhIJNRn4UDGhZTL+R1OSPb8ath8uMvq+/rDW4=,tag:qWjTFYspPGUkUD7sUqEa3g==,type:comment]
#ENC[AES256_GCM,data:JpZ53dHvPVDF/XbJB//u9eEDmGaokaVn,iv:KChDUOpbZVl5q4YhTc4+wOjoqumSHY5f1y3v5Doa/1k=,tag:3OSOAmGvb6GXqt6rY+x+yw==,type:comment]
#ENC[AES256_GCM,data:qmvqqOxFh5OtkrIcd5d7aGpB02aVBRNEUVqMVnbPR5R4I/O+PCZOFXmSoQGNqQqL,iv:KxlcL7YZZghAmbxX8l0JRA03j+iBaxajVsUnHaKVfyw=,tag:RQ03xQaXA3EBa1Izn5Seyg==,type:comment]
replicas:
    - ENC[AES256_GCM,data:dvEEYTuLKzdMqmI+EoY7y2nG8enfAegCvYeVBA==,iv:vak+x9FxlQsx3kTJpZWTihiyKltHVxHsmczl23OukSk=,tag:mG0wOcl0OksdQ43pX3Q5Lg==,type:comment]
    - ENC[AES256_GCM,data:2848tMDrfaJ42eQnKFCSKF41Lb0AyGsXy+MRIenNrJJOevgJ8/PpkY4Q,iv:eyLVo67Lp4e2Fv3Tc4Xpn3B3qVb82d5Vcaf/Ea5s9cQ=,tag:62zkq5rGE8TcT4Fz5alrJw==,type:comment]
    - ENC[AES256_GCM,data:LUyyND6DLpeKClFolt0bSBRiKN3n,iv:+Jtb+fUnmYh/AGkBbPPi/hsZs2CZLH8IFXR/h36v0Xo=,tag:0IYZGQp5EhZEHEiJm7BQYw==,type:comment]
    - ENC[AES256_GCM,data:T9XUVQbnLMM8DpeRSxo/m7FkWsgV9AOpwYZ+PA==,iv:exyDP9+xnnBV5Rh1vPblvXhSEyyZFvsi3ogDvenbonc=,tag:JnzT7Wb03qiNYnmMHLv8Bg==,type:comment]
    - url: ENC[AES256_GCM,data:gXpX/DsV8Mk7MbhZE5DL2IX3GOid,iv:WH5PO+5dtlDQyY/IlDLNjuQYNSWlQYlt+e0T64obfE8=,tag:LPOhDzDAMl/MKlceq6ewQw==,type:str]
      username: ENC[AES256_GCM,data:E5Y10dx7AA==,iv:4yTWZb2/oDWotil9/kmYSeqUJH6U2pULgznANH4/RFw=,tag:g1wxq+bb2dO4dgSwf3v0tw==,type:str]
      password: ENC[AES256_GCM,data:E34wkLDcDy6ZvWJYHFx/N+0=,iv:59PPYoTdsgXqvwCuis3w4zKrS+Dg38ESYlJ/9MqHJXQ=,tag:Pme/egzfbShvrI9AksQQbQ==,type:str]
      #ENC[AES256_GCM,data:GAj7nQZOYuZa2W9aPIQMGfAIOyW9qe9m7g3t2rgOxp+IMN9gX+i6f3/loVoXJtwWW2nCDBl7gy6zfdSREjt2xD6GDSI/,iv:JJLH4wO8GS919jdFNPhUNk1j4rbftSbo4nf17cg0gcE=,tag:HqGamT+FzevD3AkIaZsnug==,type:comment]
#ENC[AES256_GCM,data:CYAA1latCnKMFrex40LBs1hHIO61166bXM9b5ao6A4YdfMz91fKMoYXQIbjMNWqYOjeWNLWbYEHO,iv:Midr22aqmeEGZDkxZOxpXv+BRtQSNQmM0vtnzsyl5L8=,tag:T7NR3QZD5N62AGbc1u9FvQ==,type:comment]
api:
    #ENC[AES256_GCM,data:Tm3yzBy8WvcTKHWqtV8CHmhq/w==,iv:d1o9CkWdQx5b172EjJ3pQL2c9futzGwhcPMuTnYL2bk=,tag:Jn7Ep+Pl/B7hWAJhrO2EKg==,type:comment]
    port: ENC[AES256_GCM,data:Q8ghhw==,iv:5msWyNKbe0eQfcfE2DmgZnlSySnjF2YM/Y5deeanewY=,tag:AkDT3V4mHEegWsCUWFIn6Q==,type:int]
    #ENC[AES256_GCM,data:W5nnT3ziRzw+1jUqQsiIuzfqFvpxbpjgiHivUEUqYcizpPNPHVybEFY7iCXIDThwRIapFoO5F3feZw7g0JRoEwqWhfjP0N6iB5/53w==,iv:v31JRNehv0z5eT4zNSVTKSX1sHclXJ15a8FfDDYt2gY=,tag:nrHGdoh477dIudgZwCFz1Q==,type:comment]
    #ENC[AES256_GCM,data:dTspHQTC3y/feOVFZZXl1Q2cJQ==,iv:oCpo7AJJlv3CU/FBvIPtzSnTBUegEZ7e7gk/nzQxZ3A=,tag:OyLVSPPuN3rSK3kJEbW8tw==,type:comment]
    #ENC[AES256_GCM,data:RdAjEcsLCPhSALXfpiWEPC4iEA==,iv:jqojlnVbmLae6oo1cUDzbD5tjn10Krc9nlq7+YqXewA=,tag:CLgHAXyg/QyW8qDkDyGTJA==,type:comment]
#ENC[AES256_GCM,data:59pppgp94Tkc17qkad7DCTXoVvj+2+cyLe3Q+G82w7AAyC67ZJz3Wvnp3prAnT9zRSvoEZ6HaAh7/9E7NKg=,iv:sOrnLK8wm8FLC+QTU3Gu6SLSiLA/XIRlTDwcVKxv+vE=,tag:1lIa4BSKqZ3z1ZAAEBdHDw==,type:comment]
features:
    generalSettings: ENC[AES256_GCM,data:5nnL1w==,iv:XhojNDKlzvGsKth6LRgczBNaBpNN9fePFP/CciNlCfI=,tag:E+nzGP4FKrtImoFL/LK9KQ==,type:bool]
    queryLogConfig: ENC[AES256_GCM,data:o40bng==,iv:BCZEEefGD+dorI+1WBxazga3mbTKv5HRfJxRdfDQOtI=,tag:k2Qsk8M0a3OPkihEI+cM4A==,type:bool]
    statsConfig: ENC[AES256_GCM,data:N4QRrw==,iv:oEa9yIklW+jNqUIiJbNs5tSwpt1gacw+mJzEle0ndW8=,tag:YdlV/352udBklFUwwqiNTg==,type:bool]
    clientSettings: ENC[AES256_GCM,data:fdLmQg==,iv:Ju44kvg4fPXfPwjWRLVoThhmOzD9XlDQ8FNkEF28Tz0=,tag:J78V9MltxnnuuE1fjnSMtg==,type:bool]
    services: ENC[AES256_GCM,data:dELkzQ==,iv:E6Igvh//q0WfLXh7LrDahE6YLM2IlX5L3KmhGD5fmJE=,tag:nsOGkN5NHQSkCE5WADe1UA==,type:bool]
    filters: ENC[AES256_GCM,data:HQA50Q==,iv:MNXQR+8cLmbd60pnV57BbE5xYOHOueqIgbt80u13zU8=,tag:7SJQEvYW0PbiNTKwnExIQA==,type:bool]
    dhcp:
        serverConfig: ENC[AES256_GCM,data:/Pod0sQ=,iv:7Tk/3fTYLRL8u3rjsp3TE0f6fePtQMnNYMeobSbPlE0=,tag:790gz+AcRlASz46jRe7vcQ==,type:bool]
        staticLeases: ENC[AES256_GCM,data:dT7b4qA=,iv:+mDQqXxaddHVYLd6gHKql2j11uXyAl++RI9YFPD9qBY=,tag:sDBCeKMdCZ+JoXvZ9bzn4g==,type:bool]
    dns:
        serverConfig: ENC[AES256_GCM,data:utbLXQ==,iv:rcpl6nG8VS8lX38NdzytD2XNz5aR6sOD01zFaqKur0s=,tag:bkDE9CV2JqNBicgv7GE3IA==,type:bool]
        accessLists: ENC[AES256_GCM,data:u9jEww==,iv:ixgODfn3deoRqmbOuRFMw3gkvKy49Csix7AN0UVTkjQ=,tag:gyuEddiW8tmlilb9OqDJlw==,type:bool]
        rewrites: ENC[AES256_GCM,data:pOma0w==,iv:/CvAub0C9a33qyFlm4yWjnr33sclahH/q6I4bBU5xwg=,tag:yyGgZzGhuL1h8neh/nVZjQ==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY3dFcGhYcnVFQjlRUndO
            aHdmOXpFb1NVS2NzNmJheTBIWm4zWXdCZFdzCnRSNEk0YUhqK244aCt3QnJDL0Rk
            ODlCYXdTNWVxN2p0M3FxOFhmSUNxSmcKLS0tIEdvaU9OSXprTXFWS25MK1R6cGRs
            ZkRXUC83RkJHY01DeG83d3R5bXl4UnMKQ0drvO9Lvc3Nt4LkEaKF0rBOdRLEd/H/
            T1bsQF6ogyEg44XydYP7Yv/6MdlvMRJg6L6Z//5gZWoqzWuou9iTiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T22:20:03Z"
    mac: ENC[AES256_GCM,data:itdEYgrhaSThAC4PlzZ67c5Qw5t7sZa2t8wBEDWIm0mIrvNukg7Js1BGG6kxZYIsRJ5N+aJ+8lmDck+m/lNPhDfpmoyA381TBgEfVmUoohgk5a6/tuu9EfDmT5DAu0yU6XKrOWiPEQQBQ49BqFLP+a0kXpieTYR8Qhtqbp1OG3E=,iv:EudliF1n3pt+4FLGCJfM47G35YPJiQ2V8RArkVpSJII=,tag:IXFP2hgPaoRTunO4HONK4Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
