#ENC[AES256_GCM,data:/V4f8EeV2jujeBho3lpccH47OoP6M7qPYQUIaU94PoezFGYDxXyXUEB+6vheWMZKDNJ2HbWBdp5oVzrjOnVE4y6kjrkFkw==,iv:FiL6ACkepRxKyXp8WtnXtcptEUZn9f3wE3mzpvIE+ao=,tag:BpYMajR8y1gbk51QIE3cbw==,type:comment]
cron: ENC[AES256_GCM,data:Pw2+037f2o9E41BX,iv:2vItiRFfeYRonb9sHyVy7pcC3YTE2603q+/baDgnU9g=,tag:HeodfXfIcCH2Jfi5q2lmXw==,type:str]
#ENC[AES256_GCM,data:a9aRVCLrG4d8QwS6if+yV4118wwMx1qMWHFWMjUgT4Q0kLOt,iv:RJcO8K0yqIJ2/Fi7WS8YCXBdgF/XROIPYT5BeTbNA9Q=,tag:3b9nSgVvqmTqqS4PoIBTvQ==,type:comment]
runOnStart: ENC[AES256_GCM,data:LNsbQQ==,iv:FNVovUY/G2CdRfsX9m1W1rP1bt6hUd59P3rkI6n/vrk=,tag:DaOulHNKqcmEMNH1Z+KhXw==,type:bool]
origin:
    #ENC[AES256_GCM,data:2VPCo57LRxRPcbMfALGNXxtsRpgB7F07oeY/,iv:/stU/D275SPuOBOfUzcxBOG6tswosMIIjvsIKy2X/VI=,tag:OkPa6C338XXS+VxKi7mCeQ==,type:comment]
    url: ENC[AES256_GCM,data:NfuvcLq4kkEsFGamj37qPa13+/Vm,iv:EEpe7jvEv3YM5/ygl+AxLDyMjtREjad523A1vvGhNvc=,tag:P4tCTFSsLRY0sHeyM+qb6Q==,type:str]
    #ENC[AES256_GCM,data:hAXjxFiE8jfTcbok/wRKaDrNTEQOw/1ZI6Itamnzr4ozz50ARq9fWYWqoZjjHabLRP0BT28=,iv:wtYOMrzkGY9j4xfPIZu8KLnYmPsU5AvYEcJnE71vhDQ=,tag:MViGk1zfGGJ/6qcibhxr2A==,type:comment]
    #ENC[AES256_GCM,data:ZyzbHD/ciU5OURaL6hY2dDkxvbjU/AO2ipouEa222ZMBCPVXEjY8FRHgCzyz,iv:Qxc0siVV3yScj9ygDe8R2OwlWRq+2ZXu5LYPERq1Q4Q=,tag:mIY2DL4BnoPGb73hOFX0lw==,type:comment]
    username: ENC[AES256_GCM,data:KuvaMNICig==,iv:L4ihbk6O0k247QouqsB26gt20WRE98/kIkYwBmrtAI4=,tag:JIaw0V2BkQzxzk8TmAKCXg==,type:str]
    password: ENC[AES256_GCM,data:qInSMKG4koXS61+qFe+epoc=,iv:CzH3ReLl/gyty74LHqqa2YdX95YjUZKSG81VBiRRj88=,tag:Fo1gcxHi+6p2HAZLazOhow==,type:str]
#ENC[AES256_GCM,data:L7T7ytGdNfdpUA6fZWBD1qikq4fD6q8LOCPOht9cZvpyVjSZzBKSog==,iv:7TRfoee5T4Zy7tpgjUeIqt1bf0sgOVIkm8yLwUERKNc=,tag:Bl8gjjx381HfcH0s6CEIsQ==,type:comment]
#ENC[AES256_GCM,data:YRsG5buwxvYL,iv:ie2nrqsL+Yankfz1KhjpCoSBLPrgs56IhIxO+e0uun0=,tag:rWmROEl8iZ2TbSIie3OU3Q==,type:comment]
#ENC[AES256_GCM,data:WPsrbhPt523gc5SLzdrBJ7J7OnsaZR7MeDUoJw==,iv:/z7WLMqRCAhC3HrCAh19sMSgIl5XbkS3UxNthetIiPk=,tag:66V5lW0I3odPBBsiNHpyZA==,type:comment]
#ENC[AES256_GCM,data:+x5UFo9qicq6QTP5BJLmCPL04LKMWe16GQK1TnMWJkaY5z/zxRw=,iv:cc4TsvnBdmy0g91EWz1bZQDg4O6nnj7UhXOHcqLOXfk=,tag:qVs+6QjQQeU2VE0bC5j/Zg==,type:comment]
#ENC[AES256_GCM,data:HFsCZnPtxZW8dEo6UFwWBnE=,iv:WIKvDmSUcLXMcIIj6gvh1fk5wVrxfe7S4HOPAeu65a8=,tag:1/Rrh6syFad7agketTUjww==,type:comment]
#ENC[AES256_GCM,data:exoprzLCCMn1HuwUOIy9iRn9OgRQhHdy,iv:8KJSw9a74JtExEVgVfErTmUv/Bg0zl7lNo4144fYoNo=,tag:SH++7ks8djTgj9AohxTVTg==,type:comment]
#ENC[AES256_GCM,data:jwiRxk592iTDX8qjKp0HPwD6S1w4sxmOolpbnXKrUNyFsRjuRV+QAl8Hze2owgVr,iv:Hrg4zVpeiN4/13cZwWWKg5NnZU1ngk0LA63NtTJU8GU=,tag:1BrbLRpcFs/OUbo3dyXTuw==,type:comment]
replicas:
    - ENC[AES256_GCM,data:RNmuFsBzy0BYx+YfN7oBWdJ8vnq1yvJuOzo4Nw==,iv:CKps/ss8rYg/BYd4mPXrJGepGv0mCISVWHjQrtsfeKk=,tag:3BYngKaPjOrZ42VsF3mIBg==,type:comment]
    - ENC[AES256_GCM,data:t935YWDtbbEKBQ3pfCf6Nf8qM+iSa2g6T25yQjPgahQifbdql2hPfXh4,iv:/0cLyREKT2W7LaccJdsfgWSNvrlhZjFDNi/sz6PYVyk=,tag:59S/1csGIAzeP7jpCYZ+BQ==,type:comment]
    - ENC[AES256_GCM,data:VhkKnlkc64ig6/mnG/wJPsNpTBMV,iv:poqG15jEmH49/qlxuqLUMMJ7lOMqfXy527qD0QIcIAg=,tag:P2EBDmcofP8g/vXGTgYAFw==,type:comment]
    - ENC[AES256_GCM,data:i/AfigGQLvkYQ+VxXPnq4pnE4k0qz6VosBDFfg==,iv:FiR18TaiK5/LWqXdBjSgRhcVUpSLVSt12oQA18q8oOQ=,tag:MQ2wIfKammFTUwsPIie2BQ==,type:comment]
    - url: ENC[AES256_GCM,data:GmGlmT4hZyX9UpsrFQU0XFjCH2Oe,iv:qGSHwlsdLZMA+DSvLT1ifir/J4Sr8Td3zCX1Cfy+jTg=,tag:O4U+xny52ILheRBcOkOyxQ==,type:str]
      username: ENC[AES256_GCM,data:4mnIoryPmg==,iv:C0dGJJxq7IosnwZTayT5+if3jryr4CgMHwhJ80HNBjk=,tag:7Zfl/62A3LdMwklqBSBIiQ==,type:str]
      password: ENC[AES256_GCM,data:YYG63sTrD/Mp+iezooo5ddk=,iv:0Muoaz6F2oowcX7k5OfrQRmE1V6bU/zaPQ8NUQ00PZ4=,tag:vxLI1yFnu07TFCkngUP0PQ==,type:str]
      #ENC[AES256_GCM,data:0k3Usa1wkgyuOSBDhlnkrLDjEaP3CW2LTpxAVd3nvGpKRt9ntwFoIFB00/pTud8xFRxhUxR5vlKaJPNs4CK/xtsRbidn,iv:WLtx/ze++y7PxhufyGdgdurqmuEKqtUvMAGsBXnvh+Y=,tag:sdRcfIJAkjaE4ILk2mnypw==,type:comment]
#ENC[AES256_GCM,data:sniSa3tlrdgnwW1l12V/jdfbkTRNEATL6jvBSDvcfRkGv4cDlJoyfizYkJwtNadTlNjuvUqFU9yn,iv:dET5Ei3yE95AMEKp7a82Z2l1TknztFlmbftdWNHChdU=,tag:5wir9oVHLRMJ/W+M25LgRQ==,type:comment]
api:
    #ENC[AES256_GCM,data:RH9pbtGZZJKIggQJpR7nHKBhtQ==,iv:MMDQXzDEn1R39OZ248OlBFnmcdkqXyyr05Q2yXHyloA=,tag:9t+9ssMQngML/B4iSqxKQQ==,type:comment]
    port: ENC[AES256_GCM,data:kz3uDw==,iv:jzUaP+ejj08gzD9FfHO8WhKxsW3ermdbPwrwIaD4KoM=,tag:zTYFjHhbESJQvCqhc7vhRQ==,type:int]
    #ENC[AES256_GCM,data:GBUoAXVS2mPS/7LU7iueb5PrDDMG78zdrsPZ4X3xWxfKaW3lM46Rv/yr3rM/u65Vq8TNvNXHQLf+sg1NVfXKMxynAtqWjNedP0f5cA==,iv:zzkZwXTr2Nnkzk1Kfry6t7O05H7tSAIJkfFLyMjO1D0=,tag:bcQdqyh5vUelnB7aMBbLxw==,type:comment]
    #ENC[AES256_GCM,data:+zePx8vWaiPg3YZIUeHGsvRDSA==,iv:JfyChi21iupAnwSEQ3lsDqfaGCnor2ms/2zrwVLtwvQ=,tag:Q1Osv5guVPrzo8nbXaN9CQ==,type:comment]
    #ENC[AES256_GCM,data:lJLp5+FX7HPwlPvZLidOh1sXFA==,iv:aUzesGh2dcXix4F9Ujn6MNB3jZ8gO7x5pvfq4VipsPg=,tag:KCDIDxBVghSwm8pVpd4KGg==,type:comment]
#ENC[AES256_GCM,data:n6Tt0GnSBfPMPF5bgEvb4OY42CwICXVJaxvztVeThDnxA875Pflf58LigC4uOS7JYSAeI9HqLxh5hPylcjE=,iv:Z3ctCx5q1hfosU1s/IK/mID/DyGo7bYj+Mh57XkC4lU=,tag:L/e9rEZkEdpoG0CWHj9DwA==,type:comment]
features:
    generalSettings: ENC[AES256_GCM,data:uCgROg==,iv:NdJPRxK4PtM3Kf4Kvfj0aB85TT264JSnAzxJNy7wqk8=,tag:KdWfCSYjmDTwNryK2CLm4g==,type:bool]
    queryLogConfig: ENC[AES256_GCM,data:AXxTeQ==,iv:3MvurLI6ibmG+Ltr08mOdCP8/YDklo8wFo7xOwADzWE=,tag:9hDKRLrX4QuiGs7e4M1DmQ==,type:bool]
    statsConfig: ENC[AES256_GCM,data:TQSQKQ==,iv:GZxomFwYgLX7cL6oEa5JFlyaXgoSpTa7jlqzSonBAr0=,tag:l9tih53syCSJh5EymEH6ww==,type:bool]
    clientSettings: ENC[AES256_GCM,data:S1sV8Q==,iv:BeQSfdTiwwLjhuapCMhULUX0PgojlsKeOxzLxGD+OZ4=,tag:iGz73A3El7PetZcxevJJ6g==,type:bool]
    services: ENC[AES256_GCM,data:yZ+Trw==,iv:4lmr1NnSbVcvxQCg6MLzkfmCcN4CgGfrdUFBUTpS10E=,tag:kZ6H1ZQ2UW+w1vxjSv4T5g==,type:bool]
    filters: ENC[AES256_GCM,data:EDimIw==,iv:PTUL2oMgLBulzWXwVDS8MqNypmDeJujtVCeBj0/uW7E=,tag:dPDWlZp1Znaldi06pTgLdg==,type:bool]
    dhcp:
        serverConfig: ENC[AES256_GCM,data:I4LaiuM=,iv:pVRXiExOYcVqCqe9gNnokYFxNGY5uBzsmtrpDwCKO6Q=,tag:52GfCLPmuMXzgio0xbD7Ng==,type:bool]
        staticLeases: ENC[AES256_GCM,data:C6xGhk8=,iv:2+woYot4rsHPWM25/wmCrWIalENYMvESGNqd2fduSjU=,tag:gx9brYei65Bj3nvvMQpBRw==,type:bool]
    dns:
        serverConfig: ENC[AES256_GCM,data:mKek5Q==,iv:R9t030m1WI/vY+Yzc3qKRR0rB8vG7EIIe8r1h3/fdfo=,tag:zsIPyLt/KNyk4mVgoJagzQ==,type:bool]
        accessLists: ENC[AES256_GCM,data:P85rVQ==,iv:SVHjkU2RYvoay8soQ9Lo5gCG+1vwC+aNZo0wFvSVYLI=,tag:WIzdHGf4ut06tHkUOb/ZYg==,type:bool]
        rewrites: ENC[AES256_GCM,data:qDQTVQ==,iv:4mmDfthNAC6PFtOQdwxhxjL/e+NgJYJ3KNilGPTshb0=,tag:I4lRutClrScv/hgzB5hFSw==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySk5MbXF1REZncGZDRUo4
            bmxjOGNxcXMvY21QcjhTS1ZRN2UycVNOUmtZCkhMNTc1STZ5cG1iTnhYc2pOc3lq
            V1p1dkJHWVdRT1FuRFptbFNJRGk2RWsKLS0tIGFFZ0lHemtIdEF0aXl0dWU0enBu
            d2E5SlB0T1ZWL1VpS0ZVNjZQN0JNeEEKuAfBeShVjKC7C6APqNfNPRU7bTPsn+lz
            Awdr+iW5lDDKujpHb90STayu+BnFr9JgbwmuCk5jQThYwszi5CRsww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T06:06:42Z"
    mac: ENC[AES256_GCM,data:jDRL1OnklukKChyMkF3C8Mf8GgbzVL2+HbwFv0qeQGBYRmg+YN7GIkqFWpGY90ZKcRoypXkdQ8fUP7NOk5QCY1bzNYjJwo1aFpZfzPpkMeSA4R6mjLO4bIzBE0m7n7foHMTEMeryYmqsP4KP+8C1EjY6S1pB0flNYZRrz27TVsM=,iv:uxo6VEK+uqJXL2N9V6ItbLJLxXQthvoQ9puXR5sy4I4=,tag:wyUY6zxcX726Km9xz9UXdw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
