#ENC[AES256_GCM,data:SEmooOBDLrFP5xZmqDmLc8TbZfWxMcIKZVmJAPhBoZZ/XM8NGobDwlaA+wqES4taXBDPXFA0UF2DVK36S/BpqkiutM+5xw==,iv:EXfLxY8AEVrjuAMPM5Wx2o3uTwUgUe29GCkEvoYr7dc=,tag:Ie4GmQ9cw5rz3VAV2eYfJg==,type:comment]
cron: ENC[AES256_GCM,data:wC315GAsGu3YIDl3,iv:MUiCJGq6ifIJ8va3Ue6RHexWdfmVduDVi7Cv1FkFJhY=,tag:6OUMPdrC19tbDUyiRNhwpA==,type:str]
#ENC[AES256_GCM,data:dv3iICMZ1r8uDelM+KyZUBOipY99Jd2747NQeiq+qhKQHq3g,iv:pI+kO0UNqtzty6U/jcF7lrehR3EVlXcEMr9T8WDIH/4=,tag:6r4l6g9y2DyxPV7RxZD5GA==,type:comment]
runOnStart: ENC[AES256_GCM,data:LxmmyQ==,iv:FP2NXDojn+U/axh8HOkqAnL6IXpaF1iyJIOO7W+G0Wg=,tag:WkRP4uMv15Ir0I6LD+JGlw==,type:bool]
origin:
    #ENC[AES256_GCM,data:lYzo2+V6RH69HUcOedmt5YpXycY27FaspCbg,iv:qTtjAhVZ3n4IYe851dYXgWXDabbUKQ89MHEdXIcjzvo=,tag:SGp9g1eUIBUfapBhbaJvrg==,type:comment]
    url: ENC[AES256_GCM,data:NXBIuoYOxgDH6VWlkxU7ZCRTfEqT,iv:Yv/iGfweYpvbeEopzGcU/cNoCBkTCvm+sAl9nQ/KVlA=,tag:xoto55YlU0ahX7r6NpOBjA==,type:str]
    #ENC[AES256_GCM,data:EVjG32GJtS2qVfq5jfmaosa0cK1KpUa+DiQW8zlAMJaLwvattJfoT8GZoBT/PATYUQkYXgM=,iv:2pnXERAX7wIA8AN2b7zHRgIjwYGalI7fhIRo8auzrKA=,tag:oUeKOXlVkTW1zaxJ5y33iQ==,type:comment]
    #ENC[AES256_GCM,data:OIHMth3N7fZCRvCMBI88864jbShUkOLqUhobKfw1DqPL5VaWLJ9VSg6FKzID,iv:YOZD1njlU8jTl8Gtk3rywx7Vfsr+43JCjJ+5DJTGauA=,tag:OBd13VQZrUME1YqBtt2DZQ==,type:comment]
    username: ENC[AES256_GCM,data:eMv/WvsC5A==,iv:ix2QYoAYqk16/e4RS5LVfBb7TK6+jLZ6nydEST3pDo0=,tag:/Kr+6aDImqeZsqCLwsf+5w==,type:str]
    password: ENC[AES256_GCM,data:BTxddoPUfLcYWEshp75TiPE=,iv:O8I/y7KJandF0lQdtf19iEv2dCiL+tQBDdGQbycyGOg=,tag:nDeL2yPby9egi933rJCMiw==,type:str]
#ENC[AES256_GCM,data:YqnAePkA/PIJ3v7IWNSSR+AGnJx8OrBvz7TFBxp9b+9UerUkknHTBw==,iv:oDKOUdS9vH1tBXfU+tRaXGfzNh8avRvxMT7j5hiVtf8=,tag:67bWmZ6P0z5J/zQI+zOvUw==,type:comment]
#ENC[AES256_GCM,data:CHC6w2nQ/zck,iv:VSVOqA5tdK226eK2QVXHLnXVasE/8vS2P5GVFBnPzBk=,tag:2YdVuyGoFquZc+h8a6u5XA==,type:comment]
#ENC[AES256_GCM,data:n9lC1pjHhUosK7/F25VoYH8yeudC9wGYyfmxfw==,iv:9EAPqWM2ThdbUCPa4jH6/zBUrTlleMtLgmG7ZWNJwIg=,tag:okeEoI5HUL8W/LbUFAfOiw==,type:comment]
#ENC[AES256_GCM,data:b/VIkNwGljs8VGIRIUZTnV8e6Ubyx3TDjEBZkPOQfusJG1vWFyk=,iv:f2YU6eEXRjhkC7UEjilJM/7BV0TookLW2HVHBrc46xc=,tag:mv5YOe37Bto2I/fvOfdcGA==,type:comment]
#ENC[AES256_GCM,data:tK86jgdSEJzO9YQPXKYKdi4=,iv:0E1ymN8qkkVhtY3xB88xVCToD2CIlpdKnKYoCMPiVqI=,tag:ou97zJ8xM4hkAGAdd9ju7A==,type:comment]
#ENC[AES256_GCM,data:AU2CoAurTB/waSeyid7OBn+IeVjgGq0b,iv:gqWbsdypQq6DJ4izFRsqq/UHpryBXPBzkrAPRfKUkCU=,tag:PcG5bLaWvA+ODTKZvLYfrQ==,type:comment]
#ENC[AES256_GCM,data:6tCY+/FGPJ2CTKBRvT7Jdpn0GTy9WsAxSw6kQlKEuo6gB/SvZ8bzB/LWk+adDIbn,iv:+kptmKVDsnT3daC5uMEtCcUt0Nxf+fU/eFSYCertD6c=,tag:xmCmU90CGDFJpRySUNXfCw==,type:comment]
replicas:
    - ENC[AES256_GCM,data:/VfpR1RdOn0sOhUDYR3o5zuAAq1J4d1QoRIBfQ==,iv:CNMcHEfxUM1CzH6X7RXPieFIf86ZwdSzdl9Vc8PVoP4=,tag:49bLdFNix3F7RicyZJpcGQ==,type:comment]
    - ENC[AES256_GCM,data:TkV8Np6/qEcqdeQFjmVEe/6eIeuA7K/zV4qiYMMucHexeX/QuX+1kvZK,iv:KvmpZ6VtdGtPmmx+bgDed6YxuQpso+fp29SnDmd6IO8=,tag:uEq58U3ElOhF+qzF0KC+cw==,type:comment]
    - ENC[AES256_GCM,data:EBWDZmx7mDTDfml/bJC72GbyGub3,iv:M/1AdydBhg7w3sfd9MINORfQHpEzFCeOX9roE/jQqAI=,tag:7uq+8cAHDi3Cs6YX8yTM+w==,type:comment]
    - ENC[AES256_GCM,data:H60WGn4b4XWGBy7vhELAPoi4qLf/qffDdsDhqg==,iv:x15d9iE7UeheJ0gvuEuzCdw/AL8npwjH1D1/lPUjIBc=,tag:ISsaBaqm7FP5amQwUm1Ttg==,type:comment]
    - url: ENC[AES256_GCM,data:9ZYqiAlwC1buzMuDzd2rr6G544HE,iv:91b3y/rQas7+ouuMlYWxhqEo01kcknT3Ap6x0O9oxNc=,tag:7yj+yJVoI4HAV6+MR9QQyg==,type:str]
      username: ENC[AES256_GCM,data:Y4QGfPrQog==,iv:uPFU2uYUZbhj8aNiodfvH/8Udnzbf7tBv7R4KT3PNkM=,tag:h2V356x84wcPpaFcj5Eptw==,type:str]
      password: ENC[AES256_GCM,data:90AF4KhuAqG5kluZ9BiaY3I=,iv:wNI0iMPoqjLe5UvDhcQHnyqB4pSz+C8vhu5ko4pFZKM=,tag:VOiDhXkIyDMiCfnPHC0wnA==,type:str]
      #ENC[AES256_GCM,data:JS74230ODxDaJKiKYO0uGSZIo3bNVMR8PsQpTDrMy474NHFPtPlmEwkVWeijoBZa5RCN9l6y8TjBCNfpC9tpPweV6D9f,iv:mFCFhSus7hlUZzz6FPwYIpKEYAZdixDlp5GcgbrxqUc=,tag:StYwT7HTbIv24ZvBST3XXA==,type:comment]
#ENC[AES256_GCM,data:U8LQAv3C6gsPiXL+nW6jCmQKioGJ+FUEKCkbdZIm+jRJVCahIoMRUHWAWhwXLLGHFjaJliEk8XCs,iv:VNMI0NasR0RZD1Eam8MaUevuQheaImwQuP6msAiO2OY=,tag:6QQTN35D5Jno3niYPKPQzw==,type:comment]
api:
    #ENC[AES256_GCM,data:UilvCEz3WoeRzADk85sl3tkRig==,iv:HJiXpohaZZRt23il5v7Ve39rltP2o9G4v3qT4/35+fI=,tag:zb6kWQgG5sUTYUQr9BTkEw==,type:comment]
    port: ENC[AES256_GCM,data:OVV4Ww==,iv:aDekgpaR/ClY6jp+uGOfKRjAEdutrPNdokZSFi5/fZs=,tag:tQxbAEjr/UgMRVX08M6qhw==,type:int]
    #ENC[AES256_GCM,data:tt7lv8UVJ6mbIkB0fdlrHHduCyy+0A2sltZRkT1uZu4k8I3n9y+W8WWYF7RtMzLvfawl/HsryDD6XQHy2puYhO6DdlVwS9BjFY7fqg==,iv:PD3HMGOTjjS/IDoOLfTss5g3rDxAWaWWC0FV+d1kD6U=,tag:MGqIU3sQCk4poPtxoXCLoQ==,type:comment]
    #ENC[AES256_GCM,data:9cslOajQ0T/GiWpJ6vmQrNmVoA==,iv:zUPRO+ols9MLScBm6bLHgDV3jT9TAodyG2wFGyUcmL0=,tag:Vh1lKrt3iX7tV2kTLWVsOw==,type:comment]
    #ENC[AES256_GCM,data:LOA+TPDLMF4BBXshVU3EVAutgw==,iv:3GY4ezOfcwzHUaGjx8axklhmccLahDqy+s2FzmYxPBI=,tag:R9q67vCMWoVMXOLBu1AD7g==,type:comment]
#ENC[AES256_GCM,data:SWDvko5Stwg6J10YFCEOqO39MWBujQinCRgb5TyrfhKR0Mg4uvPfTpxT5pH/9vdvzn2oEINPFZOjQC2BGi8=,iv:3JW+Gu0avi71T6vr5crwntOWUcUxHCQ/7YD/RuMIzX0=,tag:ZxMVIZYaZFN1mC+YwSi6jg==,type:comment]
features:
    generalSettings: ENC[AES256_GCM,data:aksKqg==,iv:N6dkCgfOrci1vScOMMLt6+B919CFVSlCNpZePaYpgVs=,tag:zHu6jJsiaKCiEx+AfA+slA==,type:bool]
    queryLogConfig: ENC[AES256_GCM,data:hIBx1Q==,iv:y1zsTh9k3nOGBofn5mrNjuy7dH3Mjc+WWvGS/Ohu66M=,tag:DAbgd1kT1JCxfQpRj9sZoQ==,type:bool]
    statsConfig: ENC[AES256_GCM,data:m63y+g==,iv:c3pMXVp0EYJkCUrS03D1aky8wKGAFD3xL+TdFNkRLcs=,tag:cLJfbI4QcQ8eeq6ekvKeVA==,type:bool]
    clientSettings: ENC[AES256_GCM,data:BYbNfQ==,iv:ETgbqJRJXigCMMQmwITHcIHfNyRtN54tRl7aR2ISk40=,tag:FpxJLa2s5AqR77it7iC3XQ==,type:bool]
    services: ENC[AES256_GCM,data:nc2/wg==,iv:/l7H3b9rS3G4+kwE7QeuhU9+s82JhDONcCqF5aaZjew=,tag:eWBGNxBKRqRPa0r8yE0nAg==,type:bool]
    filters: ENC[AES256_GCM,data:HP9jKw==,iv:FIG8vIR/XIPRlI1qjy2koLbxCcvRrdi20vCj3DmFX3g=,tag:r+7rdOebglsobUjkkL1H3Q==,type:bool]
    dhcp:
        serverConfig: ENC[AES256_GCM,data:wr1I1kw=,iv:ShWm2UIVPILi/lt0u078rdw6/m3lY00r1745Hskv2bc=,tag:Q4eVmnaVsLxsbiHcGdtFyA==,type:bool]
        staticLeases: ENC[AES256_GCM,data:fjRJ9ao=,iv:ffel2tkf/O76LVSxg3e8shDGO1u4Ffqo9HOvuAbo/Bo=,tag:PJaw6zTwyZhvFgarEdhrQA==,type:bool]
    dns:
        serverConfig: ENC[AES256_GCM,data:LxHQJA==,iv:sbITQKMoNf3jdA9wocgVU0WpgpvUtAhkkIv61HFA7oQ=,tag:dto8+J2b8NzdyLPdsFY2Rw==,type:bool]
        accessLists: ENC[AES256_GCM,data:CuT48w==,iv:dITtpyAzZruNecnG8nr0oo0EEDScXo27LCriocvJ9LQ=,tag:XoLQ0Wxn0XFwzn6WhEe4qA==,type:bool]
        rewrites: ENC[AES256_GCM,data:fLJGXw==,iv:lszaze+rjYyCZ8YRHBmMM+X+lmkWEWi0s+4hXVz2NrQ=,tag:GOXfthwPSs0p5TmQNZyM8g==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Ykk4T0c2bnJpLzFRb2Np
            OFhCZzI4UXdKQXJJQUJ5OFJ4Rnd0NWtYTWhVClpGU09TUTViS0V0NThmWVNqN0k1
            Z21KN0VUWG4rUElmd21iY1o1QmZKRXcKLS0tIGVvWWFJVmRsOUg2L1puT21KazVa
            YXR3cG9pNFNyam5PWStOU2NmM0oxbG8KcSYvZtvGHj2zewh7f0UJrgzlcPmC0QdA
            KptAuA7K4U3DNfl2vzVIS4oK+/HxdqTqEw6ZG31dl7b7DI6TVwIRUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T07:21:56Z"
    mac: ENC[AES256_GCM,data:hQZGSjF+oqK7H7nRptAqJfctJrN+8FAzze2UsqgnSwY1fwzd4iRTNGGZpZcSCTjiT5QYvr/jSyAchQ35VRLdffLQb477NkguXfcOLcDhhmHQBvSxEAExn6lGNyz73ehSuWVqSEQEV12RwV3rndHdThuulf3MsbkqZSEBSGor0yw=,iv:9VqmmpUgnlvv2CwDacmvdZFk1KLjdtgdN1te1tMX2+k=,tag:57GENEzajROzCHzynhjI8g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
