#ENC[AES256_GCM,data:8tJx1cpRrsqAAYrM5zlSMhLZu8IpmT6Ds26XSyup4UNC86jt9r826wR9PJtFEkJYYSneI1TZh49hlGG++C6MoNWlrPBkSQ==,iv:Zsh5TH7twtoKTkB89uPYV+nXJawpUhOzPyKcAdDAx/c=,tag:cC2k9LEToTfbR2cthFPvGA==,type:comment]
cron: ENC[AES256_GCM,data:3fvUJL0bDhIny8cC,iv:9HTsissAKTvbWGBYDEVxLqw5O5tTBmQG2EkNw1AB7rI=,tag:cSqHTMEI5HXeO4H0xGE2Dw==,type:str]
#ENC[AES256_GCM,data:248VLhSjJeDYSxLNK8EOwXhOO0YaEiaiIadJTIIOwkFb1yMV,iv:3uF5Kye0r1DIASEezh77mwYRlr3nWVduv1yMtqz9A6E=,tag:F36xIa3RdrQWpcre6JMdkg==,type:comment]
runOnStart: ENC[AES256_GCM,data:VIvBRA==,iv:3POpCa+D6bCEHA0sHm+aza6Xf/UAI2Wi6M/+7MUFK5Y=,tag:v7ltJLmfFg2poYQjpatmAg==,type:bool]
origin:
    #ENC[AES256_GCM,data:XVOqrBtDN+U6vz1nyuNqVQAiqmS9sMOFnh2u,iv:L65As5KpxradNUuSaOh4AriYDF8PTZQyVjrjpIZgfpY=,tag:okWYfDgHEHmc3a6v95wFpA==,type:comment]
    url: ENC[AES256_GCM,data:jirrNqWL8Gn6v9W/BJ51VwKvzktPrFcnlHnwlJSg,iv:lCkFvonujVef4l3lgi0/EW/dFvDmtqUPL3HJTjcmpm8=,tag:DHxv/HOplsZ1Pn4myAqsFQ==,type:str]
    #ENC[AES256_GCM,data:fcKG5WcKZjPQhgG0YtP/TyMxP34O3v8PTCLHd1Zv/FLIVrN3vQveHDOoISjeLZluvd2TkAA=,iv:UooiXrFEqf8ERaBd/VSlRlR+pip3gT2BEVK3CjQFis8=,tag:lvJZfzP4/2+ewPGEfxbvUw==,type:comment]
    #ENC[AES256_GCM,data:ZuzO9gQCZaXHFuNS5GGHHmA2+EKIMseVZcc7MOafqD4Kvw/fkxPj+/mi/rV1,iv:7CSvGP83Q7V0896LkzaaDVQAK0grJpLVcXw+DGIloHA=,tag:mWifP4Q1Wu6H9E5Msw4rVA==,type:comment]
    username: ENC[AES256_GCM,data:BqTFw3M=,iv:YvtantP0b1up0wrexNhnqjfFs9qDLxUSlAZn1COcCA8=,tag:wbh1Mi1H5V8azs1Qgkaw5Q==,type:str]
    password: ENC[AES256_GCM,data:43zyKGBWNk1ofJq5,iv:jA6xQx4wWlG5pOFBnoIWaHSslqVq9Ke66gUYh+0SXH4=,tag:tlKcvCzVyTk1hAY4JxFgsA==,type:str]
#ENC[AES256_GCM,data:E/T9f+7S1e8aVf4MPo/G1g0fpSZPy03OXJmeE7oEhFWNGWY4V3tX2g==,iv:j0QEXGiQ1s5AD0dv/uLSe42P8kN4wRE5IwrA/0/mMcg=,tag:ftOs0oIp3wn6JgRYmZmQcA==,type:comment]
#ENC[AES256_GCM,data:NHG0z2sX9lB4,iv:f1/ux7sbPFcN7SHCjCa4UILOqNaYlA5DwXxYW9rbJYQ=,tag:2FPpuHXT7uO/LPxx7SnRvw==,type:comment]
#ENC[AES256_GCM,data:BP6PIfGU8k5S/Y9Ckco1JD2vAXq/m4iQfQHaQw==,iv:wqfgcrBE7LINllpoRMZT1QGf5jbrXzppeDcsSb+lNQ0=,tag:QnfW2tPHS41KduH5oHyYkw==,type:comment]
#ENC[AES256_GCM,data:5DuSdb7n8Pne2DgSgv3onKXxNqq676ettCcJuSc71lYVR1ndeDM=,iv:umrOOmEpsjWWH0U7Ai5mc5mnj2ZUKxcWpEIi/IC7/yI=,tag:duvs3pM/0dKeMhGRRhmOMQ==,type:comment]
#ENC[AES256_GCM,data:pmw12KABTPYNNdiP7gcWsn4=,iv:Q80v3VjwKNV89OA3nKBl9gYl4hju5eN1NioRxOWDUFo=,tag:BWLDxf08LzWc6sfUolsEyQ==,type:comment]
#ENC[AES256_GCM,data:0cXQSC+wcOaRuGsLs9qpLxZCi3HEZ8gu,iv:HPp2g1vDrw4nlrZMvzBuhG0QmsGPWAYNtmb0Y1aLzBY=,tag:LKCCLwK/BfFX4LbrU9kczA==,type:comment]
#ENC[AES256_GCM,data:mDSthVbOliz46iz23q3C8t4TLu8GGyPfVr3/1CE7CLENgcPUzWSvurlsnANYaw4d,iv:z+ENyJVE/Z9dHTCUxHZX3RAVobCMqmYUTP7do10815s=,tag:A67Gpj6x8KFhDBiDIbiHxA==,type:comment]
replicas:
    - ENC[AES256_GCM,data:lYkMjNzEv+sjciIm8IhuJZczwrEu6/I+gsB3Kw==,iv:KNNpWKjPWZhqeO6ZixotylXTw7gdR6w6ljAo3NGouC4=,tag:hqA99lGGWHwj6kFQsMIXaw==,type:comment]
    - ENC[AES256_GCM,data:c3O9q+KBiSdS4t2SSd+WtCWxmh3JH34aXdiUwnY46TRE5R+D+PegVXe0,iv:hnrwse5iODCRsI36yOBn4mx6rRjekYfNdvd44qXZfAM=,tag:t6UzGe7HddVY+Bhkxz6ptw==,type:comment]
    - ENC[AES256_GCM,data:bpRFWhDcPRgp1QYID2g5JSwNu37h,iv:ctCgutTyrfz3MPkeRv4kPDFEDPtw4trB1W/Ms2kU48Q=,tag:j6IyVWvYNIYu53p0FhkFvA==,type:comment]
    - ENC[AES256_GCM,data:ZgdlT/SaQjRDAsCOGo/GMYCUgfAGrEotQwn0yw==,iv:SsFqbr3eqE8nHy+WJm2GWU8DG6FByLngpVuZnS78fRo=,tag:6VcyFzhE19KqrjFzEjqQWA==,type:comment]
    - url: ENC[AES256_GCM,data:APq0dx64Z5RMavokEm73ytwGNr/ll2ufSgjNOOJwpw==,iv:VHXlXGO6NM7kbW6Z09YwR26BkNfW9R+DVVyqjxJnwOA=,tag:eYK6PKyAXxSSmGrbTiY1sQ==,type:str]
      username: ENC[AES256_GCM,data:K9Zs7zw=,iv:AbG69PXvQw+XiOcp6I6tiLvnDI0zk3pzXZYaqZaPxKE=,tag:4HgUd0GFK2EP0vQalAV0Aw==,type:str]
      password: ENC[AES256_GCM,data:7I0Er0DjWHCsUGa0,iv:hHacFIRHY41rLfIcoLvAFuK3BZiq1UoJ8XPeEQTlgL8=,tag:ih2NEBFMlr9Yk5hb9vd/7w==,type:str]
      #ENC[AES256_GCM,data:Kb/Rgfk2bV93FlySmT0hFuwWlG1GOpWveVDnNDhis9t0u9PuBWlo4yENugJtx0McdBlgoMZAR6lCrk2CI0dovSwelmXO,iv:FQevegzQ0Rexz4C+zxTEmXq1OF4wYhuLlcYKSSDPK7A=,tag:W5aXXT0E+uKrGDzYXTzl9A==,type:comment]
#ENC[AES256_GCM,data:ktrFSTUgzE5ryWMaFT2miqPNBnDuP8bdXSKOuDCNZsYk1f17Xg3NiQedHGR8byEj1+I9uwCCfxJ1,iv:EK9vOnJunHGsTlFZQf6vBlTjrWYImOKS3Ym4O2cnXM8=,tag:GGT4xUGhFnVIGuBFM0f4lg==,type:comment]
api:
    #ENC[AES256_GCM,data:d2gSU7N6mvi+Mtbwt+95TnkQNQ==,iv:LsjjvUUVgYInpYtN1l/DzXOGpf/A4VbkZEdCz/mBGWk=,tag:FoQXvY5erLfte9zWI7BPnw==,type:comment]
    port: ENC[AES256_GCM,data:mylMqA==,iv:/tLIFT59VZsiHAu+3AAE8+HQ6kU3nuWh9QQsPkjlNtA=,tag:tersNxHLRNERKh+LONcDxQ==,type:int]
    #ENC[AES256_GCM,data:OlZUesIM5YVapl9X25KZN3qHxr40UFzKU4yM2Q7uIktWlqh6p8DPJ62WrDDwju4lTW7h6WLxY43LpwGW8l88TYUAz8NV036vr3Ypxw==,iv:bs7CWC6ERQF41cQjJJDv30aqIBjw6t0cxjCI691AjGw=,tag:xK0E3R88FbfQtKvNncPZwg==,type:comment]
    #ENC[AES256_GCM,data:Gt1kW4Sc++S8xHdzGGBXFtrBGQ==,iv:yXTlhQROu4W0WVFQ132eCmTSXmr4938XiMdAfsHf3sY=,tag:YOZRmFXtrnq6wLYw4xhNpA==,type:comment]
    #ENC[AES256_GCM,data:F661RPCLQ7uw2Bs9CI0TjRHYJQ==,iv:qRbajWTEJLskPKNzMD01qk2m8BxiyWHv5vnvcOWgjF8=,tag:5rW+P4elv7f99jknduKOeg==,type:comment]
#ENC[AES256_GCM,data:7/agGBLlPe6YFKgzKIJwrR/QQim95JeF8G+i2Gr3dyChRZ+/NVPEI2FYlCiBKyjfM6TFmdTVf+lieNNtWT8=,iv:jcJJNAU+YMr9Q2JfQN08nuhohYU0/5x++xgU9GcYSU0=,tag:X3uzeI7AlRivpXHib7lwMA==,type:comment]
features:
    generalSettings: ENC[AES256_GCM,data:TCOBWA==,iv:9bzTU/LsYyBaISyDd0ZcQEHju+ier8JLuPblaTcZz6I=,tag:sIP6xDO+jwAYsMf5Ofuk+w==,type:bool]
    queryLogConfig: ENC[AES256_GCM,data:t6wtzg==,iv:0WDTH3ZslzLi20wW5TgEoQf5ZDsb8VOr9f4jvP5VhMY=,tag:sIsYVVCABE9OUdvqyVPj8Q==,type:bool]
    statsConfig: ENC[AES256_GCM,data:KsJuwg==,iv:hAyYsiputj7QXXEbaMZolGtjuZmxXbz/SbbC2YC4sJg=,tag:0CH5rvGHtzWLGDOeBiblcw==,type:bool]
    clientSettings: ENC[AES256_GCM,data:IxdOEQ==,iv:DzTPSnJ/zqG7k+9dHxKlT7UoslbZYhWdQec1ShjM7wM=,tag:XdOqQAMYL9rMMHbYs7rkig==,type:bool]
    services: ENC[AES256_GCM,data:2bl93A==,iv:pVkmqvCZI4vNmnu/muMjYF587bS8/8P5+0xy5hSS0ew=,tag:Cez7V65UPEId6enIbi/KwQ==,type:bool]
    filters: ENC[AES256_GCM,data:/5XEQA==,iv:mH8BtKaIXW05eg/DSaq5E22XtwOdAGq1EA5WUJfijSU=,tag:DwYhjmDdRZVKwv1oM38/NA==,type:bool]
    dhcp:
        serverConfig: ENC[AES256_GCM,data:PE7hFyY=,iv:xC5QdWaW24EwJeaAcqVxIRVEk8Kfu7EmGGwoPvP7hko=,tag:16nq0r7h0lfpY5haZiMT4Q==,type:bool]
        staticLeases: ENC[AES256_GCM,data:RU2nVeo=,iv:whY5yCFjyxRcWFeruI5qGOVADF8C9ttZllZzOAvPM1M=,tag:8BMAhT65ak8P5USCgK9WBQ==,type:bool]
    dns:
        serverConfig: ENC[AES256_GCM,data:Jd8GlA==,iv:e3C8s+SalDS3n2xRMvfBJWKsgjuGMLLiSocgxwTj+Wc=,tag:x7/+xZOHivNjIecrb4NB2A==,type:bool]
        accessLists: ENC[AES256_GCM,data:eEZgRA==,iv:dCZBgLDQlZuIV7v0lEA8zT5rC8JSBYGrnlF9SFeAgvs=,tag:EjWJzrdzlt1QV5FPlhYZFg==,type:bool]
        rewrites: ENC[AES256_GCM,data:a7BJiw==,iv:LyZ+Kt97iCLZXMu5A4fwYiOe8ZcRdh6ibknCDJ8rWks=,tag:noMMyV3oBaR2xR04VAlmtw==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWXZ4QS9OOUlzY3U0WHRa
            ZHk1cEdvdGJ3MHZsQlY3K3UwaTdpOHpRS2d3CktxWVo1eHdEMlZQZFc2M1BiWTFR
            RW8vei9NSWp5eDkxZ25hKzhGd2pVcTAKLS0tIElCb0l3NUZCOU1HZGRxblg2M3Vy
            aVY1Ym1xQXNjUks4N1lTYXpUd1BxSVkK53VY8u4C8+Lvm/e3s+FEtut1vTa+gwjQ
            alFh1wygh5a171n7VCHpeRTlP9GGWLXgHBULdN7CH8yzG5hE0flXVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-01T16:29:18Z"
    mac: ENC[AES256_GCM,data:rPHrSsGPTYXQYLXGH8hsMBbUXO0Gqg3KLQSwAQ5BpFBksGF4CVuitBgwbst94NmKOvTkkxW+TJjmHi1H1vl/TxTinAub+Cl0W4cwl7nka+4f81SSHGQ1Lz1vkmCe2MfXDCVYk4diZirHTaTvoHzTYf6g0h83hSNGcZhR1HGCm5Q=,iv:GnxOYwAHT/nkPgCapp1u18YA0RVYFlGk6G0ILKxIHZ8=,tag:Qw34qCvqO/NN4tb7Obbh4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
