#ENC[AES256_GCM,data:8VUtbhamK5/xGBt4p+c7XEpgAWcCP9HBuRLdYkzl+9gstngAYvbvLAJEFsNu0jcE18jCFV9mOX31S3UlqDztxrQiB6ypEA==,iv:VOborvlzVjUxCtwFBWgSoRs9jSS4iMAuJ/uVQb+vS3o=,tag:9X+r251IaBO6rA9g4YcadQ==,type:comment]
cron: ENC[AES256_GCM,data:GTUeMUp/ETTL1l8h,iv:GZE7+jUm9BqsdPAb1NQ1Kv6aNKr3lEj4g7DsjsJ28/A=,tag:hYp1UeSPMAXem9sJpFBE5g==,type:str]
#ENC[AES256_GCM,data:Mu5acppD7DR3sqCpjXpY0xtpv8WDgbw/gcjIWndTHGvj94aN,iv:sptb70WiP6y/tdyWSknnW7Mj9oYAGxQN/d9zS9pGZzA=,tag:7jP3Kn3yrhLvuABdhU7Jvw==,type:comment]
runOnStart: ENC[AES256_GCM,data:FB0qVA==,iv:O81+RKGX9UTdgMkFhN/wWXJnHJZ8uTKb+8prKB9lTTM=,tag:bvFhHl+waWnd8yBDBuV3/w==,type:bool]
origin:
    #ENC[AES256_GCM,data:CyaYBoVUAZZPGrma6bCU7QjwVijkEuqNS9Bg,iv:+uqtmk4VvcA1uzeVm/yaCoV+gEH560xuyqJTVYvFLcc=,tag:zkq1NkUcITP8kooEdkqvOA==,type:comment]
    url: ENC[AES256_GCM,data:kY2DKQFlpkyWkkk1gBhvISj0vAZJ,iv:fZXEga5cD6Yh9O8AuhEIDL6dLoXFVCaEQxpAS6ZLhD0=,tag:E00ZwQxXu1MV9spFQN3IQw==,type:str]
    #ENC[AES256_GCM,data:+rxsq68HXOoDIrFrqXpQjZ0LH4vTyTbd0RrRPOjNAY2FXQetDoMmn0xlYBu+kl1YqRDsVGw=,iv:lYsUcCBLCjbCg5XIU1+H2DqM2R4m/9mCt+pdgIc1/CM=,tag:9CRJgZjcnZ8PwILgDeLHIQ==,type:comment]
    #ENC[AES256_GCM,data:VHEfr6IqH//F0yvliik9vs1lGCKedTnN3Vd/oOxoNSviD0+B/BB4bZZn1hma,iv:k3fMiOivE1BkkYn49MDcg2Jjk+zRJySSHkd+kPEALmo=,tag:SvqZmAT4zjG9YBDVQekRkw==,type:comment]
    username: ENC[AES256_GCM,data:9R6waFOWtg==,iv:2riguBdLmegE9CB8ahudPMYDOLbMGakpdDYhOP+aRmM=,tag:LtmXmiR3A1MVUFoW4A0+hw==,type:str]
    password: ENC[AES256_GCM,data:jPpARpxJfmWwMch7bH9BYq0=,iv:yOCF09s4sv/A/l59dNQu8EKMpA29KqwAgxM2fMlZOxw=,tag:h3P46nyZgo/MGdQ8bOUY9g==,type:str]
#ENC[AES256_GCM,data:E2g6nybH0WsSZpb2aKeo7KJvahYIaCwt7dyvCmFAfN8vPSZC9pVFNw==,iv:stsdiZLPT2NTcFdECGiyaI3SidPbqRn87XqTPCCKdws=,tag:9F7VV9LJdlRRVllBbRWKBw==,type:comment]
#ENC[AES256_GCM,data:/SN2tIpgPUBW,iv:56ZFgM5dnXGSBWvUc2gFmxfgaFUY2KKCjWmHX37awBQ=,tag:9XCEQy+zEqclseAG2WlmYg==,type:comment]
#ENC[AES256_GCM,data:Ddg7vrBa740NkhFG4Dp284XwmzIB7LHsyGoARQ==,iv:mXdrgElORSqdE13RZgDyqgECUSqXLICXnGYB9i953WQ=,tag:J7qjZV6PNOceGuyo4/bl0g==,type:comment]
#ENC[AES256_GCM,data:Ex8SJK8+B3/9dMk/dXWnR+Pm7LdHbHY+2dMTM4+ZEFduieh5o5Y=,iv:sg745LFgvlkAO4cLEfiX9yubB0pj6m83qMwhv9RxObs=,tag:V5Nei6tiFbSdVDUYkNgOBg==,type:comment]
#ENC[AES256_GCM,data:HT8LTA8lzZE5B+9xtkXGb94=,iv:2BWLd5JdiZtv2XpRkZGtcKOm/1UPdLOZ+EyH+vUa0WQ=,tag:MrC+s/oG17RG1Fv5j2TY1w==,type:comment]
#ENC[AES256_GCM,data:KUlluqu2xFadxpmKID3/1EU1CYyg1SWX,iv:R6Vzx/JPFg2foY5nv1p/PrL5jLB0HdOb8o8SiPUpN28=,tag:lsTBagdgKA9hBywTBp6EDQ==,type:comment]
#ENC[AES256_GCM,data:CDTd+9qUCFhKCptOpfZC/OIHsHUpX2HJGP27FnwyAbhS63ekOZ/PmwINkY3upaBA,iv:yql8wR3hX0ooFJWEkRryUYfPsuoniUyMxHqCv8QYics=,tag:GfCVCNzBR4Jud9ceLjebqw==,type:comment]
replicas:
    - ENC[AES256_GCM,data:GNpXehTLIEskSN+lLdEAYg6LEecQ3TVl+6c1jg==,iv:XWk0uuQ9i4OjFvaEnoVPWaKfS5LjJ500FaNt2P4EOQA=,tag:mXkAhlYH9QryNhWvI2mJeQ==,type:comment]
    - ENC[AES256_GCM,data:tMn4eMe7iObeAfys4Ob56u3kcnpgWaQz3reJwMyod62FrctBmUv1vFg8,iv:MuSnq81oN95vXQAvKv7e9tJdaMJ+CPjONgLkK+nba9o=,tag:uu+hB/IpTaGVvlFWR5AuLQ==,type:comment]
    - ENC[AES256_GCM,data:CkLinRT6vQP1SuwCxRV3zsyQWrNO,iv:Mml8QtGeNWy8hJygf9sUnLsmZhSCCw2ZSCFpqE5UZo4=,tag:8+U/dvNdMqI+XA/frc9V8Q==,type:comment]
    - ENC[AES256_GCM,data:o/9iPbj6G1nP7C6h/2JZfbqZZ1Kk8bSllV+mag==,iv:bv1Jdi9rsffa2ELNcMS112NFxDxrh26NoNqRIAt/Uf4=,tag:mPF7btF/QEoJUCRa4Cfr8w==,type:comment]
    - url: ENC[AES256_GCM,data:hqxh7GkOGIuPhyDgNefFzO+gHbJT,iv:g+TvUv5vVdxrGtmv4Il+k0yZMSzM/ldSKIUZN5XMJ74=,tag:qYUhO4Mrcu7KVSOt1ztXeQ==,type:str]
      username: ENC[AES256_GCM,data:UNpdw/4jmQ==,iv:TeJODlpLB5fN7oqtkL9AgqmD802/Sbj40MpjKQKitLc=,tag:CcRa8rq7Aag4NkPikix0Gw==,type:str]
      password: ENC[AES256_GCM,data:fOegJb4QIMfFi0d0pnQs4Mk=,iv:HkyL5SE6apUc+ZiDeKa15GIOfe+7PX29H5zVhsfgpw4=,tag:n4KRjkz8d46+rmznqdKmKw==,type:str]
      #ENC[AES256_GCM,data:Ah+LfFqvRd/5g+cLJkf4GPJ+GhwX8g1on/DtSgIIFGYe9yFHr2Ii1B56MLL8FRuOK/seUP/ecFzn1zwzYXD/l1EdNnxV,iv:3JQlH0ZOaM488Vg4CZdnJusVbOlEkIttf9oI5Gt3/Ss=,tag:Da8QeEgmFVUvBjyUqF+lkw==,type:comment]
#ENC[AES256_GCM,data:uLW1Ut3h6gnl21B6HEejVwYDzuNHrhE5e75XL3VO8TvKh59An0ZEE4t0ZOGaLxO0m+i9/IRpTz35,iv:D5nBviqOCVSP+/Vmz13PhtOJ0tBQeR6wGhzOD/kCRBM=,tag:WjcX92T8++pAgNj4d6fnyw==,type:comment]
api:
    #ENC[AES256_GCM,data:Hnk7tjNqhYG1ODXinfpDYYf/LQ==,iv:3k2QY+psMh+cO7BpgtyQBee64zXQTE2jjPRRZt4jREo=,tag:OuWbYaDtdgydLsCEQ2KfCg==,type:comment]
    port: ENC[AES256_GCM,data:B+oKrg==,iv:xLlpSnQ5BUZVSmjyGohjc+/HLjbPKCbnf6CVeNKdLZI=,tag:PVlLNg8N9nc4agMwZOaBPw==,type:int]
    #ENC[AES256_GCM,data:Ivv5SiGaSyyQjfuUmXQWplCZRTI/gx7Nlu+CWsmZ7j2N6+DN276+gdBl82S/n3kjObuJptvXloj2darlS6fee5R1Q2Swz9QSidDjfQ==,iv:VEzVlo5b7of5Nt0jaqrDWO+htujbiw2kA80HVjC3rMw=,tag:LaR656wU4HVJZax7sUqXoQ==,type:comment]
    #ENC[AES256_GCM,data:sOqzOpHI6mPL+v0yQ2uWmTD1pg==,iv:AS0ISKiE2I5Ah/DLUCvE2+1OWwDcQ7p5g0fxQljZfAE=,tag:YxDLsSq+VSrXP+sMbaywqA==,type:comment]
    #ENC[AES256_GCM,data:Cj+LuRpQuu2LUyLE71e5F8ltLQ==,iv:ODl+TnMZjD9wJ9jdj/p2Ex6FWgXaubhHNkhFUzuOIGo=,tag:bOQzBkhzyji0J1W5Yrjbmw==,type:comment]
#ENC[AES256_GCM,data:JLbH0aoDFhi1Z4/sI20uvDPZRjDzJccyxsVW4/cPgcCB8I+vNqUbeOI1I9fgwqrUa37YHMIbDo9iCrh7M/g=,iv:1Dm0EqgKjvC6ePeKFJFf5mY03cJBH5F1qT+ztmIyicU=,tag:e+m5r/XNF0VAoqv25oprQQ==,type:comment]
features:
    generalSettings: ENC[AES256_GCM,data:h476bQ==,iv:lBAm9DJ8wp5QKp1qdbcmMIaYkwdahrxG6l8ZoPvklhg=,tag:B5IxR0jMYtLA9JOBq1i+bQ==,type:bool]
    queryLogConfig: ENC[AES256_GCM,data:3DQntQ==,iv:AkLWJPreAt1TR4xqXkFotDQoPNtzTMCAHrBUMuzFA/s=,tag:XbkG+aGYZk07hAT7nfow9A==,type:bool]
    statsConfig: ENC[AES256_GCM,data:LCemxw==,iv:TS8URldeClFIoAHyCHBV9VETqR7DBnVYWgE5RIw/y+4=,tag:eF6UINCLySp2+XQBi4YOoQ==,type:bool]
    clientSettings: ENC[AES256_GCM,data:BXaarA==,iv:HVu2Jd1Jy2GBacVpTYRP8hRfL4B8s82t6RqrMpgRqO8=,tag:S7v2xTmTY/LFXoPsKPs5Pg==,type:bool]
    services: ENC[AES256_GCM,data:me/Bpg==,iv:cY++RDSgAqgf3zjWthJzvsib4OOnFEKQma8lmIiszy4=,tag:/QONfpfR2cGcL21O22cJ2g==,type:bool]
    filters: ENC[AES256_GCM,data:l9ejAg==,iv:6wS2s304AHBdOkDpFUKw7VfHSzGMuV/1SK+v3wdZ+Kg=,tag:+elIsJvGwze987jDVdqH3A==,type:bool]
    dhcp:
        serverConfig: ENC[AES256_GCM,data:IKyrry4=,iv:DrqJv/VkSm91Zga2OCg+F8DgS4UqIUcELSD0LpDeqz0=,tag:Ky0dQTT9ZSeAEfsLs0Xchw==,type:bool]
        staticLeases: ENC[AES256_GCM,data:kPa38pQ=,iv:QNhMtH++XwiUvp0Gipwk6uUFBJwKF7FlD193obdJHoc=,tag:s4u1I/iWUH7pdRsyt7MA6Q==,type:bool]
    dns:
        serverConfig: ENC[AES256_GCM,data:lZVBKw==,iv:HfPrWmK1JHfu9Ir0zF9LoOBQFOMdyQidlSZyl0wMDb0=,tag:yL4fGT+GiSJPyFf8DWDtUA==,type:bool]
        accessLists: ENC[AES256_GCM,data:sFCoZw==,iv:lT04HvrJBQr7QCZ/ybpf0xyS5KboXaCpJYpr1qzNjPw=,tag:mHxbO+1EV0BTOsS2HGorNQ==,type:bool]
        rewrites: ENC[AES256_GCM,data:hjWB7g==,iv:48j+GwqKpv5U8pFGnGtXSZDMjdmL0BP2bC5mGQ6ztB0=,tag:VFXFCO6EzF3XO0DXFBoqYw==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bVlxb2paS1NHN1Z1Q3Z1
            VnBMbjAzWDZKa2Zvdmg1K200dnk1d0lFMmk4CmZ6T2Ryb2ZRUE1pdFdSY3pLZENL
            VU51NXRRRkQ5WUtuNW1meWtlUzcwWk0KLS0tIEJHK0s0QVRYNHhhSHB1VVpOdzRN
            ejF1QUdoeVNhamh3dTRYM2p3L1M1Q3cKzR4FASl0M76gmGt1csbOB+sUBCOIUGxR
            o5sSF3dGRUsO/OzJXshNw3FubzZ9gZMUnD2WTV+0NcvFGt8Vi79JvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T22:12:44Z"
    mac: ENC[AES256_GCM,data:2Ux/LEMoYZeprYrJ3mIoFn1FUCA2XQkjOSwQMhEjOk1mufA1Ms7fR0chIEQ3uvH7qL3kgj/3XN/ws9K+3mtd0M9Mm0VfKUzOxPrWr5/cpX3toOzCwLb0KUzKVK3OMz0TZxqz3lh6B7jfGUuswSth//0p1Abrpof3kIM9fMhSHfY=,iv:x17dSwBUBGVQbC7yes3pqlGrlbWnSKlZzoBIpYdyEJQ=,tag:+EZdj3Id3whk/uJg4sfgEg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
