#ENC[AES256_GCM,data:IVJ3E+E55YHCEUXXQfokpK9RrlXKgdLN+OSxv8adqnM085mu4Ph5lJN8YMVTGBn/IAD+mQvbHLA84gnOM8iY66u7K668Sw==,iv:ZKfD4tCcDrXXMZZ6LllhGirAv7Y6DhlHvLJYt+l7dZQ=,tag:8cnQygjMPmW2CF4qx9d1zw==,type:comment]
cron: ENC[AES256_GCM,data:7B62ppcL9AvdpcpB,iv:o1ncKc8pdajWe4x757Qsb4wKfM3D8g/ekvjkj47y0aY=,tag:OLfF1RD4kD/Sbs8lMEIbUg==,type:str]
#ENC[AES256_GCM,data:K5hrLGc2x7yfNIOb6zOguNZncFoLHdJtHxgwKwFcOjEb6YXn,iv:ritqtCl9K78U0QncthE3OEw2M7Cw36bHpH5ONg+WG1I=,tag:udB95yE+zOHcaJiTF1HUBQ==,type:comment]
runOnStart: ENC[AES256_GCM,data:49WJJg==,iv:ifJKf0KvtscHYriMkllYA+pKoPgdsuGvIwF1FYmWVQM=,tag:Cq+p99i3wCqR5WHAdQ3Q9Q==,type:bool]
origin:
    #ENC[AES256_GCM,data:jQsfCAwtsTAvhqaVsaA6B3UydPmbxEYBK8V5,iv:nwz3ubENY3gMMtgbKEStuq5Jn3fI0M9uDpqWi8u1FDk=,tag:v3BYevNqkxvlj4ds93vF6A==,type:comment]
    url: ENC[AES256_GCM,data:CewDQDYsFmWC8er89IF+YSxQwsi0,iv:u03u9+tFM+53goWMKHoCr9L4uC45uE/ueSuaEuAW6Gw=,tag:EsxjTjy+01X/5YEneqKPkA==,type:str]
    #ENC[AES256_GCM,data:bAlpMNuXmjmoodAgY7D3VrTJFpJUwVBsVWFM2mPUxpECkh3CELNXsKFd4ciDLyM2GQKr5Lk=,iv:Oh89qCw4swi3vKRfBks3JQWrk2bIdS9NjmZnJI/4x8w=,tag:nGNaaZxUeUzuqKw4Jzdz4g==,type:comment]
    #ENC[AES256_GCM,data:EGY0jHWhV6UJxR758CQNS/VcmOCPPxnCYtTyEiRLuuIIFunG/vbAyHvA15i/,iv:qonZcM53tpcnSwNBYHl7dewmqvTWbr8nrT8ej+p7PNo=,tag:EmeDPQc3dZ5IRCd7vbMhww==,type:comment]
    username: ENC[AES256_GCM,data:v01K6OtM4w==,iv:keM6ywu/nOfKo8XxCI6HJofdXM3kW0Z0FwlRdSzlx8U=,tag:fl3D0kaZSn7rC1O7Kqi4Hw==,type:str]
    password: ENC[AES256_GCM,data:ipUVhYN66xYJ8ZlRsRPsE+A=,iv:4V1D90b7ccDU/6X8vjc3+4B8ZGHelVYE9M/4n4MKXlQ=,tag:yiH6i8DmRoe8GHOjLL0NtQ==,type:str]
#ENC[AES256_GCM,data:m/Qt0q8hFTCK5plgPJ4vKECn9CFHYTYIYoVw4xLkITi35Fa4unMhpA==,iv:SpKuADsnaeTukSoazxVolT+0qvFsyieTm/PcwMDQxkg=,tag:8eitakikUHYz8fD8O+uAWA==,type:comment]
#ENC[AES256_GCM,data:9OWs+YnQOWze,iv:gubAyx/NlhhUegWbf6XiNr3W8ZrDLx4Vc1kU34wdwco=,tag:FcwptvKl7aeS0ttvznt75A==,type:comment]
#ENC[AES256_GCM,data:wTQBGmTm8FLYJh3SFZqp2HUnMxqzEv+U0R211Q==,iv:pDW5oeXje67K0OcJhoKM6AL2+CK6a+z1l+ixNJXO7FA=,tag:HFRbsDxU5mdnyCkFB/9sZw==,type:comment]
#ENC[AES256_GCM,data:uUdYEgzIpMNzW4FYtqHy5D7m2KiPzKRERKh20XQrlwpbDaC4zNA=,iv:zNPH8cYat+6UQqTkhRaGgJWi8XqT/hT4F53hsTBzfVg=,tag:4UGHLgmuPPaCp6oLXVCJUw==,type:comment]
#ENC[AES256_GCM,data:rZUISrwN9C0sjC6sls2oBbs=,iv:hjDKxP4lPm9CkpcfUS7foQSWUiRyadskbn+pFHSju4Y=,tag:si50cB1INJCbcPpf11g/Mg==,type:comment]
#ENC[AES256_GCM,data:Wq15uznHBcjGdA/GyKjtYHqgyzd0Q49a,iv:HBkmpRqOqJQjv/h5z4XwUCefBP5xhZY3gYZdi8AU/Ro=,tag:7446VNNm7Xh6wq/vP6dzCw==,type:comment]
#ENC[AES256_GCM,data:L85kvg7Zrloi70bodmpqsVIvJyuh+B8l87YAGJsSqPU0QffxtFDrxRZfoVJhQu+V,iv:XGWllvy4FP/JFqkkqiZh8tL5hiJBKcmvROqXGQvHiWQ=,tag:kOAVPlPo1yyOtTWF1fv+Sg==,type:comment]
replicas:
    - ENC[AES256_GCM,data:C8Z3m3++YS/8p6Tv+GQAsjQz0TgRnpdrYhkQMQ==,iv:xWpsvH4+lrZfr4ZuOPbBtCbLaVuje0L60pKmlaxGNwY=,tag:IPLVgzfU7zPFgu549ngyRw==,type:comment]
    - ENC[AES256_GCM,data:qEv1HSyZufhQN32JOtmakrTojKUNPDO7c14XdZ2C1fSnjP2Y3M0mPpC/,iv:wfWNidXn82v34o2GofcziYqSLB6X7oF+1z58w04K29E=,tag:oRw30VwLZ3K9pR2EHiVaMA==,type:comment]
    - ENC[AES256_GCM,data:xcnLKTHlB11aB1bDtUNZ/1RSNpW1,iv:jNU/neSND3BCsadgz6Zy8Ipl+hNJ2vRUB0aBJUMJM10=,tag:fJRRyPyGmeaMwJ8IUFVKlw==,type:comment]
    - ENC[AES256_GCM,data:VE74jg51YmJcyi6r1Wh8Q/B4hOV0YbS3ti42pw==,iv:BAlILXBgtEN+HV5r961WRykXcQIW+ge0yZw1mNHn4vs=,tag:6IiLlAv3JTCh0B87BP/3Iw==,type:comment]
    - url: ENC[AES256_GCM,data:ovRbjzU0JCAUK05sB01iAzTjTdSi,iv:HtFW1pG7lm6+kNmtJh4TE5rAd6yaAoUFy0iUEARYqnE=,tag:AGclROrMh3xe8OOJAJcT5A==,type:str]
      username: ENC[AES256_GCM,data:UcG4jSqMWA==,iv:FvRcxd1rXQn+I6IFlkc4nkJ3l+bJLTwPfavChRbgtKk=,tag:NUI/awdX/GplHAu6X4kKFA==,type:str]
      password: ENC[AES256_GCM,data:Wmdoy3yNA/rh8RNXoFl8Y4I=,iv:DHK9Oe+5SlYZcmpErc6SjLN7cy/HFQxyE8k1G5ZAFEM=,tag:nTVZfJTex5JbaP1VJcqt7Q==,type:str]
      #ENC[AES256_GCM,data:SSrF75Sjrv3oAUbEO+DE7WOO33O6Fa+tW/9NTgezq6/Sruv07h9IrlPJ4ZKlZDC2qTaL2L9vLAZC1V9RWpYt34MyMD6B,iv:oXiLUmifPJHMu75BKRPFXYM9maY0w8yEB/iG97/h+9M=,tag:MUEKybsAbmaQGyEoAoZoBA==,type:comment]
#ENC[AES256_GCM,data:st1SFtufCivjR9MAi0kpyOjFUYhahIjxgOeEJxzLB6Ggu+8IjlCmfneEOSHcfn5uEF4QvR4eRkLe,iv:uPKS9reIEJAPsP4VevLyLAJY/2gcuwFQSZrO3T3qLAY=,tag:dm7MnBOEI8wsqopZcw7/lA==,type:comment]
api:
    #ENC[AES256_GCM,data:yftMTrhqlOQm4dGzmpk1xiDuMw==,iv:ALoitN1hTOrQbweimkQPJXPzMhQJWeMVmEdFJg1aRuI=,tag:3sgTmJZ5KAnnQAIFFGItng==,type:comment]
    port: ENC[AES256_GCM,data:qDzfZg==,iv:TveViMUdk5eBmacsr7leo9WjkSw4Vj4VCGDHJ9ZqcHs=,tag:trhJWF0hcwfDjWXZwexjDw==,type:int]
    #ENC[AES256_GCM,data:i2/VC/UYAw8gomd4Mdzs8yo1Iomwjg1thJODMTQX85gNmbqxpvY6lH9URwOK/+oHHEn6MZx0k3083HH01YII30W52BFpPnlu2XSgtA==,iv:tddyzSr99MqZzfGuuImyWqr/NtjVywkS/K2qfC3eUaA=,tag:Yy6Nkyuua/m1S+doyMseyw==,type:comment]
    #ENC[AES256_GCM,data:wNWBUp9TZ+8SHb8fjKZUonfTMA==,iv:GJCUKQEE2qdfzFW5W63OTB9poDnEF3d2K4U/nhlNSaE=,tag:tq/hkb9+EBDhFHX/2kePKg==,type:comment]
    #ENC[AES256_GCM,data:b8Td5gHbc8aKwO3uQaGZdT2uyg==,iv:0SO/wPelcbbe8w1YhR1Smt8ScgNVzrUZbndks4SXZLY=,tag:1yFgsMrBKYYDQpt8KvsPVw==,type:comment]
#ENC[AES256_GCM,data:o7pZjaXYxPTnXm4VCvKWdZhGqVHWjCEi6ygqRzjNCTI6Tmwvn1WlR+GZiqiOEcjugEVd09i/qvaV6ra+8GY=,iv:M/42sUVcewDWXkPsRfeio4Fwd78geL8/iT5O+DQPzKI=,tag:s8E8SVbZhXQ/eJ4DcQuQPA==,type:comment]
features:
    generalSettings: ENC[AES256_GCM,data:3490Cg==,iv:0A+dwgHIfzfMwV3euQExQduEnb+Un/BR+pBOwEk/fX4=,tag:loll+nX5cLuXE9k0dG5uOQ==,type:bool]
    queryLogConfig: ENC[AES256_GCM,data:BvdpKw==,iv:S0xhRhPH6NVViWKyGS9vzxS1I37j0tug0r6eA3ufCs8=,tag:8S0WV2ZojJL4EdspEFo6lw==,type:bool]
    statsConfig: ENC[AES256_GCM,data:y3Skuw==,iv:0O3AEH0wC1eZrIjECipWrGC63g87nqluYBrYpba/JDk=,tag:OTv9uDmOIVeOdoLVAtXCYg==,type:bool]
    clientSettings: ENC[AES256_GCM,data:Y+uhYQ==,iv:9AuiIXeywAva55eXkUwJVyfaDBDBqfxkoAdR5vx0bBc=,tag:8+d6Xj83KMtp+USvWgaibg==,type:bool]
    services: ENC[AES256_GCM,data:SKAesQ==,iv:gnTXUk3nLkDgZT6Nccnaa9pFGAw1q4nWtQgpWDlNra8=,tag:sH4hNGukpYLZ3/O9wIJMkQ==,type:bool]
    filters: ENC[AES256_GCM,data:i6/6+w==,iv:1oxW3pjjES7iFGr96IqKGSQTYv7mONtaxnnagJY8dKw=,tag:rTy1ckM3Zd8RSV2sq43qWg==,type:bool]
    dhcp:
        serverConfig: ENC[AES256_GCM,data:JXEaKSA=,iv:TqwFSHm2M7Z4cwDd8QCiven5633qX3QV6XBwe2WQJvo=,tag:8Jz4JX36b3zkLyWGo3Acaw==,type:bool]
        staticLeases: ENC[AES256_GCM,data:KuuUkOE=,iv:Y1x3As6Tl/iYYn2q5gX0itxDLPwXQ3UKnojeOJ1J8UM=,tag:68sHxZtGqsjhaFe5GI3XZw==,type:bool]
    dns:
        serverConfig: ENC[AES256_GCM,data:KbVDvw==,iv:ofpy6bE1d8QPe75skUGDN9Mnx2WwzrKLPZOEjt6/iL0=,tag:Xu1x9mmft1fI9YvosIbdUw==,type:bool]
        accessLists: ENC[AES256_GCM,data:U4YFKg==,iv:jPd203hd/bUf/oSfdD3Le0pohsCnsYDZx+g5hhpwmN8=,tag:Y8v5MDYGsiVPe35I2bXghQ==,type:bool]
        rewrites: ENC[AES256_GCM,data:WAchRw==,iv:DnPdGkuqWe9klrEV8vvSBBIOWii8crd6jnHdLFk1FJs=,tag:wduJuxnt2aHakdtFgQqcBw==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Wk40bkhYSWtzRU5vNW15
            bVd6aGt0aTRiRHNMWkx0NE82M3g2Nmg0d2pRCldzcVljaVRpazdaQ1BxZzJOMllj
            eHd5Z3dVQlBwRjg2QnNOYVI3TEpMMWsKLS0tIDVQVlJBNXZmU0VRSUdwdURVYmor
            UGZFTzc1aW9GWW9rQkI5UzliaWIwNU0KO6/M7A8jzM08MDn7Yn/ktLWm5glZz6Ow
            D7A/1he9uqN4CaKwo3LoRph6fhwAxEzIhMoxhccKPu5WvIsIt71BXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T22:49:19Z"
    mac: ENC[AES256_GCM,data:AzQs43o65AtmUqw19AG9m4fa1IbFI3OurnTHwIsUUoUoXNS5Tl/h04jcT14lxzstSfdgPIsLdrORjrdRI+Xm46zoSUxy23PyCCuwpQ/0LmgZs1hQzZzMVWv5mAuEQ8LXpMLE6mDamEPldi3k0/MaoB0x+v/7iLfF/HoWWLmw+70=,iv:2RV72SqXp7rxmvnkeMlJhxsT2pNGta/xsaPspS4wmB4=,tag:PXjUSezpIj93lk/kl6ST3Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
