#ENC[AES256_GCM,data:m4huW6WM7kve8XVyZA+5YDxlZ3QpilGZ3N7h7Mq4sPQ+smmY4JecL1aETR2IZULcQoZF3TGhe0Og9sAzT5Ve+5afBz4vkw==,iv:khV4VAe6QcWG4s8f//2doS/2DhQGcbMOaUktBH3gY9E=,tag:FSH+0oaJxEssZu+14yvRxw==,type:comment]
cron: ENC[AES256_GCM,data:k9zjtXI1txPQS94M,iv:OSusRXotRA06kkhWka2UcLRPh++UxphibBjXHLBvmH8=,tag:wsYLIoZ8qMiFkMuZVpsGlw==,type:str]
#ENC[AES256_GCM,data:jh11RluMstTbWug0JarwfzwQNmYn/i0gzmQ1EDlYvxgyMUeB,iv:rknDoc2vyMGSucEVy3EmwiT61jPE30U1fDygjsG3aQI=,tag:H4WtFBVe6BUhfZes2armvQ==,type:comment]
runOnStart: ENC[AES256_GCM,data:isPp9A==,iv:tuFk8iJEq1y4sa0Exayn/koqEoFEjwXxIR7GDqIF+mY=,tag:SgH1em9C3MhF1ZHHwqZIpg==,type:bool]
origin:
    #ENC[AES256_GCM,data:F+TBP48sOO7jxfoSK/vNU+ztC6s3HyQWpn5N,iv:b57CyBkhr/QfPrZNca2fJBF2TVI9nNBZElAZmzW3ck8=,tag:y3UQLuPPXyk/2MDSvoIyQA==,type:comment]
    url: ENC[AES256_GCM,data:BmhjF9dPCtPh8a+X6kJnn9XO/ITE,iv:DRd6SsSNb96CbV7gaDD69bzPjwWdpQjT0Crv1PbgQj0=,tag:VMi3lYEAmsHtgwmdhNYglA==,type:str]
    #ENC[AES256_GCM,data:8tA5ZIFqKeMeyf6TZk3nQnFQjmP3/9rueJ5mzVvLXz4VaphDBYtS8GtNbWgqezPVD2LSDZY=,iv:D3N7JaMqQoj4LUjXPKj6CsHcTeUt/oLhudz/tcVaGPg=,tag:K9ExQ6u7j2on2bFYptOsjA==,type:comment]
    #ENC[AES256_GCM,data:qpayXXn0G6t7hgypJZiDOaDxW9zohDeS/HruTZgFemtIp9CxO51QGBpQuBEi,iv:5cglV7wz3ynm8OdUxEOVy5oCL5hpvXX9r/dGx+PSsAs=,tag:c4SBLVkNMiDk/Opv3c5IpA==,type:comment]
    username: ENC[AES256_GCM,data:MQjfQzanIg==,iv:7xDQ8wGM2cxGy95zXHSShibz+1FpjpFhi4elpfIDWgs=,tag:nMxpMJv900s/0AYKvxf6Ww==,type:str]
    password: ENC[AES256_GCM,data:kIq7zsjrpz3gpun1IGVbOu0=,iv:mbKfMeKYKOmY74+bPT/ipLUiHGvuasSn8aojk/hfC5w=,tag:CW6aLLWG6aXQkXFPvx4q/Q==,type:str]
#ENC[AES256_GCM,data:so44zTxXJTK+O870CC2z3Wwd5VFvFcuEHkfh5CM3jz4xcuoAy9Z8IQ==,iv:Sx8lfbmFvGuY4Ol9EsF9QjSueQ+5B5vy1qANg+vb01c=,tag:UM088I35Cjam/828VYsKdA==,type:comment]
#ENC[AES256_GCM,data:RJ1tkdntzBQ6,iv:biw3GK96H/xB6IUaLmEbYDVFWR5b4TzQR/EDIEdrgNw=,tag:6Ymr99KT8N8V83Qb6mDpBQ==,type:comment]
#ENC[AES256_GCM,data:l/Xe6er5nmu99Ngbio1RxqyAYYIbNBX6QjRt7A==,iv:t2OCXORveIJtyoCmfgRqQqEgFOb7tA75QlURGQRYbyE=,tag:i6Xl3F8E7QWa6fveXGXdTQ==,type:comment]
#ENC[AES256_GCM,data:3Kr22lXhhQsdPuNhzmvI5obubPWOW+kAw5zhJw+4eNR2yxYuxes=,iv:pLYqbc7v0L8ZuPQgkLGKzU10QvN6MHEQhg9SqKOe17A=,tag:tExS26E3J6IvRhvtrg1wGQ==,type:comment]
#ENC[AES256_GCM,data:0t0uDCTknfhoFS8CjQcYDQc=,iv:x5UV1jnxnUpRZOgwjDkEuY7yM3MFnqEL+a9SjKgttSQ=,tag:3dSF07txsrfuYf3ACWsPAA==,type:comment]
#ENC[AES256_GCM,data:CTVHbaCGCVHR/v2kACG5k5r+zuGo+lhZ,iv:hO2IDFmxDYubygyCD68ocWLkvyYHIEqPHxiN3yGQa74=,tag:VC0MgUpQiv5NiUYGX5NUOA==,type:comment]
#ENC[AES256_GCM,data:ghY4Fk0F00CsyrOTgbZiisDcbC2mOGnDSErjOmGY17aynO1WBTfFFiVie7lUZ7BO,iv:bpsNi8lKFR00cpRTSVP829GUB0Re5/ceIW1/cMh2Vq8=,tag:8umkEaf5SqTlGuKlZbsyaw==,type:comment]
replicas:
    - ENC[AES256_GCM,data:xfCPxaHp3G3E570EHj6JcbQw1U31r5JobllarA==,iv:UlaMN26R1tVL9RSnmeCfWL17irsZeXB1wcD4MVBefmw=,tag:3wXdKx+ArhfhvjKeUYGfhw==,type:comment]
    - ENC[AES256_GCM,data:B0ueBnO9wE5HNVCs5bCtAVxUOT2auu9srl64FHUtGd9FMOUNFzpFkPAU,iv:gK2uu9aEnua7KOqkp3FZ/TkPAgFUUgs5sIpshwl0ckE=,tag:a3j7VkQp/BHNyY39neBxbw==,type:comment]
    - ENC[AES256_GCM,data:Tt5FGVJqWULqh+wo+SmrP6SUj7Pk,iv:sP7//s6O6iNWl6lQ5wQYnZRPWh93M83v067znHY5Evk=,tag:9U8jFMq8ak5TFoIDCXY5eg==,type:comment]
    - ENC[AES256_GCM,data:PW3fVYh4Wk/yLVjj0zl17Yfuk2JttaFtRGbeiQ==,iv:Pobz7FSHe5Sof/hrXthBW6Jhbfh02rvqy1LU04UGaSo=,tag:9ivmNpZaRHo08CaBpODTdA==,type:comment]
    - url: ENC[AES256_GCM,data:BeZrcgBmofE4W1c9+X0kGjAh21NP,iv:CB6x3AJUihuL2RusvPvCGdT9zjxFP6sBIlgMk5qq9Z4=,tag:I8ezpjXsmzOJO9YM87ADLw==,type:str]
      username: ENC[AES256_GCM,data:vm62O9Eg6A==,iv:vzl7drtmORiVOzBA36dIh9LQRJvL+AB9crp22NndUVA=,tag:SnFGnkib+nMm5umhjwM4sw==,type:str]
      password: ENC[AES256_GCM,data:md5X0ceKEabooN+nevqgtco=,iv:EIx9TDzcHD/mFZXqOE26m2rVeVLwVIfYMBYeeMH7qMY=,tag:rg6P1FmCdYG1uwqSTjmR3w==,type:str]
      #ENC[AES256_GCM,data:uNnnV5oiZBYna+sF9iZOPEdhE1UlNAOdksuhrmNl+ehcr2PwnGpZyiNYsvUgUcay6qr7RDZ54ba1CVfI+n/zae6bgKH1,iv:VxmuFmb3KJP1F0t0vshJJt7yzScmLcR75K/JfNXJ4wI=,tag:lAOAcBO5GfQCMGQ25H1WmA==,type:comment]
#ENC[AES256_GCM,data:uuoGPwRiDQ5AQ1zo69rFlnSGv6izD6FCzvSrb+2vNqnU9hzcbZzvApNkpWQucAdURbGX+CljV/fI,iv:WEBQ1IBygmzVQ0nY5/JhNgXPU5lch197A8+7XoY0twA=,tag:pY1/q9WEsPJ/MLQgM22sYA==,type:comment]
api:
    #ENC[AES256_GCM,data:waVf4EUrZWHscDxUve30BAW+FQ==,iv:jUy6hxoNatc8/xhfgm9bWRiaOTbZbOo6EB5enrbCV50=,tag:9/9qdIdGhr9ZvhTC4bfRqQ==,type:comment]
    port: ENC[AES256_GCM,data:V4bmAQ==,iv:6dxjh1b1Gcz1uuRyZ8gAeu982zTY1AkHwBC6GnwreJA=,tag:OIj2p0vYrP31mJNhnxHgjw==,type:int]
    #ENC[AES256_GCM,data:lpToKnUKzPTQjDHSsm47D7F9OGyxPAcAuC/pGAnlnBVJUzmIZmZRL7PpPu7pivtdFxAowsYk14y029SGjrs5bkZ6TAsPMRLLBLMh7w==,iv:/6OyQ+KZZkIAsf6E7OErqkr2oj2juDVIRmmH702bnfA=,tag:/v1S9Is6hjXW1EmRuBWB3w==,type:comment]
    #ENC[AES256_GCM,data:UEHXCFw9NGLgq6jf3soDxSHjcQ==,iv:Xlp21JuJrLHR3FI4b20odfwMnha2KblEhJ6ebieypJA=,tag:8j2XAcBSayLnutat9EOUhw==,type:comment]
    #ENC[AES256_GCM,data:eBEz0wtAoaLZjxJ11MVhZ8TDaA==,iv:5+RuO61Xo+/pfE4mDXY/tapdZSuoNEuCEyrNF2gaYbY=,tag:njx2eBHQA0gxml3rp7SpKA==,type:comment]
#ENC[AES256_GCM,data:ZKYlyx9o9lP1lu9CpEaEkoNRglbhRGkMtm2u+4D0a+8n4w8tyjBK8V93bn65lbdgaPCP1x1Ap61yJpnVyQY=,iv:XIbtHU5UAW6M9n4llRfm6zaeAcsXfHoyRxHRvAWiZ9Q=,tag:eH7KLbZgIPFGwsTitQd1PQ==,type:comment]
features:
    generalSettings: ENC[AES256_GCM,data:Bd9f2g==,iv:hF9pUAv95RHv+1Fx9WLEdxeTCmCPs2pQ9B5cT2Tg5AY=,tag:kRXfdaW5+TS5AqYY6aYtBA==,type:bool]
    queryLogConfig: ENC[AES256_GCM,data:Nss93g==,iv:6vNmm8ExV/WhkliriDfKtktbhAUUzhBD9WQDJFeH5eU=,tag:ZfvO4eAr3g2LCiN9LFnx0A==,type:bool]
    statsConfig: ENC[AES256_GCM,data:zuBLsw==,iv:vmGAcKDOtp1r56UVOExnuHUb9TyRpaaz4lQ8uK7hPcA=,tag:Smve9u/0she8lD1WGb8MKw==,type:bool]
    clientSettings: ENC[AES256_GCM,data:mKlhCg==,iv:YknBUPOHbzRMNUh0Fz1AD03BUbPZjzcI4DXKEgBAAYY=,tag:yBsLHEgdLH1pF2VCQinmxg==,type:bool]
    services: ENC[AES256_GCM,data:a9tHDQ==,iv:Q0zQVCe5A8N9miJP67DGVT5rYW/YrRzi34sacauZD2E=,tag:1h3A3ksbFjWCjIp61mC5wQ==,type:bool]
    filters: ENC[AES256_GCM,data:/DtMZA==,iv:boo4cx2iGeSlRgkbsII3ZDA1EZlZM2uz5VTOVtBHf0I=,tag:MzX9HvPtKEPORPwZn+0Fug==,type:bool]
    dhcp:
        serverConfig: ENC[AES256_GCM,data:BrjQYBQ=,iv:4mcnW3UY/H/Mw1xCTtadhXb6fJBnk3GF881uYqol3AQ=,tag:4/r1f0KL0alX2dIODqDV3w==,type:bool]
        staticLeases: ENC[AES256_GCM,data:/dwoOeg=,iv:673id4OS2b8QJ6Hi8cQoADaIjDWCcqzd9TN1+odPyJw=,tag:cIUQzkzaSj4eV9dQgRh8zA==,type:bool]
    dns:
        serverConfig: ENC[AES256_GCM,data:WM7+uA==,iv:e30m73aI+upA00TVq6yevpXpzzqxjSvJXwSVvv+6+9Q=,tag:q4LfVYvAqPRzOeAzmeDtrg==,type:bool]
        accessLists: ENC[AES256_GCM,data:bO3agQ==,iv:RLzXhWoXltKwMJlBhnlwPM/FB2n3Z3c0Uq4gpFPYfxQ=,tag:IfIv18sibMjGXUNeMS1XMQ==,type:bool]
        rewrites: ENC[AES256_GCM,data:L3sr3w==,iv:2Z+QZzxMKHqOgFcSUL4YvhrsjaGScOlXG3d9UZZzugE=,tag:1X3pAwEkrDeMbqHPUSi4Tw==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbTdmUHU3TjFmMGtNdGY0
            Nkg4dG1FUkJCckF6Yk5Xb3lsRHdQZVZ5OTB3CjloQjkyemNGQndqUkk2WnZmRS9y
            RGxrckNVTjg5YWVOL1RhOCtDNEd3TjAKLS0tIEZ1bHFmYW11N0I2bytjbTZKTDdi
            ZmFnWFduNkJTYkhCdXNJY1FwcXY2bDQKB+Q9AAOzIgNnAGpYNUjqqUYJXPpuKSm/
            ixN+9uMLcVuWBDiwJUFjBdbG7cb3KT2TcwUXZi8xptCsiq92e8xwoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T23:10:03Z"
    mac: ENC[AES256_GCM,data:pMa4jcXgSMA+cU9gji8wBZX6v+xhnI6nxsRYnCDvYq7V9shYl0aLbV3UXlIwumOH2ozbbLQcJcgZfTGhPxdgbJMB+oC+aIQN3KZuY7O+JNRJjplSu1Of5eRRFUujGkLgF2n8bkAiaDy7DFZq+RL3UShVcK/MiAhUvo3V/bRmfSE=,iv:9EP0Y2VRXs6kiGy+M34hqOVM7P9Sny8AHYVy9HEHzSM=,tag:NAKUHAKxpxL1fMzQtQ8jOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
