global:
  scrape_interval: 60s

  # For Prometheus federation
  external_labels:
    origin_prometheus: ${HOST} # envsubst

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    # Override the global default if desired
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: '${HOST}'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: '${HOST}'

  - job_name: watchtower
    metrics_path: /v1/metrics
    bearer_token: ${WATCHTOWER_BEARER_TOKEN} # envsubst
    static_configs:
      - targets: ['192.168.86.201:8081']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: '${HOST}'

  - job_name: 'podman_exporter'
    static_configs:
      - targets: ['192.168.86.174:9882']
    metrics_path: '/metrics'
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: ${HOST}

  - job_name: 'uptime'
    scheme: http
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.86.174:3001']
    basic_auth: # Only needed if authentication is enabled (default)
      password: ${PROMETHEUS_UPTIME_PASSWORD}
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: ${HOST}

  - job_name: 'adguardhome'
    static_configs:
      - targets: ['192.168.86.174:9617']
    metrics_path: '/metrics'
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: ${HOST}

  - job_name: 'monika_exporter'
    static_configs:
      - targets: ['10.0.0.14:3001']
    metrics_path: '/metrics'
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: ${HOST}

  - job_name: postgres
    static_configs:
      - targets: ['10.0.0.14:9187']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: ${HOST}
