global:
  scrape_interval:     60s # By default, scrape targets every 15 seconds.

  # For Prometheus federation
  external_labels:
    origin_prometheus: ${HOST} # envsubst

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9090']

  # Example job for node_exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: '${HOST}'


  # Example job for cadvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: '${HOST}'


  - job_name: watchtower
    metrics_path: /v1/metrics
    bearer_token: ${WATCHTOWER_BEARER_TOKEN} # envsubst
    static_configs:
      - targets: ['192.168.86.201:8081']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: '${HOST}'
