---
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    container_name: hoarder-web
    volumes:
      - data:/data
    ports:
      - 3003:3000
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
<<<<<<< HEAD
  redis:
    image: redis:7.4-alpine
    container_name: hoarder-redis
    restart: unless-stopped
    volumes:
      - redis:/data
||||||| parent of cecde87 (fix: use new  hoarder image and remove previously needed services)
  redis:
    image: redis:7.2-alpine
    container_name: hoarder-redis
    restart: unless-stopped
    volumes:
      - redis:/data
=======
>>>>>>> cecde87 (fix: use new  hoarder image and remove previously needed services)
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    container_name: hoarder-chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: docker.io/getmeili/meilisearch:v1.10
    container_name: hoarder-meilisearch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch_20240828:/meili_data

volumes:
  meilisearch_20240828:
  data:

networks:
  default:
    external:
      name: hoarder_network
