version: '3.9'
services:
    shlink-web-client:
        image: shlinkio/shlink-web-client
        environment:
            - SHLINK_SERVER_API_KEY=6aeb82c6-e275-4538-a747-31f9abfba63c
            - 'SHLINK_SERVER_URL=https://s.test'
        ports:
            - '8000:80'
        container_name: shlink-web-client