version: "3"
services:
  netdata:
    image: docker.io/netdata/netdata
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    user: "root" # add for podman
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - "label=type:container_runtime_t" # for podman use
    volumes:
      - ./netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro # for diskspace monitoring
      - /etc/os-release:/host/etc/os-release:ro
      - /run/user/1001/podman/podman.sock:/var/run/docker.sock:z # for podman use
    #  - /var/run/docker.sock:/var/run/docker.sock:ro # for docker use
    # env_file:
    #   - .env
    environment: # use with podman and a .env file in same dir as compose
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_URL=${NETDATA_CLAIM_URL}
      - NETDATA_CLAIM_ROOMS=${NETDATA_CLAIM_ROOMS}
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "https://loki.local.timmybtech.com/loki/api/v1/push"
    labels:
      io.containers.autoupdate: "registry" # for use with podman

volumes:
  netdatalib:
  netdatacache:
