version: '3.3'
services:
    speedtest-tracker:
        container_name: speedtest-tracker
        ports:
            # - '8080:80'
            # - '8443:443'
        environment:
            - PUID=1000
            - PGID=1000
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=speedtest_tracker
            - DB_USERNAME=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - './config:/config'
            - './web:/etc/ssl/web'
        image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
        restart: unless-stopped
        labels:
           traefik.enable: true
           traefik.docker.network: traefik_network
           traefik.http.routers.speedtest.rule: Host(`speedtest.timmybtech.com`)
           traefik.http.services.speedtest.loadbalancer.server.port: 80

networks:
  default:
    name: traefik_network
    external: true
