version: "3.3"
services:
  speedtest-tracker:
    container_name: speedtest-tracker
    ports:
      - 8083:80
      # - '8443:443'
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_NAME="Speedtest Tracker"
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=https://speedtest.timmybtech.com/
    volumes:
      - ./config:/config
      - ./web:/etc/ssl/web
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_network
      traefik.http.routers.speedtest.rule: Host(`speedtest.timmybtech.com`)
      traefik.http.services.speedtest.loadbalancer.server.port: 80
      io.containers.autoupdate: "registry" # for use with podman

networks:
  default:
    name: traefik_network
    external: true
