---
version: '3'

volumes:
  grafana_data:
    external: true

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
#    user: "1000"
    ports:
      - "3000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
    environment:
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel,alexanderzobnin-zabbix-app"
      - "GF_PLUGINS_ENABLE_ALPHA=true"
    restart: unless-stopped