version: "3"

services:
  promtail:
    image: grafana/promtail:3.4.2
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro # uncomment if using docker logs
      # - /var/run/docker.sock:/var/run/docker.sock # uncomment if using docker logs
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
