version: "3"

services:
  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # - ./promtail-config.yaml:/etc/promtail/config.yml
    # command: -config.file=/etc/promtail/config.yml
    # restart: unless-stopped
