version: "3"

services:
  promtail:
    image: docker.io/grafana/promtail:3.2.0
    container_name: promtail
    network_mode: host
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml:Z
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    labels:
      io.containers.autoupdate: "registry"
