version: '3.9'
services:
    # run with default config
    monika_basic:
        image: 'hyperjump/monika:latest'
        network_mode: host
        container_name: monika
    # run with plugin
    monika_comlpex:
        image: 'hyperjump/monika:latest'
        volumes:
            - '${PWD}/config:/config'
        container_name: monika
        network_mode: host
        command: monika -c /config/myConfig.yml --prometheus 3001
