version: '3.3'
services:
    adguardhome:
        container_name: adguardhome
        restart: unless-stopped
        network_mode: host
        volumes:
            - './workdir:/opt/adguardhome/work'
            - './confdir:/opt/adguardhome/conf'
        image: adguard/adguardhome
        labels:
            io.containers.autoupdate: "registry"

    adguard_exporter:
        image: ebrianne/adguard-exporter
        restart: unless-stopped
        network_mode: 'host'
        container_name: adguardhome_exporter
        environment:
            - adguard_protocol=http
            - adguard_hostname=${ADGUARDHOME_HOSTNAME}
            - adguard_username=${ADGUARDHOME_USERNAME}
            - adguard_password=${ADGUARDHOME_PASSWORD}
            - server_port=9617
            - interval=30s
            - log_limit=10000
        labels:
            io.containers.autoupdate: "registry"
