version: '3'

services:
  apprise:
    # git clone https://github.com/caronc/apprise-api.git
    build: .
    container_name: apprise-api
    ports:
      - 8001:8000
    user: "www-data:www-data"
    volumes:
      - ./apprise_api:/opt/apprise/webapp:ro
      # if uncommenting the below, you will need to type the following
      # Note: if you opt for bind mount config file consider setting env var APPRISE_STATEFUL_MODE to simple with appropriate file format
      # otherwise the django instance won't have permissions to write
      # to the directory correctly:
      #   $> chown -R 33:33 ./config
      #   $> chmod -R 775 ./config
      # - ./config:/config:rw
      # Note: The attachment directory can be exposed outside of the container if required
      #   $> chown -R 33:33 ./attach
      #   $> chmod -R 775 ./attach
      # - ./attach:/attach:rw

# linuxserver version
# ---
# version: "2.1"
# services:
#   apprise-api:
#     image: lscr.io/linuxserver/apprise-api:latest
#     container_name: apprise-api
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=Etc/UTC
#     volumes:
#       - /path/to/config:/config
#     ports:
#       - 8000:8000
#     restart: unless-stopped
