# gotify with alertmanager-to-gotify integration
version: '3.3'
services:
  gotify:
    image: gotify/server-arm64
    container_name: gotify
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - TZ="America/New_York"
    volumes:
      - "./gotify_data:/app/data"
      - "./config.yml:/etc/gotify/config.yml"

  alertmanager-to-gotify:
    container_name: alertmanager-to-gotify
    # image: a1kmm/alertmanager-to-gotify
    ## Build from source repo instead of using the image
    ## git clone https://gitlab.com/A1kmm/alertmanager-to-gotify.git
    build: ./alertmanager-to-gotify
    restart: unless-stopped
    ports:
      - 8435:8435
    environment:
      - GOTIFY_TOKEN=${GOTIFY_TOKEN_ALERTMANAGER}
      - GOTIFY_MESSAGE_ENDPOINT=http://gotify/message
    links:
        - gotify
