---
version: "3"

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
    labels:
      io.containers.autoupdate: "registry" # for use with podman

networks:
  default:
    name: prometheus_network
    external: true
