version: "3"

services:

  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp_exporter
    restart: unless-stopped
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
    network_mode: host
    command:
      - "--config.file=/etc/snmp_exporter/snmp.yml"
