version: "3.9"
services:
  agent:
    image: "portainer/agent:2.13.1"
    volumes:
      - "${HOME}/.local/share/containers/storage/volumes:/var/lib/docker/volumes"
      - "/run/user/1001/podman/podman.sock:/var/run/docker.sock:Z"
    restart: always
    security_opt:
      - label=disable
    container_name: portainer_agent
    ports:
      - "9001:9001"
