services:
  agent:
    image: "portainer/agent:2.16.2"
    volumes:
      - "${HOME}/.local/share/containers/storage/volumes:/var/lib/docker/volumes"
      - "/run/user/${USER_ID-1000}/podman/podman.sock:/var/run/docker.sock:Z"
    restart: always
    security_opt:
      - label=disable
    container_name: portainer-agent
    ports:
      - "9001:9001"
    labels:
      - io.containers.autoupdate: "registry" # for use with podman
