version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${PG_DB_DATABASE}
      - GITEA__database__USER=${PG_DB_USER}
      - GITEA__database__PASSWD=${PG_DB_PASSWORD}
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "721:3000"
      - "222:22"
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:14
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=${PG_DB_USER}
  #     - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
  #     - POSTGRES_DB=${PG_DB_DATABASE}
  #   networks:
  #     - gitea
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data
