services:
  nexterm:
    ports:
      - "6989:6989"
    restart: always
    volumes:
      - nexterm:/app/data
    image: germannewsmaker/nexterm:1.0.1-OPEN-PREVIEW
    container_name: nexterm
volumes:
  nexterm:
