version: "3"

services:
  portainer:
    image: portainer/agent:2.20.3
    container_name: portainer-agent
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    ports:
      - "9001:9001"
