---
version: "3.7"
services:
  exporter:
    image: ghcr.io/hansmi/prometheus-paperless-exporter:latest
    restart: on-failure
    container_name: paperless-ngx-exporter
    init: true
    ports:
      - 8081:8081
    environment:
      - PAPERLESS_URL=https://paperless.local.timmybtech.com
      - PAPERLESS_AUTH_TOKEN_FILE=/etc/exporter/auth-token.txt
      - PAPERLESS_SERVER_TIMEZONE=America/New_York
    volumes:
      - ./config/:/etc/exporter:ro
