version: '3.1'
services:
  web:
    # image: alerta/alerta-web
    build: .
    image: alerta-web
    container_name: alerta
    # To set config settings not supported by env variables use config files
    # volumes:
    #   - $PWD/config/config.json:/web/config.json
    ports:
      - 8082:8080
    environment:
      # - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=${PG_CONN_STRING_ALERTA}
      - AUTH_REQUIRED=True
      - ADMIN_USERS=${EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_KEY=${ADMIN_KEY}  # assigned to first user in ADMIN_USERS
      - ADMIN_KEY_MAXAGE=500
      - PLUGINS=remote_ip,reject,heartbeat,blackout,normalise,enhance,influxdb,prometheus,slack,syslog
    restart: always
