global:
  scrape_interval: 60s # By default, scrape targets every 15 seconds.

  # For Prometheus federation
  external_labels:
    origin_prometheus: pihole2

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 60s
    static_configs:
      - targets: ['localhost:9090']

  # Example job for node_exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
#      - targets: ['192.168.86.174:9100']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: 'pihole2'

  - job_name: 'snmp_exporter'
    static_configs:
    - targets:
      - '192.168.86.44'
    metrics_path: /snmp
    params:
      module: [synology]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        regex: (.*)
        replacement: localhost:9116
        target_label: __address__

  # Global exporter-level metrics
  - job_name: 'snmp_exporter_global'
    static_configs:
      - targets: ['localhost:9116']

  - job_name: 'adguardhome_sec'
    static_configs:
      - targets: ['localhost:9617']
    metrics_path: '/metrics'
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: 'pihole'
    - target_label: status
      replacement: 'secondary'

  - job_name: 'adguardhome_prim'
    static_configs:
      - targets: ['localhost:9618']
    metrics_path: '/metrics'
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: 'pihole2'
    - target_label: status
      replacement: 'primary'

  - job_name: 'podman_exporter'
    static_configs:
      - targets: ['localhost:9882']
    metrics_path: '/metrics'
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: 'pihole2'

  - job_name: 'pve'
    static_configs:
      - targets:
        - 192.168.86.160:8006
        - 192.168.86.199:8006
    metrics_path: /pve
    params:
      module: [default]
      cluster: ['1']
      node: ['1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9221

  - job_name: 'paperless-ngx'
    static_configs:
      - targets: ['192.168.86.174:8081']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: 'pihole2'


#  - job_name: 'uptime'
#    scheme: http
#    metrics_path: '/metrics'
#    static_configs:
#      - targets: ['192.168.86.174:3001']
#    basic_auth: # Only needed if authentication is enabled (default)
#      password: uk1_something_here_for_auth
#    relabel_configs:
#    - source_labels: [__address__]
#      regex: '.*'
#      target_label: instance
#      replacement: 'pihole2'

#  - job_name: 'pihole'
#    static_configs:
#      - targets: ['192.168.86.174:9617']
#    relabel_configs:
#    - source_labels: [__address__]
#      regex: '.*'
#      target_label: instance
#      replacement: 'pihole2'
