nut_server:
    host: ENC[AES256_GCM,data:FS1UUK9N9OvIh66zxQ==,iv:Roa4Uk2nOBghOCFkBYY0cv6LYRQ5KCK3f7PVujKgUVU=,tag:vHoEHKfTJQbwAwdVUMeCAw==,type:str]
    port: ENC[AES256_GCM,data:mxVbeg==,iv:nKMfmeYHTOcYsLLHYUpAPWHfSxlFt0ipOzbaWzxVxTM=,tag:3PDLi2rQ+TPGau1XQ7BBgw==,type:int]
    timeout: ENC[AES256_GCM,data:oA==,iv:oQ4aoNwMaZmYeLWWPLe/SH31IHHpES64C7BQMGA9kYw=,tag:eKZxfpRUYIYsY31eJIAmxg==,type:int]
notifications:
    enabled: ENC[AES256_GCM,data:tCS3bQ==,iv:UKvWd3+7qxkYAt1Klzzi0eXqLMcl9oH6INDSy4GXP+c=,tag:W7+cPppEdnxnmYkV+iTGkw==,type:bool]
    cooldown: ENC[AES256_GCM,data:kJI=,iv:ky+YhBmXPcEmQAtbiwHLIyIu+GAXgzaWphVvRQ3Ur0o=,tag:w6ZnijStj37L+sfWMzUD4g==,type:int]
    urls:
        - url: ENC[AES256_GCM,data:tsBVm+rbuzgqsY+zG0oFtOoVCNyWMaVrbjZgTyAOF+d6HcIXno9uctUkmGbBQvaPLd/O4r7ycCdErlEGvev0/3IuiUNV8Xw3ixw21HIHId42SgGW3A==,iv:G3QHCKcRfnkLv2wD4wHSl6OG5fh/Fj8AKi56RtEbMnY=,tag:6ihXkGwG6orQcK4+yRxeOQ==,type:str]
          enabled: ENC[AES256_GCM,data:8f6fsQ==,iv:1YLjohNphFuPJoFWhrMCD9CoJZPv0xMtWzVp/AYG3Z0=,tag:7eDQn5CsUVrlDb34CcbTlQ==,type:bool]
        - url: ENC[AES256_GCM,data:EKHNrPHLSqIM6oOD5UR17Cug6L8oWggn1TDX+gSC0joHSg+aMgVYvy45q0XDZO89rL/fO0cPu8GypSNrKBV3PGMJI/LHkJqj2B97MtaAxYioSuCPdtNmXVMuo4pwjjLWaaY=,iv:YLxfHhcpFXVdGq3S4I1+yVnTS+TVKi2v96jPalfAYGE=,tag:NIwNeyGlI4nt+rtNVx4xpA==,type:str]
          enabled: ENC[AES256_GCM,data:eDx1JQ==,iv:MQnhlaDryyUPR9yEF0Fffe2qBAM1yUq0hXNpXZ62wjo=,tag:+cQ7kWetjXo0bhbiyRahXA==,type:bool]
check_interval: ENC[AES256_GCM,data:NR4=,iv:oWtw/iA8y3t0rwYzE9KqgeCgoLQq03Wig7+GkUlrOag=,tag:l57xd+3NGeavKRgTp9TLgw==,type:int]
alert_mode: ENC[AES256_GCM,data:Yq2WtUY=,iv:BfrWCJYkIPgEnAiISmbPy+TQ9neXSIB/eV3NFZfycUE=,tag:9JXpZZsR5x8cBvJmT5HYtg==,type:str]
basic_alerts:
    battery_charge:
        enabled: ENC[AES256_GCM,data:BxiSvA==,iv:URFFTf7hza45GmgL8BplHuJVLTpaORdhMyIuvFDvRpk=,tag:AVq6Cdzluw5a5t4fBMLfTA==,type:bool]
        min: ENC[AES256_GCM,data:p8o=,iv:3m89wq6mlA7yh2Fcp2YDV+ll0EjsneqZEUVoliz2gzE=,tag:Yr4ouLcK92sLAlr5EztXbw==,type:int]
        message: ENC[AES256_GCM,data:dj/CCTxxgl6uAJ+b6HaoRFrDXr8y9iaJwjrYI4exBhfDdZ6GmebHIu7s,iv:AHqz8rKTCKs/eTaavQlurEMR0a/Q/tnQG3MmC2PZK9s=,tag:TsnM4C6uNsrJJO1vFr0rOA==,type:str]
    runtime:
        enabled: ENC[AES256_GCM,data:kCixMw==,iv:W00HxMB7EL2sLEvKpNIspZ3gnJ3RMKiKjgssFtk8PsQ=,tag:LuOy2NwIBNt6PvEUYARsMg==,type:bool]
        min: ENC[AES256_GCM,data:7Ds=,iv:2rR4GTWwPG6y4I9qHpY75T6BEaPfOuH33yYpfFfOp3w=,tag:74/QoM9yjtjs+EcwAlBeHw==,type:int]
        message: ENC[AES256_GCM,data:O3bzQAZZ9L5XwICTRCKNUBiXuJcF5E9sS6qDvCYtUhoNMtU=,iv:uatC8ZsFuYVI4ohygYADwZO7o2HTxCwbRcUgM+u3J2o=,tag:f6WlatLQsQrMNM9pcb9n8Q==,type:str]
    load:
        enabled: ENC[AES256_GCM,data:JuNMxA==,iv:eQ5167n/wt8NTU+wmwWLC8xi9X2hYDYvndZs5YY6xog=,tag:JpkLFttMaccorOGptdughw==,type:bool]
        max: ENC[AES256_GCM,data:7rc=,iv:E3gJtmkcA0hOXkyxJicgZgi2n1J1NdFSyTo96f+YCio=,tag:z7CGggNV4670dSXm+vTgcw==,type:int]
        message: ENC[AES256_GCM,data:zrA7/xytCM7ENzAZYM2pvY6wNnHQPS35wXAKhr5i3GKtzw==,iv:A31PnRP23UUP60eRONyt1/1jNFCTJdZHZa4laLqoxGc=,tag:4s+RCt0A8tGHJ9qTjU3btw==,type:str]
    input_voltage:
        enabled: ENC[AES256_GCM,data:T/k0s5E=,iv:fGnahgN901BAHT+gIA0TyZNQSPJ/J8yNg5VSu7ljUvk=,tag:zcz32vqG0XptsvC6fgveJw==,type:bool]
        min: ENC[AES256_GCM,data:O833,iv:0Gzbn9VlHc3UAXIZvILhtSK9m4uhPlMVq4juZGXhPTg=,tag:mBZJsgYMkCdBPj5+9U7LUA==,type:int]
        max: ENC[AES256_GCM,data:yJkh,iv:0wpdfkv7WTadYFBGqEBcVL3oNUxpAJ2XB04vAx86NS8=,tag:GyzPdYKjmvTlMBgFAmd58Q==,type:int]
        message: ENC[AES256_GCM,data:W6ipcdZYm/RSWMm+8Oikqo1QoDVYaSANPI2BR5DZKt9oqepddoQee708,iv:R9Dbo3IffAqSd8cXxDyVrmmv9tL1L+jLW14L2WE0JKE=,tag:ageZCgBeqbb6ZNlB+YB/Hw==,type:str]
    ups_status:
        enabled: ENC[AES256_GCM,data:QE6O+A==,iv:MGYC7rkXdvo0GsDgqCEc2BDwApXyT2zi7bxUvfoPRmM=,tag:gfKLWLTHYWrd5Rvy1ipXNA==,type:bool]
        acceptable:
            - ENC[AES256_GCM,data:cR8=,iv:VhCgEEVw74NgBXZmeUGYQ5wrRJiVh2ZJ5l14Fbym9P4=,tag:TxMDT4F/cPrbPu7Oakdw3A==,type:str]
            - ENC[AES256_GCM,data:DuUewFn1,iv:4R8LCkaCYfLLzm6X3TPTWO5/15qv6kbiPU/bEFsTIlw=,tag:Y/HLLaNKi5gabLfhMUox3g==,type:str]
            - ENC[AES256_GCM,data:GV704O1FHQ==,iv:ZF4mz92xqtA26KP969G+A0cpLRohWGZoIEID0dk1IFg=,tag:5pa8i1BvXZlp7yPHFQUO6w==,type:str]
        alert_when_status_changed: ENC[AES256_GCM,data:9Xf6Mn8=,iv:rj6QOonIsm72Cgz1+IHw/ffF3kCXYirlhNJUeW6Qg0M=,tag:F6JF9zxWppYt+D7b3z1Ofg==,type:bool]
        message: ENC[AES256_GCM,data:GbsyyG9yKqXiwKbJwsVxFQEC8xdXpI8QseJikhHINqzI,iv:Gg9E+g1ut17vshqSMPYbVup/qeJ1EbtLxFUboITXKzo=,tag:JLdxJXLGkPuLK/5jkyCLOQ==,type:str]
formula_alert:
    expression: ENC[AES256_GCM,data:5bYG0Zho/U5AcxcWkylsmqaG5fChs8Z+SESibpbqPlYzilu9VLB/zvhNmyGbmCWjzAk3ODsuoVxPce/m8XMgzgbVkiWyJQ==,iv:amgy9tGWGvkdhWDVozjKCppe5ozb8a7Al4HY2q6bqUs=,tag:HyKyE2VT9G2rVSKpOz2Itg==,type:str]
    message: ENC[AES256_GCM,data:HR8p1ysx+rhP7BjDegJyJK7mvrXRSuIsD3uRKeoOApc9EsiV0DygPxubiqqgl5RIrx2DoT9HRZm3r++ALrpOQqA2uGxDKnsusSi6V4QaSLYODjOnq6IeBU2QCL4=,iv:GUiKafDrNQAdFuCHYuJFrK5aas1V6dmOSzBRkFNSuos=,tag:LTqGYRHzXS8jHyQ7dzc41A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMTBhQzZ3UnllTG1LN001
            N1doOGIzYXVydXk2aVpCb2w1bHFaOCt5WlVJCmt2d1lWR2pBdUpUbWtDTEVRYmpi
            R0doZmFKTEpvMW1UT3FNMEdHRkt0OGMKLS0tIGxqV3MwQldCRk9yL3dlTmc2aGhH
            TXMwSkpHMnd2dXBQT016SFRoMDduc2cKIMgPwAMi/4tlzWnpIX1aGTrZJMDnbrhI
            14MzvDVNEzktz7STuP25M1oVgKGPl146mrj9tJlnjnZ55ESwZcKNOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-02T20:18:23Z"
    mac: ENC[AES256_GCM,data:SC2ASxksm1oJA7ZlOowfXNkcyxULne7ZV71ZNzagC0rzd/zkZaN/ppjH7ug7qJPICgebDv5AruUzB1J/LDEpCsBgSeuBKxDjKVcYVkfyiRrABqEvpow4KR3nkbkW97J8HdpMcpEA1PQgcaPaUT5LFRG58QxY9T9Q4hjSfFVyjOU=,iv:8ws6Nv2/bvCEfrxYWnXhS7yj30CW2y8o/DgwLOCBVrQ=,tag:I/u0cLCaUWL92l0LcFttqw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
