nut_server:
    host: 192.168.86.44
    port: 3493
    timeout: 3
notifications:
    enabled: true
    cooldown: 60
    urls:
        - url: ENC[AES256_GCM,data:A6tXnlKzzFT3gZKWqZu0u2QdeJ6kPN2ul0SaWTfDlVVca0aMd2DEo0/DWBaa6zPShckrxz6o15rZBotT7Tl1L03gjm9ZJi+cZom2IVq6X+KoauEc4A==,iv:g2GWyzVL+mfS1/iKmpowsAwnlEx/P42WSgtIu8TLTqE=,tag:1AuTE0in8UW9sC+cUQIP4Q==,type:str]
          enabled: ENC[AES256_GCM,data:eNx3Ww==,iv:eU7fWnR7MTdLIBPS42YmE5YoykvFnG5jEtfjNlDPDXo=,tag:L5HwwXN/U1R1fxutVViBbQ==,type:bool]
        - url: ENC[AES256_GCM,data:RBTMnOoDzbywBJGDuG8kj6fipCzkuZ6p3rl0licRpF+p2n1FQPWa7LddbKkNwJ34x7RL490qIrumZGqHeZHwQdfC+CAHjkJ3GP2PPJ2aWU0twTMSIocH5O5+vOf/r+mFBSU=,iv:BVIf4niM4k8aQ76ymIyUksGBKbrmsksiYy9IgOve/dM=,tag:rlgUAhG495k8XygToxXjSw==,type:str]
          enabled: ENC[AES256_GCM,data:2a3YPQ==,iv:MIfOElgWTgkzMu5pVP0u1ZgpRvcD4zTUHbGj8gp59Hs=,tag:UeoTm7TI/ToQEhMu01ET/A==,type:bool]
check_interval: 15
alert_mode: basic
basic_alerts:
    battery_charge:
        enabled: true
        min: 90
        message: UPS battery charge below minimum threshold
    runtime:
        enabled: true
        min: 15
        message: UPS runtime below minimum threshold
    load:
        enabled: true
        max: 50
        message: UPS load exceeds maximum threshold
    input_voltage:
        enabled: false
        min: 110
        max: 130
        message: UPS input voltage outside acceptable range
    ups_status:
        enabled: true
        acceptable:
            - ol
            - online
            - ol chrg
        alert_when_status_changed: false
        message: UPS status not in acceptable list
formula_alert:
    expression: (battery_charge < 90 or actual_runtime_minutes < 20) and ups_load > 20
    message: 'UPS load: {ups_load}%, charge: {battery_charge}%, runtime: {actual_runtime_minutes:.1f} mins'
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQlFFNGpmTXhzQng0eTRU
            dzMzV0NZMmtwRUJrTGdWTzNDd2YyUUhtdWdvCk5TczhFQzdoY1FzRU9oWDdIWTVV
            ZTdOR0RmbFhKbXhXZStvb0xwVGhwYk0KLS0tIGMwUnBOcVJadXFzWU95dkZHVnhp
            elRrNVh1Q0o0ZytueVpvd0lJRmR4bnMKfxjaioRxoBPn7MRzHWxLaEe6TNEPw4NJ
            ll8rozKzD1TU0h91ph2TdJq0qRJJI9lzcvDVKKHOPD5Lw41SWXH4sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-22T13:13:01Z"
    mac: ENC[AES256_GCM,data:bRXWkpAWA7mbEYBLp3Jc0IWf+ikvXzOsynjRXJ0RWFyxtuJjNJPsbNWJIgFByvjOzkOyAR7MKXkii4klkr/xfLcmVcAYV/yGQ+212ufIWaUIpGOcCbKcR7QnIR5BqSxN2RUGB2BV0osrv6o62GNmKE2YqzZcXWYfcLZFUSyXCrw=,iv:xgd9I+hQN1kuQervLqPZ3jnKmsa+OBC0hT1AbvwleMg=,tag:efNW89sgmCPGzG8OT266Ww==,type:str]
    pgp: []
    encrypted_regex: ^(urls)$
    version: 3.8.1
