nut_server:
    host: 192.168.86.44
    port: 3493
    timeout: 3
notifications:
    enabled: true
    cooldown: 60
    urls:
        - url: ENC[AES256_GCM,data:ETM2Oh/W2khtvubI3JL0+6yHLw1wINZQpBcnybPr1pUwBz2K2SLVJ1Lzb3OZKNHj8bZBTxJXZKKKqc42JODOp8LXxbIMymvbXhCdXG/mKE7eFIHxyA==,iv:p0TtPySNmMpBzklnLrh2Ll53VWHuZZm3wlEr4DKWP38=,tag:57pMY+iWXPKFY3n9N+IkCw==,type:str]
          enabled: ENC[AES256_GCM,data:bC0cSA==,iv:+YsCeJDKbQJ9drpFOzSaNKoUldGsmNaSwbOcIsgSrks=,tag:VJaWCmKiwQU1+FdOUndyRw==,type:bool]
        - url: ENC[AES256_GCM,data:Hz1mZlpHU4CHcTwH4t9C/jQQlC8V/2lYeT8uzBFEUWI7b4igTlftHUrAW32WT+7uKAAVtFKZ/zMz2sUfbqNAADF6E0Ca71YXejkKYkk+Wd1Orvbes5/W1xWVmPI1WoaFYq0=,iv:LDz7kA5pMKVQIOMFw0svykL3nMCWw14lNSFFq6STZYc=,tag:hYqwZ2ovbfgqfYLruwu8BA==,type:str]
          enabled: ENC[AES256_GCM,data:5dTnpA==,iv:LsxkBsURqdu6AbFrFNrdIMbnKIbOwdkIAjcBk8DEbLI=,tag:H65IC3vpvj6Gk6h3HUJ2GA==,type:bool]
check_interval: 15
alert_mode: basic
basic_alerts:
    battery_charge:
        enabled: true
        min: 90
        message: UPS battery charge below minimum threshold
    runtime:
        enabled: true
        min: 15
        message: UPS runtime below minimum threshold
    load:
        enabled: true
        max: 50
        message: UPS load exceeds maximum threshold
    input_voltage:
        enabled: false
        min: 110
        max: 130
        message: UPS input voltage outside acceptable range
    ups_status:
        enabled: true
        acceptable:
            - ol
            - online
        alert_when_status_changed: false
        message: UPS status not in acceptable list
formula_alert:
    expression: (battery_charge < 90 or actual_runtime_minutes < 20) and ups_load > 20
    message: 'UPS load: {ups_load}%, charge: {battery_charge}%, runtime: {actual_runtime_minutes:.1f} mins'
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMVRHcVhYZlNGVCtmQjlh
            alNXeGJUMVUyaEU1a1Bjb3dadDhFRFkvQm1nCmNmYkRUdkFtc3V1VTdMdisvY200
            aUJIdTRzRGlCT01RLy9ha3BaeHUyb2MKLS0tIHVObFZZb051MnVYb214eTRaK3BD
            YnJaT3VDVi95Y0NWc1FETHVTSGtQYmsKenKHgpNR1daZb4saWOFLBu4y5qyqsj5W
            dJmkQ7ROM3kHtkRqRajsBgmdmJ/QjzbSvKJAZiMvLaEWVlS1m8avHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T00:51:17Z"
    mac: ENC[AES256_GCM,data:oEDUS31Hg6r2cUOfKd5knEK61ponjWSAUIAsNMQMOKseWUzjusb8KNuVDG1zRKaD920vNI8jXWlXs5C29WkOK3xZe4ighwsKPYCB+vKbxXoYhw80XNc/tH5c/lQ7KEDip9q0k2jdsd6HHAw3zjHZOQsf2jKiXkvvmcVAOART4rE=,iv:OTPIbG1Mv/lMyCrw1CJmsZVhWbsldmttoYvjYs06mSI=,tag:6G46yDeLKeDxSA6YgLN9wg==,type:str]
    pgp: []
    encrypted_regex: ^(urls)$
    version: 3.8.1
