---
# gotify with alertmanager-to-gotify integration
version: "3"

services:
  gotify:
    image: gotify/server:2.6.3 # oci: gotify/server-arm64
    container_name: gotify
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - TZ="America/New_York"
    volumes:
      - "./gotify_data:/app/data"
      - "./config.yml:/etc/gotify/config.yml"
    # oci
#    logging:
#      driver: "json-file"
#      options:
#        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        
#  alertmanager-to-gotify:
#    container_name: alertmanager-to-gotify
#    image: a1kmm/alertmanager-to-gotify
#    build: ./alertmanager-to-gotify
#    restart: unless-stopped
#    ports:
#      - 8435:8435
#    environment:
#      - GOTIFY_TOKEN=${GOTIFY_TOKEN}
#      - GOTIFY_MESSAGE_ENDPOINT=http://gotify/message
#    links:
#        - gotify
#    labels:
#        - com.centurylinklabs.watchtower.enable=False
