services:
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle-agent
    command: agent
    volumes:
      - /run/user/${USER_ID}/podman/podman.sock:/var/run/docker.sock:z
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    environment:
       - DOZZLE_HOSTNAME=${HOSTNAME}
    ports:
      - 7007:7007
    labels:
      io.containers.autoupdate: "registry"
