global:
    scrape_interval: 60s
    external_labels:
        origin_prometheus: homelab-oci03
scrape_configs:
    - job_name: prometheus
      scrape_interval: 60s
      static_configs:
        - targets:
            - 10.0.0.26:9090
    - job_name: node_exporter
      static_configs:
        - targets:
            - node-exporter:9100
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
          #    - job_name: fail2ban_exporter
          #      static_configs:
          #        - targets:
          #            - fail2ban-exporter:9191
          #      relabel_configs:
          #        - source_labels:
          #            - __address__
          #          regex: .*
          #          target_label: instance
          #          replacement: homelab-oci03
    - job_name: podman_exporter
      static_configs:
        - targets:
            - 10.0.0.26:9882
      metrics_path: /metrics
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
    - job_name: uptime
      scheme: http
      metrics_path: /metrics
      static_configs:
        - targets:
            - 100.71.136.91:3001
      # Only needed if authentication is enabled (default)
      basic_auth:
        username: ENC[AES256_GCM,data:DnZ1K6GRsQ==,iv:5aNCHH4GGSfFIGa5omVMBG8jB69+hHiI/xq+5FOwMNE=,tag:S62LeXZnIQm/ug+cWUG7CA==,type:str]
        password: ENC[AES256_GCM,data:c12uOV7tfVfSTQN3MjrToUtn1U9OoczKgqp+I+sX7+pTuRUeGQaI4lkn83o=,iv:An5Ojt44dh+V92Ja/Tp3dH9Gv4vCNIRPoCEMzz0CPl8=,tag:l1HvHkKTmlx5JLNB7CET/w==,type:str]
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
    - job_name: crowdsec
      static_configs:
        - targets:
            - homelab-oci03.tailebee.ts.net:6060
            - homelab-oci03.tailebee.ts.net:60601
      metrics_path: /metrics
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
#  - job_name: 'monika_exporter'
#    static_configs:
#      - targets: ['10.0.0.14:3001']
#    metrics_path: '/metrics'
#    relabel_configs:
#    - source_labels: [__address__]
#      regex: '.*'
#      target_label: instance
#      replacement: 'homelab-oci03'
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VVErMkRlaFpiTkhuVWtH
            Q0dTS29rTVgzYUhiYXRoOUoyU2QzdEdFdEUwCldLdWJMRmgxcVZtSGNzWjNtRmJq
            b3ozWGc2YWJRU04wNTNLd09EbDFleUUKLS0tIGlnZGlWOE1qOEdKeDNOS3hXaVFF
            MHo2TFBMbXdSOVV1M3MySWZZMTdPRWMKQ0Lj2juxODFC28Tk0rRcoou2vGzf1jgT
            dC+g07J74DufGU3j+GhkE+HbvBvXyl2vTmyydIEc9fLdKMPYkkR5Qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T16:15:06Z"
    mac: ENC[AES256_GCM,data:JbMnmpkxUw8S5okMUnlU6t4tsLr1HoBKuIOktO4INzJLoTvNE3gZpvw8fa7DfZHSip/9vTdW3lCJjZ9BJTnuL76uqhhopun2C/aGJIrbuomHofg9jXk7ieQk1/SZkJPt6quydzheuju3G6OxaYIbkFZSHg4FxP2KTxCWyTLUgW0=,iv:/nlH8AgagSCCINnWVKhlu9pn5YVF3NBglBce3zWkaI4=,tag:OMNmMa74bYGp7+10RsY6Ag==,type:str]
    pgp: []
    encrypted_regex: ^(basic_auth)$
    version: 3.9.1
