global:
    scrape_interval: 60s
    external_labels:
        origin_prometheus: homelab-oci03
scrape_configs:
    - job_name: prometheus
      scrape_interval: 60s
      static_configs:
        - targets:
            - 10.0.0.26:9090
    - job_name: node_exporter
      static_configs:
        - targets:
            - node-exporter:9100
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
    - job_name: fail2ban_exporter
      static_configs:
        - targets:
            - fail2ban-exporter:9191
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
    - job_name: podman_exporter
      static_configs:
        - targets:
            - 10.0.0.26:9882
      metrics_path: /metrics
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
    - job_name: uptime
      scheme: http
      metrics_path: /metrics
      static_configs:
        - targets:
            - 100.71.136.91:3001
      # Only needed if authentication is enabled (default)
      basic_auth:
        username: ENC[AES256_GCM,data:HMtDoFGtrA==,iv:w+L/1ZY6dfann2N+o7RCywdjXMqQzvlaxJXrMEj5p+s=,tag:h/ofI+hkT8KDJE4c1WFcAg==,type:str]
        password: ENC[AES256_GCM,data:rbICygI9p+z/+yRyzLgg4NhAoEvN0hNZVLJPfjYEJAeFwQ3LA3ngQ0zV/gw=,iv:TFduYw/HIg4rH4K/XkrX4gA3Lwni2Td1OdnxxxT9N+Q=,tag:1kwR73FgJvZWptehWueRVw==,type:str]
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
#  - job_name: 'monika_exporter'
#    static_configs:
#      - targets: ['10.0.0.14:3001']
#    metrics_path: '/metrics'
#    relabel_configs:
#    - source_labels: [__address__]
#      regex: '.*'
#      target_label: instance
#      replacement: 'homelab-oci03'
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RVc3YnZzOFVzWG5tMlpZ
            dWhjRWdIQjdncnMrTU1FaEUycGp3U1ZibENvCkhTQkFOeUJreGFvNWQwa0F2R2Iv
            NWVPNWlGQTlmT3BKRkU3S3hGaE9RWDQKLS0tIHFxbWpkRWtBZE9TQ2UvOTYybHQx
            TTVLUHhsb080K2dteUtUUUR5VjhYWFkK9TtlZWkwqFgdSnaHvSH7d5iDmDt7+AjN
            WQNIHBY24JH0hV/G/SteVqwlV1qU24WkOM50OuN/kwwtKRluQGcu3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T10:29:26Z"
    mac: ENC[AES256_GCM,data:2XbxypepIwrRBeXahKuFNtwHsyIt3uQ8v85desSonDG8RWOO6182m0spbhItHu4ZM+wmFhoSh1HIfy/2UCV93GsJAekNJDRPRBpU5ZE1sZx1jXL2L1ZXG5ju5fFH2GuBo6c9c6wpgv96QrKp8eXAFomleEs0WNSN91E1pKcNOGY=,iv:tRnAgBw6k7LtqlARidk/kWAVjQ1S1jWFXGMDqLFJIQE=,tag:5JU5Rr05tvPbN5/FL+RE4w==,type:str]
    pgp: []
    encrypted_regex: ^(password|username)$
    version: 3.9.1
