global:
    scrape_interval: 60s
    external_labels:
        origin_prometheus: homelab-oci03
scrape_configs:
    - job_name: prometheus
      scrape_interval: 60s
      static_configs:
        - targets:
            - 10.0.0.26:9090
    - job_name: node_exporter
      static_configs:
        - targets:
            - node-exporter:9100
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
          #    - job_name: fail2ban_exporter
          #      static_configs:
          #        - targets:
          #            - fail2ban-exporter:9191
          #      relabel_configs:
          #        - source_labels:
          #            - __address__
          #          regex: .*
          #          target_label: instance
          #          replacement: homelab-oci03
    - job_name: podman_exporter
      static_configs:
        - targets:
            - 10.0.0.26:9882
      metrics_path: /metrics
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
    - job_name: uptime
      scheme: http
      metrics_path: /metrics
      static_configs:
        - targets:
            - 100.71.136.91:3001
      # Only needed if authentication is enabled (default)
      basic_auth:
        username: ENC[AES256_GCM,data:pHB6/NEYRQ==,iv:hD2/beFDfBUdSwS8nHO9wmDCZNfbKSuTP/g9NHdt+1A=,tag:ny3KhH6cJAh+wKrWNT+sJA==,type:str]
        password: ENC[AES256_GCM,data:264nZ60AX0t45OTS64xxUTY1dmwgmIssJQzBi+lU1HekHrq0plgpR22/baI=,iv:1/ZRf0eBISVge3KLgvgP9aqORk1hgutlmVikcxI1nnc=,tag:fcFVcG71qmTpfsVflWdk6g==,type:str]
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
    - job_name: crowdsec
      static_configs:
        - targets:
            - homelab-oci03.tailebee.ts.net:6060
            - homelab-oci03.tailebee.ts.net:60601
      metrics_path: /metrics
      relabel_configs:
        - source_labels:
            - __address__
          regex: .*
          target_label: instance
          replacement: homelab-oci03
#  - job_name: 'monika_exporter'
#    static_configs:
#      - targets: ['10.0.0.14:3001']
#    metrics_path: '/metrics'
#    relabel_configs:
#    - source_labels: [__address__]
#      regex: '.*'
#      target_label: instance
#      replacement: 'homelab-oci03'
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aE9TWkdqSG84b0NIZFJi
            L0hBUEJkdlRlQk13SitKcE9vUVlpK0lUQ2owCjRybkNwd01FMlV2RC9HbDBsRmtn
            UzRYS2Vub1ZlNGV4QzVSOUZsb2M4YUkKLS0tIDR0TjhCaDFvRE1Kb0pZbDljSjRY
            UjJVanJRclp0dkk0cTljZzNnYmZsNmcKQjrXlY0avzLZ90MsPEAZe38FmLb/Ra6w
            whQJ2pZAuYEnUIXVO9Qcsvcq7Z7891XIi7pfVgBED7o9QD0VshWsxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T17:28:36Z"
    mac: ENC[AES256_GCM,data:O8s+ezLYppv3Cr8eRXtPU8IRYG4F3Jt0oae/ZaZAeQxLuYNPaxCSENjtXETlFOxYvhlmf0gn8az7olfSWE2lKKZwSUj9mqrAvsS0UgzdscfBfZQgdVQ6oTwTQB/S5qjHU4i8vqrf9DkNNpWpwcyDKjLBAgdzXD69WqHq1C4tAUo=,iv:HqyLpodmXNsAlUGUIkUw74GIL3kmgZ1q/YG4sVyqxyw=,tag:MOiUMjcCKVpO8BoEhmDzAg==,type:str]
    pgp: []
    encrypted_regex: ^(basic_auth)$
    version: 3.9.1
