global:
  scrape_interval: 60s

  external_labels:
    origin_prometheus: homelab-oci03

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 60s
    static_configs:
      - targets: ['10.0.0.26:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: 'homelab-oci03'

  - job_name: 'fail2ban_exporter'
    static_configs:
      - targets: ['fail2ban-exporter:9191']
    relabel_configs:
    - source_labels: [__address__]
      regex: '.*'
      target_label: instance
      replacement: 'homelab-oci03'

#  - job_name: 'monika_exporter'
#    static_configs:
#      - targets: ['10.0.0.14:3001']
#    metrics_path: '/metrics'
#    relabel_configs:
#    - source_labels: [__address__]
#      regex: '.*'
#      target_label: instance
#      replacement: 'homelab-oci03'
