version: "3.8"

services:
  # postgres:
  #   image: postgres:alpine
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     start_period: 15s
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres

  server:
    image: amruthpillai/reactive-resume:server-latest
    container_name: rx_resume-server
    restart: always
    ports:
      - 3100:3100
    # depends_on:
    #   - postgres
    environment:
      - PUBLIC_URL=http://localhost:3000
      - PUBLIC_SERVER_URL=http://localhost:3100
      - POSTGRES_DB=${PG_DB_DATABASE}
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_HOST=${PG_DB_HOST}
      - POSTGRES_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY_TIME=604800

  client:
    image: amruthpillai/reactive-resume:client-latest
    restart: always
    container_name: rx_resume-client
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=http://localhost:3000
      - PUBLIC_SERVER_URL=http://localhost:3100

# volumes:
#   pgdata: