---
version: '3.3'
services:
  zabbix-agent:
    image: 'zabbix/zabbix-agent2:ol-latest'
    container_name: zabbix-agent2
    ports:
      - '10050:10050'
#      - '10051:10051'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
      mode: global
    environment:
      - ZBX_HOSTNAME=homelab-oci03
#      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - ZBX_PASSIVESERVERS=${ZBX_PASSIVESERVERS}
#      - ZBX_ACTIVESERVERS=${ZBX_ACTIVESERVERS}
    privileged: true
    pid: host
    stop_grace_period: 5s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    labels:
      com.zabbix.description: Zabbix agent2
      com.zabbix.company: Zabbix LLC
      com.zabbix.component: zabbix-agentd
      com.zabbix.os: "oracle linux"
    restart: unless-stopped
