version: '3.3'
services:
    speedtest:
        container_name: speedtest
        image: henrywhitaker3/speedtest-tracker
        ports:
            - 8765:80
        volumes:
            - ./speedtest-tracker/config:/config
        environment:
            - TZ=America/New_York
            - PGID=1000
            - PUID=1000
            - OOKLA_EULA_GDPR=true
            - SLACK_WEBHOOK=${SLACK_APP_URL}
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped
