version: "3"
services:
  healthchecks:
    image: docker.io/healthchecks/healthchecks:v3.4
    restart: unless-stopped
    container_name: healthchecks
    environment:
      - INTEGRATIONS_ALLOW_PRIVATE_IPS=True
      - DB=postgres
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - DB_USER=${DB_USER}
      - ADMINS=${ADMIN_EMAIL}
      - DEFAULT_FROM_EMAIL=healthchecks@timmybtech.com
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PORT=465
      - EMAIL_USE_SSL=False
      - EMAIL_USE_TLS=True
      - PROMETHEUS_ENABLED=True
      - SITE_NAME=HomelabChecks
      - SITE_ROOT=https://healthchecks.local.timmybtech.com
      - SECRET_KEY=${SECRET_KEY}
      -  #UWSGI_DISABLE_LOGGING=1 # Uncomment to disable logging
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
    labels:
      io.containers.autoupdate: "registry" # for use with podman
    ports:
      - "8000:8000"
