http:
    routers:
        loki:
            rule: ENC[AES256_GCM,data:FBnGMK34tciieDqkb56KvFn6dWZEyitYPvcX,iv:aR+bwttaohUdtZ458CAU7twp71J7UiZdqGbqy/wM2oc=,tag:Eb1QqVN3KfqR+AdTGlon1A==,type:str]
            service: ENC[AES256_GCM,data:K+bkPA==,iv:YSRa3mWK9M37yKNGl2Op85dG7AjZJ4UCyuDZeC32zy4=,tag:hoode/wc68XO+twz0Q+TOA==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:97RWNnPKvMKv,iv:hE239puSBPYIUj/mFQOuZ+trbLzIxp4YSoCVqc4rPAo=,tag:eKpdATl1uG80FZuoXEttDg==,type:str]
        prometheus:
            rule: ENC[AES256_GCM,data:tLftdEk28xiu3tW/Ukh2ZXVj0p0JJMyf7pwOZESL585s,iv:pnUPqAwhUORgDcTWWexPBdRjlye4/rb30zmG90bEi2k=,tag:wCIk/lZfpAr1h4kdV9RiMA==,type:str]
            service: ENC[AES256_GCM,data:BFF3rfQQEkXwuQ==,iv:LbBtQelu3YOIoppUEb4V1SqZiAQIMuGBBb4siBhYDhA=,tag:4UH5lmlsFUwvhFz9aT4oXQ==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:k5fDrZqZoAzJ,iv:kzsrzCMIb2E54mfzF0rpN5eCdPBaCW6M6qCorsirai8=,tag:/OhjvcKpcmMuheHwGnBu/w==,type:str]
        it-tools:
            rule: ENC[AES256_GCM,data:0/v8wCFw9kToFkRXH+oJGWIqRuvCtxSnOpYqZaIIpA==,iv:QO8im1zlWwfALFNeM3LHbCMowkPyMytCEDozNiqktqA=,tag:9ntMu1wCvo8Zom4se0RzkQ==,type:str]
            service: ENC[AES256_GCM,data:+Ux5vBqJWD4=,iv:KoKgApPyx3tTemz4vK/KVDKmMhcyiLFBbLtbbR/Kdh8=,tag:sec/u1z+/k1hh6wSkWkZQQ==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:Zu7rjr62JMFP,iv:RPYEVXaloJerbntTBcCHTUtV2sQFwmZdIa6VK1E8Ih4=,tag:T8UwRPss/m9FnUxiQeuXRQ==,type:str]
        linkace:
            rule: ENC[AES256_GCM,data:fpPeuAzdAY3WiWZMuxFkmfH6Tz9QNz45llX4MzlZ,iv:2qXfUc7lEf5p5+U+t9/f4UWbsn/F0mnmpb7aftuvr3g=,tag:FAIRwuRkGkXeG/bH4DiBEA==,type:str]
            service: ENC[AES256_GCM,data:gMjktmHCag==,iv:+WPzbYfUhl1l0TCXSA8CkghH2wCQylJ/QCd6hlDsK4Y=,tag:M0cNbVxcm61B2Lf8L2Nfig==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:hER6zabu8YMU,iv:jTs9I3pn758I9JErjDp97yzMvdfYMhddA8TZOycNqOk=,tag:6UKGn5BE+K+oYlPglBLdjA==,type:str]
        hass:
            rule: ENC[AES256_GCM,data:9bQft35p1dfAtRY4A9Y2EFwFuiQ4e8dCqZYI,iv:fVD6e1RpYn9T0Q+9v2Mj8X3FZlaD86DGGgLn5p4ehNw=,tag:GJzSk1qk7OIpCLWXq9S/Bw==,type:str]
            service: ENC[AES256_GCM,data:bbIn+Q==,iv:5EeaNcCjRxaF8UiseFmRJll7v4UgHsHcjnAevgbQX3c=,tag:yKwkA1igQCy3YxUOBIqgJw==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:YPmTyw98jAR6,iv:QjRHJaXS7ixPUNhu+bBx/cTmYvK9++RQPt3p5GyytA4=,tag:YFOUKIIrmdrhDKoyJqtxXw==,type:str]
        wyl:
            rule: ENC[AES256_GCM,data:ORR7CFfZ0TZLbQK3krePWlYqonF7UjmBm6Y=,iv:F9oTxBlPaHjvhk86Fl6IDGKoka4lDpquVnK/E2nnqo8=,tag:Ade/3QqpMWLvIQY7PYirXA==,type:str]
            service: ENC[AES256_GCM,data:si1H,iv:Jo9BZbXCveFv99Yv0OK6oP71r8IF8HX2NxRkx3Ab+vw=,tag:RIkCF+3UfRH28WdPOpRx2w==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:PfOzqzptSFuW,iv:hAiCIbugX0QOXfv17//UBDgQ+GMrB0yDzF3BWQrSjdk=,tag:FGCGhMjGN49bVo9/DHl62g==,type:str]
        syncthing:
            rule: ENC[AES256_GCM,data:XUpCx9UnvxPBni/dlMOZcJKLNEx5gf06NsRTxMtDoAc=,iv:4q0Zw81QczCS7E9qxfOGDqqNDkY+G3VqfkBCplGGusA=,tag:Nr9Fgr321NEPfQfPgufIDw==,type:str]
            service: ENC[AES256_GCM,data:5UgSlD5kmiqd,iv:CyUBNohL/GEz+UiqY2Ke5MrPw9q011aorS83/U5DLBM=,tag:qwrP3q8A3MpPFbdsUx/8Qw==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:JGWo7fs2xvG3,iv:HhMbbbgdyyyMgQxBFM4fNMaWgGtyvMdnSUbLgK80hYY=,tag:CocWT3HpuPq78jFtXJcjEg==,type:str]
        uptime-kuma:
            rule: ENC[AES256_GCM,data:PZRwzkMvblOOZsk4Ft4FI78MWbP4fnqSfI7q6mFBRvfO5g==,iv:mbemdkj8Ux2VqO/zYGBu8jWlrIIBNSdk33v8hW8UR2k=,tag:IEefqII5LIA1U8TVnD6fdg==,type:str]
            service: ENC[AES256_GCM,data:6wBjplKqiwokfNE=,iv:8tr1Vzo73yaRMnVmxgQMFnLIzsfBQ9/I4IVJBG7tK+8=,tag:BMq+wy9BgNa15gOWZ9pCkQ==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:H4ul2wjxAuLK,iv:BcP2lLOroPYt20i4wRAbOxuyRV24TdQX0ZEIOvw9bmY=,tag:q5OBtWt4XCrd0RjV6k+Srg==,type:str]
        adguard:
            rule: ENC[AES256_GCM,data:AuNVUzTl/bHfxsdtsTXVvhnxurOlCq1ZJEG9gn8D,iv:nWHKFbH0y/TS3G6fZAIM/+9r4Va2Eof3h03mvFnOugs=,tag:83gYBXvR0xB5jQXwdPVbVQ==,type:str]
            service: ENC[AES256_GCM,data:0W+2209s6Q==,iv:t8S1oBUlt5v4arvNbRyeTtJDViOrePVCcf27NbyuvTY=,tag:VTAFx17JdzNKCw2GYHFN+Q==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:c1LMBlIXhYEd,iv:uCxjKYoWBgoCJPYxmexYew6MBQHEfLe+KEgiDQzNEZw=,tag:u6NtFYwj0YHUW7IFuNKZ/g==,type:str]
        adguard2:
            rule: ENC[AES256_GCM,data:MkcGv9OKab5oWp7kGTSkTx6bPENp1QDQx9+e2ZGwkg==,iv:ndZoT34FdVpnPFh5OMvZs8QD5k6u7GrHQD+xYxllUsg=,tag:BrnKCbfDI86lG3GM5LfUDA==,type:str]
            service: ENC[AES256_GCM,data:zJrWxXqtxYo=,iv:7v3QxNXZwFI0oSFx4FPofTpE9xdRy4CXEMz/ch6Kq20=,tag:n2HOYuVDGf30lTGIwMmtAQ==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:ZzXQYmXkOePC,iv:t3NCqEWA9csB7N0vXSHp4yR5BD9K7JfcMHtuqiKndKE=,tag:Ms2M6ZOVU4+JAdhHduoBgQ==,type:str]
        gotify:
            rule: ENC[AES256_GCM,data:iYAcE3OhAoT2tILQOskeY/+P5z+dIjyJpFisfTU=,iv:bRehpc1K8FwsXs6SZUIuI/mcR0J6GKCFmU47eI3o1MI=,tag:GzpRHn85j+9mUBfSlL4xgA==,type:str]
            service: ENC[AES256_GCM,data:XIMIfBj1,iv:tV6a/5cLGMRtmLmt6IcKAqPjYNU/m/W7YZAnT6L4Yns=,tag:muegx+Wkcpiw9TtRbBhHJg==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:aBNF6BaIzx+y,iv:8qCSL3O7a+bJMz/FIPhBP4bFQ1A5Xz6eUEvUj26NGq0=,tag:0Ql+Bn7Svv7Iq5flPpm+AA==,type:str]
        healthchecks:
            rule: ENC[AES256_GCM,data:O5KW7cocCX8Ijcb+mPFGlkCf7qOeADiE+C5T+a5IH6fsTTs=,iv:6EFqPz3jgianHA7587FVaygxReq2PHErY1QQlsZJjRU=,tag:KGkvYPpo7pfWgjfwlfJ/tw==,type:str]
            service: ENC[AES256_GCM,data:nFmax1B3nTQY+RoW,iv:sIccFNxZeHydhPUUlIPWZzD7k+FgoIf33jPbatvfDCI=,tag:MpBf4eBsNGA9dWWdRwYJjQ==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:tn2fQ/T//hfQ,iv:W75RltOKm1MIrS3zzO6n0iOaUwGyXozWldyq2B8UlYk=,tag:82SIeTn/n7s4tS9NZ+aX+Q==,type:str]
        pgweb:
            rule: ENC[AES256_GCM,data:Vpjz8XTmFej2F4zGpEzyBn28Apm4rlpGqdhkHA==,iv:MlWPM0V5wq8eQjNvuhpu2d7e68+N9dwALnU99dNPtmU=,tag:BXLP8Mu5p9YV0rvRXNiw2w==,type:str]
            service: ENC[AES256_GCM,data:oEh21fA=,iv:tkhSIAYas/IuP4G7yqfk5JDTQjkL/uwkIdPApd64oac=,tag:YQilf0kn4el41ewnHU2LtA==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:Hx9QV1LnC4cT,iv:u5IoLbWMIcN9PfyVcJb3B16DS8s1U8zGMIGrWW4AZLs=,tag:3HExBs2yCtnkNCu6tjN4hA==,type:str]
        pgweb2:
            rule: ENC[AES256_GCM,data:9idoSermouRT7vIyfJcdZl5NnTaC/9BRwd9NZ9I=,iv:LpYJM9hJZHUSSaSwuicCzlZm4YgKjqg2yTDad/A0pMg=,tag:ZWcEnMH/bz9RvvILCBgqBw==,type:str]
            service: ENC[AES256_GCM,data:JMQaaoq/,iv:pxnSpp6jsH0rR32yTXrDSfoIpENDSoYVbvKc0dnWqoo=,tag:1c9fKnnmFWJl+KnHy1IHUw==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:SkfiD9DCI0h1,iv:5gxxXWVBbQErD9sB3NNIfm037e1rFdHx1B9ljibOPpI=,tag:8kgjWF/C7Rnu33JT18CiUA==,type:str]
        nas:
            rule: ENC[AES256_GCM,data:vwPJLPohdimCwFhCkAMg1aixmNoNAqj1L50=,iv:y+2ZWA8ujDR6kkhX8CS+1NNN8ca8I1epIKY22PGTDLo=,tag:+GbG0kLanMOXJ6HHbUQsDg==,type:str]
            service: ENC[AES256_GCM,data:xgYk,iv:hpUPxHrmxqBSZne/5Z+fLND9RK91P/ikN6sTnGlURa8=,tag:YGdlsAC059DApKQkU64Qjw==,type:str]
            entrypoints:
                - ENC[AES256_GCM,data:enGpurS1KSZG,iv:CQWbDaGzehYw5d6RGJjZoHWHI74ST3/hXkODrhpYGg8=,tag:Tcl5gdJy8ZBKF5rG4QgHQA==,type:str]
            tls: {}
        pve:
            rule: ENC[AES256_GCM,data:QPr6aHGjozTKSq0rUZ8Az+KfQ4SomJlKwHg=,iv:yxqrIQPL088qjGaBdrAHIwHtLXbXXb5iZXfxQQe07Tw=,tag:z65APbnSxuwy9kNj7FFPlA==,type:str]
            service: ENC[AES256_GCM,data:3rkL,iv:I7ai1ELS46VCwNRHDN+oVVl+/p6f1m24XmX8MUTXtec=,tag:7SGpAiDyjj+CciGV9UVhlQ==,type:str]
            entryPoints:
                - ENC[AES256_GCM,data:V5FtBOoaN5sv,iv:Ob0dqk+8x44RgdlKra2pQqjqiBHw/Mx26ZWrj4/XMaE=,tag:0FZxJ9BlrMTvFAtg0FYCAA==,type:str]
            tls: {}
    services:
        loki:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:4ueFQwb3xzOC7zWsvykdXkC3GC0GbQWE63Q=,iv:ZtQI8bm9O8AbP+qAQMOzlvPvPZpsLwxDwA47GzpB6uI=,tag:EFBrmZLMEbZQjrMdCc6Q2Q==,type:str]
        prometheus:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:gG91yEW62bF0S8HRaEBctuOxcp8ykDRiKxY=,iv:8y4p3cjHUYtzRPz8EW/TN2PTNhLaykSEnSym04acL6Q=,tag:zIpTsDCihyV3c0hkTVTptA==,type:str]
        it-tools:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:yOQR37NgXhrRH89Ibnr/V1dEnKCoo4oVGQ==,iv:DPQsIA3eWhT8BarF0rsO1RyDDJnxnnEm30dvw0IXBmQ=,tag:AStqJuExasslvyFrKNCKBQ==,type:str]
        linkace:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:FsepjpNbtKY4+TM+zTtUUQGfI+95dXNiyQ==,iv:GdCxi6D2EIMfhTraAlO9FfAuU/Ry7MjWX4Sn40LSjWw=,tag:0o5w1u434a5f9N96EmBt/A==,type:str]
        hass:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:VArZw3ESR+xJ5+gGZGKboIfuDoNb4BGSoTU=,iv:1NB6DstKCo1rI0tMHvzAYXr1ZGn8CEjJvhvmFtOrJ4w=,tag:Y7rCF625wy6RnTZkbXfxXQ==,type:str]
        wyl:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:jAzVqmO4PF1B3D/ZuUXKaULFlmx/ecWvAMY=,iv:4VyOCm+Z7jANzUg7AVJajsQYpXko0tIjfajowB0idfI=,tag:DRMjxB/rAVm6sYZbPH17Ow==,type:str]
        syncthing:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:i14t3OlU92+xz4BJcHPzE7glSLqpx6jvAoc=,iv:4sFUy80e3A2e73QfRnoK6T2wC9SdX68L2sUxAgYkVVM=,tag:DSoXYALCcQErQ8t/6ieB8w==,type:str]
        uptime-kuma:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:mdMfI6pYghIyHHSk7wOFOeA95ygkhMEFalZ9Fp8VQ4rhl74=,iv:9V5B28p5Qcxyf0CNN9Rpe8/ftLdLK7lSk9rdiH7MH74=,tag:scpcZBL++tvq6A+Y7gg2xg==,type:str]
        adguard:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:X9r/cWwSjkgFYqbQzh4+RS+DmKYU,iv:PTifemYD2a/7Up0SZdmrrkbQ7nMaWx3x/SYapr5YOdQ=,tag:qNmQNzGFu3TumD/VPf4IMQ==,type:str]
        adguard2:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:H8MGC1PHAuEDz5I8u0/SmoJwoOk=,iv:wfIaO8NsrpLJVP4snAF5/+Dh652uMQsURiNLfAFaDKs=,tag:WWmZ8ncu3dPn7Y9HlGriug==,type:str]
        gotify:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:C+jgAResiplBziEd6czs0i565/dh9dR3ow==,iv:EgxrayJl1b0zAyMYsKXWQ/MJ1FSH6Ww+d/pAsfaMGUM=,tag:vz/VIDztmdS+k2WYChEQMQ==,type:str]
        healthchecks:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:OFPhzBrX8eXwGsBGodwtnVKwUVepb5sHNQ==,iv:WGDMAMnYuSJPhnCqtI3Y7EEQA5mLrI+76Ny9p17xJE0=,tag:HncBU2I3JV1uv1dt8TUKOQ==,type:str]
        pgweb:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:RZE9QprsGGk3z9P4FT7fzArme8YSDCZHBlLf,iv:TGE5fDMfzSkK9hnk21XIj5dg7JvO3Te9dsMomgQfyso=,tag:w0vteaekTLTtQFOAduQjmA==,type:str]
        pgweb2:
            loadBalancer:
                servers:
                    - url: ENC[AES256_GCM,data:j9XbBmVoOxG8RAqc6u93Muwxm8GLaWlL/UKY+IPfH1u0Yl0=,iv:3+If/nsAPhyiifsdw2/knpkmxO6Gosbgt0aYP/lNlLE=,tag:vFd8JISk9/aMmOOGvHxmWA==,type:str]
        nas:
            loadBalancer:
                passHostHeader: ENC[AES256_GCM,data:EFP1cg==,iv:pTEkMx7ww4zylzZvv7J8Q6VJUu8LfhEmoFUBJr7eCFM=,tag:pI1GOrMvmQBEND+Ta1FjfA==,type:bool]
                serversTransport: ENC[AES256_GCM,data:ma9c,iv:hwWWbbrRLYpCojA8pj3qPT6r7k1j4oKFx523+jjOb6s=,tag:3+1BcL+WqHHktJwKlra8SQ==,type:str]
                servers:
                    - url: ENC[AES256_GCM,data:GFkNIedyNBFPu8UIXtVqaQ5TX7/ts38RjwI=,iv:jCEC0eissdiy432nfgS/sj3lTHRql3dndHnzo406PQQ=,tag:Cv0O/OReJyvO9yhl0AYOQg==,type:str]
        pve:
            loadBalancer:
                passHostHeader: ENC[AES256_GCM,data:kOmXdw==,iv:hYMcd6/jfco0AJoCtvvLlFmz3gCNlzgBy+Ugn/ogHGU=,tag:7D1Y6V7BOiHXk+hObHuBSw==,type:bool]
                serversTransport: ENC[AES256_GCM,data:Vhcx,iv:jFO7b7HMlcrg6iAOofo8IR86cDgfKL3dI1QAh0k7Lg0=,tag:Ja0n3TSPo+UXiG66v/2XkA==,type:str]
                servers:
                    - url: ENC[AES256_GCM,data:z6izDfVPby6OzK/UNYBU5l3xnnHBsd5BD0Mv,iv:PVPeEJofHUxOfm12MajXjN9nodDZCaLuxWhoKnFHumk=,tag:9gTR9g6zua+8B3+6jXjnnw==,type:str]
    serversTransports:
        pve:
            insecureSkipVerify: ENC[AES256_GCM,data:6igm0A==,iv:+XPS9xF1DA/z4S49DYSFdPaWlewTE/Klth2T5V+4N/s=,tag:uBAOCvW+vnYJKaZS5LwVbg==,type:bool]
        nas:
            insecureSkipVerify: ENC[AES256_GCM,data:rjErVw==,iv:WQcN+cTlvTrb5+iwLTDbIVAfQQneZXl8tunQenZDWXc=,tag:h5VyXpPAy72Ki+MmMs9fHw==,type:bool]
    middlewares: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WjR0Z0xiZy9zL2g3SE51
            TnVSWEdtcnVsYjRReXdGM1RhUjBDdXErYlF3CjJuemRwNVVnMXBOSkRBMFA5OXpV
            QXFNSmZJaVJjTUpBbXFxc216aDZpTkEKLS0tIHVXOFl2Q3lldExOUVh2eTBUbDFr
            bmtGVWJvYWpOcXYwSjlJNWhqd1NNY3MKkLW247YjFCl4sIh1jaYrIdVqhnmyCAUN
            Rb8s4EAJN44eIow3Z58BOKF2kjpJ2pK3YU5uK67wdOjzijIsNkwPVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-08T15:48:39Z"
    mac: ENC[AES256_GCM,data:Us/pmPJlIxBhgEr+lXzXxze43p6mrK9o5R+yMA0FE4RD4GktM6CLoStu2oI7ooSZhOoaFka2ycunXsj8SMpM+QmHtq3VdxJGbW3M8EDJ8ivdgM1HUxOyl4wNjFzA9PSguc3b2aXev5j3Wv9MEW7Hd3eoNYB0EBteZOJmUNMdF6E=,iv:MSe97ElAIMNvfMyFZNunkIjCyAtsB1a5aev+cP1rEX8=,tag:hU7uBa/Ls+gWpYrAqsVDHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
