---
version: "3.1"

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - /home/tbryant/uptime-kuma/data:/app/data
#    ports:
#      - 3001:3001
    restart: unless-stopped
#    security_opt:
#      - no-new-privileges:true
    network_mode: 'host'
    labels:
      io.containers.autoupdate: "registry"
