# Deployed in same compose file as Gotify server
version: '3.3'
services:
  alertmanager-to-gotify:
    container_name: alertmanager-to-gotify
    # image: a1kmm/alertmanager-to-gotify
    ## Build from source repo instead of using the image
    ## git clone https://gitlab.com/A1kmm/alertmanager-to-gotify.git
    build: ./alertmanager-to-gotify
    restart: unless-stopped
    ports:
      - 8435:8435
    environment:
      - GOTIFY_TOKEN=${GOTIFY_TOKEN}
      - GOTIFY_MESSAGE_ENDPOINT=http://gotify/message
    links:
        - gotify
