tunnel: ENC[AES256_GCM,data:YOL/71NjeAOMP6sa52SGvuBZSuqSOdpSsCo/yj6byGYDOx3I,iv:50wL4/PXlpPg+7MIvalcgiRsSA3R68+8/ewIqm2Dhvs=,tag:0bvyEzyXwWLD9KK0k2ycTA==,type:str]
credentials-file: ENC[AES256_GCM,data:XmDfCcBdoijeGBU52AnKYxYHMjkv3O2kQyH0g7g+Goz+tMQfeCDP90Hzl0Egcd0WYzc6TsFdRsfSDg==,iv:MBKd5Kmjj/0HNlO8+OaEKTmZ+BBQ/rE4Asfi4MBMsi0=,tag:62UMvbXa+RrnXXQxw7HByA==,type:str]
ingress:
    - hostname: ENC[AES256_GCM,data:J26w9EGr6qNklFVPwtz6J2k5v3HXbA==,iv:AnmrrlrNfKp6JUER/9wA4qrt6JPKoITMXYoAQugZ8Iw=,tag:dkx0/0jtWMLhzSVi0lRPSQ==,type:str]
      service: ENC[AES256_GCM,data:uLNE6cVbXe2zCPN2gHDgU3j1JNZDCobn4LU=,iv:qv4el/uevfPUokxRsPusgYpGLPMWL7JqbS4qnRu/cPc=,tag:7kCl/LQiHf1jFHaoqem8ww==,type:str]
    - hostname: ENC[AES256_GCM,data:nH5J4+Ti2wfmbG5SINt4nYIcKW/aV7YFX79+,iv:09uGcOkGAia0aA4m6SjnxBesbR2cCZRYCY2N91QcExo=,tag:1pusTjXjZ31JaNnKjH120A==,type:str]
      service: ENC[AES256_GCM,data:ZAWpCbDLuX2/ZcCe1MQ7YtU5aR7SBt1oeF8=,iv:Bue16HFvUyoQkZSVffl5/met8kWegI3p28h40s7w03w=,tag:ge3idl5paounPlEWKMX7SA==,type:str]
    - service: ENC[AES256_GCM,data:UGQtCovSg+SKO6GGcDmr,iv:g0ArzL5K3e0f5FI9+qvTp6cv3CBXbgKljLT39rPotjw=,tag:yo6OyXlyyEhitSeoRUSh3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cW5NaXpJTlBiV001dXNF
            b3VzZS9sOEg1VWdYL01iVVpyNTZJREM0L1V3CjlDandMbDl0bE1oQm8xMzRQTzBk
            K0dPdi8vRitOdFlmcGN4MFZwWmZ0dWMKLS0tIGs3bFRpM3NFMk94OGl4K1IxR254
            MEhyS1h2UG1YMlJDU1p6OENINWtTVUEKjNzBGNT9SnVjykw+zS7T6BrsxZY07rmc
            cuqEpgh4bovlei3GXZCXu6j/G3SmU1gj9xnx8zu6m84H9IW1D5znbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T22:19:19Z"
    mac: ENC[AES256_GCM,data:iRkUbltqAM3ABYYzQ29Xe+fDmHJyhVwg8cobacTURln/CAhJFZE6tD835Gp7USkyDVjPct7D9xGvs+xUohFLjYk7Ook1/kYfH5E8HncaYT2C2DoxpE/Z6xfg69Ilm521eLkWy39cuVdGem2MrRBs9/mrc+9mq9br6iYugblkiTU=,iv:n8uvXJUgeYlN+FLexIxg053tpGr9O+3Fw8fDYQZl/0M=,tag:g0aW0AJVyB9G/uZM/9jiEA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
