tunnel: ENC[AES256_GCM,data:wfS6NtY38msJVPvZEDOw4OG5bTqiPrK4mW4Lz6w2tOyWwCzg,iv:uTYI/D+gZIk/mET58ddZ6l4Z3hNA2DL8x9i1iKri7t0=,tag:eVoJWxbnrB+Ow+iewGDj5A==,type:str]
credentials-file: ENC[AES256_GCM,data:vqictRQisej5yXCuGlb/EyGh0Fczn6XR2lUFNMssUfSZEVqBS5+1FFw1rH/bhktn1Nq3HcIivYkYJw==,iv:t9qdOyxyxb3n9x2nFf68741Q9RFyzw7bB520UFw+7FM=,tag:75KC3NxJN3AkT4LHaDb4yw==,type:str]
ingress:
    - ENC[AES256_GCM,data:kAmbRK2CLUtTuQgvM4BGpClHDVoOl5JoqudpalcPHMZh83OBpY8=,iv:wz2vIHESvDsF86h/DWArrLBqzxY3TJloAc7rUYfqBPg=,tag:GRgGpXRtQ7PaSmnk+f8Lvg==,type:comment]
    - ENC[AES256_GCM,data:aXOfJ1tSM/cmLlWh/DZEz6OVu8LFxxRmOn8Fu+uDiBiehryt3+jemTY=,iv:kpGCd4QAWMtRGkThF1gTStCDhTpphhfiMk18aFoJSc4=,tag:W9FdfxeiangoOOJcWtOeSQ==,type:comment]
    - hostname: ENC[AES256_GCM,data:M8magbHA733F2PqOw0BFAygvsnGI/UuVffIc,iv:XLafZIpOnucRpWok3GeUC+r1X4LXE5uhR61hpspo7RU=,tag:sVRjFylgg5bKJw10T1HIOw==,type:str]
      service: ENC[AES256_GCM,data:F7W5CzXKLKGaAEgWHZubumSLcr+VZmb7HwM=,iv:wn80qgFw4CpjB5fL1AnTcdZgdB51urefjbB4iFvI1b8=,tag:y/T/zGBttTOiV3HOiN2Kiw==,type:str]
    - service: ENC[AES256_GCM,data:ckvrtxmLK9mhWt1JTE57,iv:bgHwSvBgUI1rK3nmG8yymFMETTKNSNr0jz4kLuSrVbk=,tag:5DfyA9NDgEi3sfmM2lxWDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z3JGUGlLSzVBRG1FRk45
            OTlJM1A3SmdPYmllTlF2a0lUODFjQjJzNFhjCm01SHdCVnlLV3V3K2NvMStIM1FZ
            NVFXVjNROENHcmh2YXM1L0pjT21OTDAKLS0tIGEydUk2d1Zqa1FHQXFSeWJrVUZt
            cVV4UHo4YzJnZk9TNW9HY1JpeEhMN1UKKRsHYO4w0KYf4OkCifieRj1/HNjrsPU1
            bzL34cdNDCkA57HUt+5KqnJ7cq5dDeZD21OELeb+1MsyCv1LaGnBdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-15T15:00:47Z"
    mac: ENC[AES256_GCM,data:cGCEp/rwrJahYmVJRgp9+Gs6ToZDXGB6I8idjXJZhyhPoN+CtAFluS7MAqHb7cyY5L6ByME8y2gNni47rdGaVrIVZmsWMn+d80XFq8zo31kzH0M3WrzMgxDrYh28J1oJFHfhrYLhcBNkYEsRUdNq5jmUFhjHRtA/JE7lBs99c2k=,iv:1DRfRmAzVY+xGril4Q3FlPi1i8AFZrZFOnNLJblAbRY=,tag:+bFbyfqink75Ep4vX9mwjQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
