tunnel: ENC[AES256_GCM,data:4xOOWEcoQvzCttFtDcIfO3lPcDYs5oWrW/Nio0XCLWkKLBUb,iv:0PWGcO1h8mPSL6rIgznmIUWUuNNIDlteLW3pv7X3040=,tag:U2BYBn5DKr5NsKCNSJDNUg==,type:str]
credentials-file: ENC[AES256_GCM,data:44D64hY+QSRprIxS7YyViGVODndOymJ60ERZi3yPw3m7TMelbsmW3n8Z1y9co+mq56+VDx4/lT0x5A==,iv:M0i5+EEhZTFxKniY42EUxhoS44YdzL1E6JAOdWffoB4=,tag:L3BSQ6W3B1piu7mwucn45g==,type:str]
ingress:
    - hostname: ENC[AES256_GCM,data:uCBW0QO3lzUMgVcjOGKDKNI62QHpLA==,iv:Lyw/Dvpy9YLneLdBAlkRlvJUtLDOlEtp5bv/j1F4mss=,tag:fy4yrMhRMYpfVH6iCzQiMA==,type:str]
      service: ENC[AES256_GCM,data:4jhJVbLO/p7QZK+BGgR9y+Qz2TOGGteqIjc=,iv:2SbVlecwMDdTLgWyqIwe+HFY4u2ymXrVis30xiK7HN0=,tag:E+UXiLIuLRr7h8aSm/HkAA==,type:str]
    - hostname: ENC[AES256_GCM,data:HuLXZAccAjIA8a5j4CT12RCIBltGIroa+XkJ,iv:MZliF5fKiS6ji+AfZRXqP2eO1Whtr/PXa/2UrYjbaBk=,tag:2h0BHbtztuvJRiQ68NpY5Q==,type:str]
      service: ENC[AES256_GCM,data:sHUddYkv3Ti3tnsV+s64Pttbak5iEsu1f9A=,iv:qKyCYYWSHa3EO1ZgYh7y4TbrLy4s+e342lr9LkDIDNU=,tag:7Gr8aOUm113wIbLKtVMm4g==,type:str]
    - service: ENC[AES256_GCM,data:WKzyA5eZmaFsdwYS2fqY,iv:ILCNr2Ka+epdMtWQ8Lgh4S0WUWE4hdZtsHfGKIMWFcQ=,tag:SQPJAeE9Iz6WR+b4U5VitQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuL3JYbUNwY04xTWdXaXJl
            cCt5NHU5bDRqZHd1R0tJb0tUUXM3aTlPQTNFCnFDYXJib1o0L2F4K1hjK3hOeTIy
            eE1weWIzajZkNCtrai9jMDJVRXNkeVkKLS0tIE5EVTNhRmRKNG02UHpsMWxRdzRT
            WHAxV1RwM215dUtkMVlHK0g0VHpHWHMK63TcsubdOHUVEy8aRhucc6zmd+WNvD7x
            oz3Lw4jyoILLyDnDHbC4wNSqqsCMVW+FA30iGn6u05kJQbvik0VEzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T21:08:18Z"
    mac: ENC[AES256_GCM,data:t0YSeZ5DmP5K0XGqM63Jf3HHNKsvGcMl2KOg8S06iW5hbIntrdpZdintRNVyo5xv/tPWvLuHnlZaApPIKF7Wl4BnyC7hLt2M3nnAQRuJFB6PdjvlFKwOlrV2bYh9MLuPbfsuFzaW2e3WfSc9w3rTkednKjK9KMjmAwnZE0UblB4=,iv:ezt6CMoKk4tJEirSRaGkwgiIuWDWWfTVlsMnBEYRTEk=,tag:QZUnZIWODdxP4Lr7eLhbKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
