tunnel: ENC[AES256_GCM,data:EXVvkpaITCp0RsyubQFed8rQOhB1dRepzWbSkuuRYmKoSJkp,iv:lTsccUMpD24MInm67khD9NlVunITK0eSLXzzQetO8KY=,tag:Bty35+AhPQoBVB08MGq+rg==,type:str]
credentials-file: ENC[AES256_GCM,data:PW9iqbnh33jwl/RB9l+7drEhAna0W6l+0uyuS9hIHkYHJIyDbVW96eGZ9Eq8P5BkuAkJeykP0ynh4Q==,iv:IM/AE90Ou48oRzfVIrV2R5bCvIk0mY47STPfT75ovwk=,tag:4LzJcVK2hSoLfEY3Cw+h0w==,type:str]
ingress:
  - hostname: ENC[AES256_GCM,data:7PhcfK9LWY9REvyN/fkqadn/e6yJKQ==,iv:5cYeUSmEW5Xs0HP54ZlyapwdsyHBNWZdA702nDwKd4E=,tag:/oTfHIei++izna0FgjboDg==,type:str]
    service: ENC[AES256_GCM,data:bFoKgYZ0s81niJaaWwPvnnFTsazTZ8/P/oQ=,iv:uSNATJb5PN0ziBHucMGfZQEb7+XG+7gcxBtuyHDLe7M=,tag:N18Scz9lN30ohx8Ut5+pow==,type:str]
  - hostname: ENC[AES256_GCM,data:lIMys/jZe198gs7s67qGuWSXPDLWPKPX7Bvv,iv:ON3w07vFvPdWYZVRaDxN/Tus2SWRqAkPlqggPjo9qRo=,tag:SlB+wAWZI6cZEfMIFSNt6w==,type:str]
    service: ENC[AES256_GCM,data:PV85zlb9j3BS6nf5TsYIQAqE0Vt7J7oRSaM=,iv:CjwStcOe2HavbONZaAiJIFdu8bRJSHDlqvEl+5CVo94=,tag:5RGXJPBaW5tGUjDDzWEd5Q==,type:str]
  - service: ENC[AES256_GCM,data:AQ1GnTDbZXNFBWuSYjJ1,iv:5XBMl+uFBpR9X9mUYn1p8WRtSmEJ1sMTjFFr9CjYGRU=,tag:aP4gy+30827y9uR54k8+Qw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMHBNeTBiWXF1cmVnOHl0
        Ym5WTWpQeWt1UHAzcW83Rmp2NFI3cHR6ZzFjClhxMXN1OHJhaGRYNzcvMkZwSWVI
        Sys2NW52Y3VhVnZ2bnhkRGpGWVNLdTQKLS0tIFErVHJDbXFMZzBEbWZYM2Z2cTNw
        bmNBcDd1bDd2RzlnSHV5RTNCVldMV1UKWyC45ajwhYCBFOcN8Q8/UoLWDqdQyuNH
        jbYRRRgoPusYoDbjOiGVYIiqX5iIkHVUspp1FXBRAPWmhckBieKAEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-24T20:39:05Z"
  mac: ENC[AES256_GCM,data:2eG19jR8GwXjdVqI+IPWBi4uLkb/E0lIx1zFchbnFQRmLew27vIXZn3Ogw1DVT1tW3bnLPtvQrvDfC9SNDJanRCrUseE0HRTK/smIV21PHxA1XzZZqDpDKgTDv8EuZ0J0f7dhu90ROB+FLlF6m4oQQQJypw/GwgbDO2dyVfxEpQ=,iv:MVR1mou6HcsER6RrPrgms/Rnpq/S7dGSv7QihLZOojE=,tag:nUUV8tv4+LjjKZy2je7boQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.2
