tunnel: ENC[AES256_GCM,data:/VWIv7FD/vY67XQFvgPsvOyq9WlZwdUX+Wyfs3bebxyGI7d+,iv:hEn4f5AqWdAt+QvBQF907qrCHxpqGGgaccMLfcaUgO0=,tag:+ZFo91DAq9A87LfbCJKJzQ==,type:str]
credentials-file: ENC[AES256_GCM,data:7lBRQx7On/3CAyoBkB9PrN5sD38d265+pJtWSvq43Zf5xvF6xwjE9SSa4xw31FJHIdzUFo3lHimNaA==,iv:wJLKfKnehOROOT3NrqL2Wkb4buKhsBMyOJryflBeJMA=,tag:mkxnM+zD0aLpxu5F0ybZtg==,type:str]
ingress:
    - hostname: ENC[AES256_GCM,data:GCTtrwZhhczZhDESMs0/J1YThg6tfQ==,iv:PTJ6eZtgs/Dsm2O2ou5HeoWXtPR6uth9ZWbESTT6Nr8=,tag:4Yg6stUvartSBlcyzh4plA==,type:str]
      service: ENC[AES256_GCM,data:6xCjq+6C7I2OLvdpeN/8o6EQcb+OoekiyJE=,iv:1OOmBd9wGOC6Phcira8vv2bNsbGGoIEjSKUWjxpYWAI=,tag:JpSzO0Q1S34GS8p8ceglMw==,type:str]
    - hostname: ENC[AES256_GCM,data:6/n9Ef7DrLjQGQh7eBANRewe/DshyhsD7npR,iv:yvE+iDLM+R1E503awe9i+r+i8cCGXXOkO69cgPm+5WE=,tag:/JmOi0CTl3fgpDj88dciMg==,type:str]
      service: ENC[AES256_GCM,data:WCSELCzdmpGtz9vwIe4cxncYU56diyG7LeM=,iv:myC/QT/61VlimVPa2SzcyB9evaPN6IWUNeq2HueXV9M=,tag:kiCWAJKHbvsYPNu0QoxCFQ==,type:str]
    - service: ENC[AES256_GCM,data:xMjz7/vVqn1duzS+HA+h,iv:7kJC+diz09bghSJtugPftCNK91xJhTAvHU0YOmpCQfY=,tag:F8s0ek6mZFmQGhLrlVi/Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hhnjylnwfh0w6sxzlvc905ma8wa5pkspv9k2kj8a0d993m8h734se3jh7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Wk9LWVV4cW9ibTBIYlZn
            TWxSRm82TlFiN2FvaWcvbEplYVJUVTlOa0ZNClJweXZZWTZlcDZYRUxGZXdBWWhW
            aHRYQ2wwclBiWG5YL2ZJLzA1UW5NaGcKLS0tIDRrMHBFZXVkVU5QcVhXRU9PenZE
            ckRickRuQzlnRERFTnNkc1ZRTTZhajAKdC8kCkZVDkVF6LZLxe2ItXI9QqhQNkGv
            CoFznQsOzKzsLjqs4geYRpkELrHNCpd2wm3cfmxnLzPYUn6vH2wgKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-21T17:54:58Z"
    mac: ENC[AES256_GCM,data:wplDmrgo8G2G6eCgsLsWoc0fbn9c90lO9DddPXqA3nvdMSl3JMRVHN/0ta4eY/B3XdpBifCOEjaSOfYXRqNfvbaDE8jpLeX+o4yolITvVG64/G7fTssdxGUdf2f/cNN89ue9AYmAgeCbdAUef9oOUCzJGu+v3y8efCMcRi2KZIc=,iv:7ENzLCfAMBQ80eUcDAkEYgy1yNhTh3mqnGEkq7pTlVM=,tag:+S1LYqzrx67rJE5rskcKuQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
