services:
  unbound:
    image: docker.io/klutchell/unbound:latest
    container_name: unbound
    volumes:
#      - ./unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound.conf:/usr/local/etc/unbound/unbound.conf:ro
#      - ./custom.conf.d:/etc/unbound/custom.conf.d:ro
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
    restart: unless-stopped
    labels:
      io.containers.autoupdate: "registry"
