version: "3"


services:
  traefik-app:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
      - 5432:5432
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./app/letsencrypt:/letsencrypt
      - ./dynamic.yaml:/etc/traefik/dynamic.yaml:ro
    command:
      - --api.insecure=false
      - --api=true
      - --api.dashboard=true
      - --log.level=DEBUG
      - --accesslog=true
      - --metrics.prometheus=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
#      - --entrypoints.web.forwardedHeaders.trustedIPs=192.168.86.1/24,172.29.0.0/16,172.17.0.1/16
#      - --entryPoints.web.forwardedHeaders.insecure
      - --entrypoints.websecure.address=:443
#      - --entrypoints.websecure.forwardedHeaders.trustedIPs=192.168.86.1/24,172.29.0.0/16,172.17.0.1/16
#      - --entryPoints.websecure.forwardedHeaders.insecure
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAIN}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAIN}
      - --entrypoints.websecure.http.tls.certresolver=myresolver
      - --certificatesresolvers.myresolver.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.myresolver.acme.email=${MAIL_ADR}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory  # STG: https://acme-staging-v02.api.letsencrypt.org/directory  PROD: https://acme-v02.api.letsencrypt.org/directory
    environment:
      CF_API_KEY: ${CF_API_KEY}
      CF_API_EMAIL: ${CF_API_EMAIL}
      CLOUDFLARE_POLLING_INTERVAL: 10
      CLOUDFLARE_PROPAGATION_TIMEOUT: 180
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_network
      traefik.http.routers.traefik.rule: Host(`${APP_URL}`)
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.http.routers.traefik.service: api@internal
      traefik.http.middlewares.traefik-dashboard-auth.basicauth.users: jsmith:${TRAEFIK_DOCKER_PASSWORD}
      traefik.http.routers.traefik-dashboard-http-router.middlewares: traefik-dashboard-auth

networks:
  default:
    name: traefik_network
    external: true
