---
collections:
  - name: community.zabbix
    version: 2.4.0
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.2.0
  - name: newrelic.newrelic_agents
    version: 1.0.4

roles:
## Examples ##
# from galaxy
# - src: artis3n.tailscale

# # from GitHub
# - src: https://github.com/bennojoy/nginx

# # from GitHub, overriding the name and specifying a specific tag
# - src: https://github.com/bennojoy/nginx
#   version: master
#   name: nginx_role
## End Examples ##

- src: artis3n.tailscale

- src: staticdev.pyenv

- src: geerlingguy.docker

- src: stephdewit.nvm

- src: avanov.pyenv

- src: patrickjahns.promtail
