version: '3.1'
services:
  web:
    # image: alerta/alerta-web
    build: .
    image: alerta-web
    container_name: alerta
    ports:
      - 8082:8080
    environment:
      # - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=${PG_CONN_STRING_ALERTA}
      - AUTH_REQUIRED=True
      - ADMIN_USERS=${ZEMAIL}
      - ADMIN_PASSWORD=super-secret # default is "alerta"
      - ADMIN_KEY=demo-key  # assigned to first user in ADMIN_USERS
      - ADMIN_KEY_MAXAGE=500
      - PLUGINS=remote_ip,reject,heartbeat,blackout,normalise,enhance,influxdb,prometheus,slack,syslog
    restart: always
