---
services:
  pgweb:
    container_name: pgweb  # optional
    restart: always  # optional
    image: docker.io/sosedoff/pgweb
    ports:
      - "8084:8081"
#    links:
#      - postgres:postgres  # my database container is called postgres, not db
    environment:
      - PGWEB_DATABASE_URL=${DATABASE_URL}
