version: "3"

services:
  # --- LinkAce Image with PHP and nginx
  app:
    image: linkace/linkace:simple
    restart: unless-stopped
    container_name: linkace
    ports:
      - "0.0.0.0:718:80"
      - "0.0.0.0:719:443"
    volumes:
      - ./linkace.env:/app/.env
      - ./backups:/app/storage/app/backups
      - linkace_logs:/app/storage/logs
      # Remove the hash of the following line if you want to use HTTPS for this container
      #- ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      #- /path/to/your/ssl/certificates:/certs:ro
    labels:
      traefik.enable: false
      traefik.docker.network: traefik_network
      traefik.http.routers.linkace.rule: Host(`linkace.timmybtech.com`)
      traefik.http.services.linkace.loadbalancer.server.port: 718

volumes:
  linkace_logs:
  db:
    driver: local

networks:
  default:
    name: traefik_network
    external: trueß
