
version: '3.9'
services:
# First run `systemctl start --user podman.socket`
    podman-exporter-rootless:
        image: quay.io/navidys/prometheus-podman-exporter
        security_opt:
            - label=disable
        userns_mode: 'keep-id:uid=65534'
        ports:
            - '9882:9882'
        volumes:
            - '$XDG_RUNTIME_DIR/podman/podman.sock:/run/podman/podman.sock'
        environment:
            - 'CONTAINER_HOST=unix:///run/podman/podman.sock'

# First run `systemctl start podman.socket`
    podman-exporter-root:
        image: quay.io/navidys/prometheus-podman-exporter
        security_opt:
            - label=disable
        ports:
            - '9882:9882'
        user: root
        volumes:
            - '/run/podman/podman.sock:/run/podman/podman.sock'
        environment:
            - 'CONTAINER_HOST=unix:///run/podman/podman.sock'

# First run `podman system service --time=0 tcp://<ip>:<port>`
    podman-exporter-tcp:
        image: 'quay.io/navidys/prometheus-podman-exporter:latest'
        ports:
            - '9882:9882'
        network_mode: host
        environment:
            - 'CONTAINER_HOST=tcp://<ip>:<port>'

