version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    security_opt:
      - apparmor:unconfined
      - "label=type:container_runtime_t" # for podman use
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:z # for podman use
    environment:
      - DOZZLE_REMOTE_AGENT=192.168.86.53:7007
      - DOZZLE_HOSTNAME=pihole2
    ports:
      - 9999:8080
    restart: unless-stopped
