version: "3.8"

services:
  prometheuscommunity:
      network_mode: host
      container_name: 'postres_exporter'
      environment:
          - 'DATA_SOURCE_NAME=${DATA_SOURCE_NAME}'
      image: quay.io/prometheuscommunity/postgres-exporter
      restart: unless-stopped
