---
services:
  fail2ban:
    image: registry.gitlab.com/hectorjsmith/fail2ban-prometheus-exporter:latest
    container_name: fail2ban-exporter
    volumes:
    - /var/run/fail2ban/:/var/run/fail2ban:ro
    user: root
    pid: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    network_mode: host
