# I run monika on oracle aarch64 linux, so I had to build the image myself
# I also have two configs, one for all services and one for the databases
# git clone https://github.com/hyperjumptech/monika.git
---
version: '3.3'
services:
    monika:
        build:
          context: ./monika
          dockerfile: Dockerfile
        container_name: monika_all
        network_mode: host
        volumes:
            - './config:/config'
        command: monika -c /config/monika_all.yml --prometheus 3001
    monika_2:
        build:
          context: ./monika
          dockerfile: Dockerfile
        container_name: monika_db
        network_mode: host
        volumes:
            - './config:/config'
        command: monika -c /config/monika_db.yml
