version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:1.32.7
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://vaultwarden.timmybtech.com"  # Your domain; vaultwarden needs to know it's https to work properly with attachments
      DATABASE_URL: ${DATABASE_URL}
      SIGNUPS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      ADMIN_TOKEN: ${BITWARDEN_ADMIN_TOKEN}
    volumes:
      - ./vw-data:/data
    ports:
      - '8081:80'
      - '3012:3012'
