version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "portainer_data:/data"
    ports:
      - "8000:8000"
      - "9443:9443"

volumes:
    portainer_data:
        external: true
