services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      # Install packages during installation
      # - DOCKER_MODS=linuxserver/mods:code-server-python3|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-terraform|linuxserver/mods:code-server-zsh
      #  - DOCKER_MODS=linuxserver/mods:code-server-zsh
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
      #optional
      - PASSWORD=${PASSWORD}
      #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - PROXY_DOMAIN=code-server.timmybtech.com
      #- DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./config:/config
      - ./bin/:/usr/local/bin/:Z
    ports:
      - 8443:8443
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_network
      traefik.http.routers.code-server.rule: Host(`code-server.timmybtech.com`)
      traefik.http.services.code-server.loadbalancer.server.port: 8443
      io.containers.autoupdate: "registry" # for use with podman

networks:
  default:
    name: traefik_network
    external: true
