version: '3'
services:
  orbital-sync:
    image: mattwebbio/orbital-sync:latest
    container_name: orbital-sync
    environment:
      PRIMARY_HOST_BASE_URL: ${PRIMARY_HOST_BASE_URL}
      PRIMARY_HOST_PASSWORD: ${PRIMARY_HOST_PASSWORD}
      SECONDARY_HOST_1_BASE_URL: ${SECONDARY_HOST_1_BASE_URL}
      SECONDARY_HOST_1_PASSWORD: ${SECONDARY_HOST_1_PASSWORD}
      INTERVAL_MINUTES: 60
      NOTIFY_ON_SUCCESS: 'false'
      NOTIFY_ON_FAILURE: 'true'
      NOTIFY_VIA_SMTP: 'true'
      VERBOSE: 'true'
      TZ: 'America/New_York'
      SMTP_HOST: 'smtp.gmail.com'
      SMTP_PORT: 587
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD} # https://myaccount.google.com/apppasswords
      SMTP_TO: ${SMTP_TO}
