---
version: "3.8"

services:
  bitwarden:
    env_file:
      - settings.env
    image: bitwarden/self-host:beta
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - bitwarden:/etc/bitwarden

volumes:
  bitwarden:
