# This from a test I did to try out cortex
---
version: '3.3'
services:
    consul:
        container_name: consul
        network_mode: cortex
        environment:
            - CONSUL_BIND_INTERFACE=eth0
        image: consul

    cortex1:
        depends_on:
            - consul
        container_name: cortex1
        network_mode: cortex
        volumes:
            - './single-process-config-blocks.yaml:/etc/single-process-config-blocks.yaml'
        ports:
            - '9001:9009'
        image: quay.io/cortexproject/cortex:v1.15.3
        command: -config.file=/etc/single-process-config-blocks.yaml -ring.store=consul -consul.hostname=consul:8500 -distributor.replication-factor=3

    cortex2:
        depends_on:
            - consul
        container_name: cortex2
        network_mode: cortex
        volumes:
            - './single-process-config-blocks.yaml:/etc/single-process-config-blocks.yaml'
        ports:
            - '9002:9009'
        image: quay.io/cortexproject/cortex:v1.15.3
        command: -config.file=/etc/single-process-config-blocks.yaml -ring.store=consul -consul.hostname=consul:8500 -distributor.replication-factor=3

    cortex3:
        depends_on:
            - consul
        container_name: cortex3
        network_mode: cortex
        volumes:
            - './single-process-config-blocks.yaml:/etc/single-process-config-blocks.yaml'
        ports:
            - '9003:9009'
        image: quay.io/cortexproject/cortex:v1.15.3
        command: -config.file=/etc/single-process-config-blocks.yaml -ring.store=consul -consul.hostname=consul:8500 -distributor.replication-factor=3
