route:
    receiver: 'slack'
    # send all alerts
    group_by: ['...']

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#alerts'
            api_url:  '${SLACK_APP_URL}'
            icon_url: https://avatars3.githubusercontent.com/u/3380462
