version: "3"

networks:
  gitea:
    external: false

# to use named volumes, uncomment the following lines
# volumes:
#   gitea:
#     driver: local

services:
  server:
    image: gitea/gitea:1.21.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      # - gitea:/data # to use named volumes, uncomment this line
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
