services:
  pulse-server:
    image: docker.io/rcourtman/pulse:latest
    container_name: pulse
    restart: unless-stopped
    ports:
      - "7655:7655"
    env_file:
      - .env
    labels:
      io.containers.autoupdate: "registry"
