services:
#  pulse-server:
#    image: docker.io/rcourtman/pulse:latest
#    container_name: pulse
#    restart: unless-stopped
#    ports:
#      - "7655:7655"
#    env_file:
#      - .env
#    labels:
#      io.containers.autoupdate: "registry"

services:
  pulse:
    image: docker.io/rcourtman/pulse:latest
    container_name: pulse
#    network_mode: host
    ports:
      - "7655:7655"
    volumes:
      - pulse_data:/data
    environment:
      - TZ=America/New_York
      # - PUID=1000  # Optional: Set user ID (uncomment and adjust as needed)
      # - PGID=1000  # Optional: Set group ID (uncomment and adjust as needed)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7655"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      io.containers.autoupdate: "registry"

volumes:
  pulse_data:
    driver: local
