# repo: https://github.com/eko/pihole-exporter/blob/master/docker-compose.yml
# On the host this runs within the same docker-compose.yaml as pi-hole
---
version: '3.9'
services:
  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:v0.3.0
 #   ports:
 #     - "9617:9617"
    network_mode: 'host'
    environment:
      PIHOLE_HOSTNAME: "127.0.0.1"
      #PIHOLE_API_TOKEN: "mytoken_from_webui"
      PIHOLE_PASSWORD: "mywebpassword"
      PORT: "9617"
      INTERVAL: "30s"
    restart: unless-stopped
 #   networks:
 #     - pihole
