services:
  intellissh:
    image: docker.io/clusterzx/intellissh:latest
    container_name: intellissh
    ports:
      - 8083:3000
    volumes:
      - intellissh_data:/app/server/data
    restart: unless-stopped

volumes:
  intellissh_data:
