version: '3'
services:
  orbital-sync:
    image: mattwebbio/orbital-sync:1
    container_name: orbital-sync
    environment:
      PRIMARY_HOST_BASE_URL: 'http://192.168.86.174'
      PRIMARY_HOST_PASSWORD: '${PIHOLE_PASSWORD}'
      SECONDARY_HOST_1_BASE_URL: 'http://192.168.86.42'
      SECONDARY_HOST_1_PASSWORD: '${ZPASSWORD}'
      INTERVAL_MINUTES: 30
      NOTIFY_ON_SUCCESS: 'true'
      NOTIFY_ON_FAILURE: 'true'
      NOTIFY_VIA_SMTP: 'true'
      VERBOSE: 'true'
      TZ: 'America/New_York'
      SMTP_HOST: 'smtp.gmail.com'
      SMTP_PORT: 587
      SMTP_USER: '${EMAIL}'
      SMTP_PASSWORD: '${EMAIL_APP_PASSWORD}'
      SMTP_TO: '${EMAIL}'
