---
# version using deprecated DATA_SOURCE_NAME
version: '3.3'
services:
    mysqld-exporter:
        network_mode: host
        # ports:
        #     - '9104:9104'
        environment:
            - 'DATA_SOURCE_NAME={MYSQL_DB_USER}:${MYSQL_DB_PASSWORD}@(${MYSQL_DB_HOST}:3306)/'
        image: prom/mysqld-exporter
        container_name: mysqld_exporter
        restart: unless-stopped
---
# version using --config.my-cnf (can also pass as command line arguments)
version: '3.9'
services:
    mysqld-exporter:
        command: '--config.my-cnf=<path_to_cnf>'
        image: prom/mysqld-exporter
        networks:
            my-mysql-network: {}
        ports:
            - '9104:9104'
networks:
    my-mysql-network: {}
