services:
  araapi:
    image: "quay.io/recordsansible/ara-api:latest"
    container_name: ara-api
    ports:
      - "8009:8000"
    environment:
      ARA_DATABASE_ENGINE: "django.db.backends.postgresql"
      ARA_DATABASE_NAME: "ara"
      ARA_DATABASE_USER: ${POSTGRES_USER}
      ARA_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      ARA_DATABASE_HOST: ${POSTGRES_HOST}
      ARA_DATABASE_PORT: 5432
      ARA_DEBUG: "false"
      ARA_ALLOWED_HOSTS: "['ara-api.local.timmybtech.com']"
    volumes:
      - "./.ara/server:/opt/ara"
    tty: true
    labels:
      io.containers.autoupdate: "registry"
