services:
  araapi:
    image: "quay.io/recordsansible/ara-api:latest"
    container_name: ara-api
    ports:
      - "8009:8000"
    environment:
      ARA_DATABASE_ENGINE: "django.db.backends.postgresql"
      ARA_DATABASE_NAME: "ara"
      ARA_DATABASE_USER: ${POSTGRES_USER}
      ARA_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      ARA_DATABASE_HOST: ${POSTGRES_HOST}
      ARA_DATABASE_PORT: 5432
      ARA_SECRET_KEY: ${ARA_SECRET_KEY}
      ARA_SETTINGS: "/opt/ara/settings.yaml"
    volumes:
      - "./.ara/server:/opt/ara"
      - "./settings.yaml:/opt/ara/settings.yaml"
    tty: true
    labels:
      io.containers.autoupdate: "registry"
