---
version: "3.0"
services:
  adguardhome-sync:
    image: linuxserver/adguardhome-sync
    container_name: adguardhome-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CONFIGFILE=/config/adguardhome-sync.yaml #optional
    volumes:
      - ./config:/config
    ports:
      - 8080:8080
    restart: unless-stopped
    labels:
      io.containers.autoupdate: "registry"
