
services:
# First run `systemctl start --user podman.socket` if not already running
# Check the uid running podman.socket and update volume below if needed
# Next run `mkdir config && sudo chown -R 755 config`
# Must be running podman 4.0.0+ if not `sudo apt purge podman` then install with podman.sh
    podman-exporter-rootless:
        image: quay.io/navidys/prometheus-podman-exporter
        container_name: podman-exporter
        security_opt:
            - label=disable
        userns_mode: 'keep-id'
        ports:
            - '9882:9882'
        volumes:
            - '/run/user/${USER_ID}/podman/podman.sock:/run/podman/podman.sock:z'
            - './config:/.config'
        environment:
            - 'CONTAINER_HOST=unix:///run/podman/podman.sock'
        labels:
            io.containers.autoupdate: "registry" # for use with podman
